// Material ampliado (deep dive) para el Word de la Semana 7.
// Capital de trabajo, ciclo de conversión de caja y proveedores como aliados.
// Caso central: Andina Manufacturas S.A. (cifras en miles de USD).

export const deepDive07: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'Qué es de verdad el capital de trabajo y por qué define tu caja',
    paragraphs: [
      `El **capital de trabajo** es la plata que tu empresa necesita inmovilizar para funcionar todos los días, antes de ganar un solo peso. Técnicamente es la diferencia entre el **activo corriente operativo** (cuentas por cobrar más inventario, fundamentalmente) y el **pasivo corriente operativo** (lo que te financian los proveedores y otras cuentas espontáneas). No es un número que celebres en un asado: es el motor escondido que decide si vivís holgado o ahogado. La mayoría de los dueños de PyME mira el margen y el resultado neto, y nunca mira esta cuenta, que es exactamente donde se les escapa el oxígeno.`,
      `Conviene distinguir dos miradas que los CEOs suelen confundir. El **capital de trabajo contable** (activo corriente menos pasivo corriente) incluye caja, inversiones transitorias, deuda bancaria de corto plazo y cargas fiscales, y sirve para evaluar liquidez general. El **capital de trabajo operativo** —el que de verdad gestionás— se queda solo con lo que la operación genera y consume: cuentas por cobrar, inventario y proveedores. Esta segunda mirada es la relevante porque es la que vos podés mover con decisiones de gestión: a quién le vendés a crédito, cuánto stock tenés, a cuántos días le pagás al proveedor.`,
      `La idea central, la que hay que tatuarse, es esta: **cada peso que entra en cuentas por cobrar o en inventario es un peso que sale de tu caja**. Lo vendiste pero no lo cobraste, o lo compraste pero no lo vendiste; en ambos casos pusiste plata que todavía no volvió. Ese peso lo tenés que financiar de algún lado. Si no lo financiás gratis con proveedores, lo financiás con descubierto bancario carísimo. Por eso una empresa puede mostrar ganancia en el Estado de Resultados y estar permanentemente corriendo atrás de la caja: la utilidad quedó atrapada en activos que no se convirtieron en efectivo.`,
      `En Andina esto no es teoría. El año pasado el capital de trabajo se tragó alrededor de **880 de caja**: las cuentas por cobrar subieron **330** y los inventarios **550**, y solo los proveedores aportaron **160** para el otro lado. La empresa creció en ventas, sí, pero crecer le costó casi novecientos mil dólares de caja que tuvo que salir a financiar. Gestionar bien el capital de trabajo no es un tema contable ni de back office: es la palanca de liquidez más barata y más al alcance de la mano que tenés.`,
    ],
  },
  {
    heading: 'DSO, DIO y DPO: traducir el balance a días que un dueño entiende',
    paragraphs: [
      `Los indicadores de capital de trabajo se expresan en **días**, porque así es como un dueño piensa: "tardo tres meses en cobrar", "la mercadería me duerme medio año en el depósito". Tenemos tres reglas que convierten saldos del balance en tiempo. El **DSO (Days Sales Outstanding)** mide los días promedio que tardás en cobrarles a tus clientes: **DSO = (Cuentas por cobrar / Ventas) × 365**. Cuanto más alto, más tiempo vive tu plata en la calle, en manos de terceros, sin trabajar para vos.`,
      `El **DIO (Days Inventory Outstanding)** mide cuántos días, en promedio, la mercadería queda inmovilizada en el depósito antes de venderse: **DIO = (Inventario / CMV) × 365**. Es clave que el denominador sea el **costo de la mercadería vendida** y no las ventas, porque el inventario está valuado a costo, no a precio de venta; mezclarlos es un error frecuente que distorsiona el número hacia abajo y te da una falsa sensación de eficiencia. Un DIO alto es caja atrapada en stock, más riesgo de obsolescencia, más costo de depósito y más seguro.`,
      `El **DPO (Days Payable Outstanding)** mide cuántos días tardás en pagarle a tus proveedores: **DPO = (Proveedores / CMV) × 365**. Acá la lectura se invierte: cuanto **más alto**, mejor para tu caja, porque significa que tus proveedores te están financiando más tiempo, y gratis. El DPO es el único de los tres indicadores donde "más" es bueno, siempre que ese plazo sea negociado y cumplido, no producto de pagar mal y quedar en la lista negra.`,
      `Una técnica moderna que va más allá del manual es calcular estos indicadores con **saldos promedio** (inicio más cierre dividido dos) en lugar del saldo de cierre, sobre todo en empresas estacionales, donde la foto del 31 de diciembre puede ser atípica. También conviene segmentar: el DSO promedio puede esconder un grupo de clientes que paga a 30 días y otro que paga a 150. El promedio tranquiliza; el detalle te muestra dónde está la sangría real. Para un CEO, el verdadero valor de estos números no es calcularlos una vez, sino seguirlos mes a mes y reaccionar cuando se mueven.`,
    ],
  },
  {
    heading: 'El ciclo de conversión de caja: el indicador rey',
    paragraphs: [
      `El **ciclo de conversión de caja** junta los tres indicadores anteriores en uno solo: **Ciclo = DSO + DIO − DPO**. Es, en una sola cifra, la cantidad de días que tu plata está "atrapada" en el negocio desde que pagás un insumo hasta que cobrás la venta final. Si te da 90 días, significa que financiás 90 días de operación con tu propio bolsillo —o con el del banco—. Es, posiblemente, el indicador más honesto de la salud financiera de una PyME, porque resume cobranza, rotación y financiamiento de proveedores en un solo número accionable.`,
      `Vale entender la **lógica temporal** detrás de la fórmula. Primero comprás materia prima y la transformás: ahí empieza a correr el reloj del inventario (DIO). Una parte de ese tiempo te lo banca el proveedor, que todavía no le pagaste (DPO). Cuando vendés, el reloj del inventario para, pero arranca el de la cobranza (DSO), porque vendiste a crédito. El ciclo neto es todo lo que tenés que financiar vos: el tiempo de inventario más el de cobranza, menos el que te regaló el proveedor. Por eso el DPO **resta**: es el único tramo que no sale de tu caja.`,
      `Cada día que recortás del ciclo es **caja que vuelve a tu cuenta sin pedir un préstamo**. La fórmula para estimar cuánta caja libera bajar el ciclo es directa: días recortados × (costo diario de operación). Para el inventario y proveedores el costo diario es CMV/365; para las cuentas por cobrar es Ventas/365. Esta cuenta convierte una mejora de gestión abstracta ("cobrar un poco antes") en un número de pesos concreto que el dueño puede comparar contra el costo del descubierto que va a cancelar.`,
      `Existe el caso virtuoso del **ciclo negativo**: empresas que cobran antes de pagar (supermercados, algunos modelos de suscripción) operan con capital de trabajo negativo, es decir, sus proveedores y clientes les financian el crecimiento. Una PyME industrial como Andina difícilmente llegue a ciclo negativo, pero el norte es claro: acortar el ciclo todo lo posible. Cada día menos es plata propia liberada que reemplaza deuda cara.`,
    ],
  },
  {
    heading: 'Andina en números: el ciclo de 154 días que la empuja al descubierto',
    paragraphs: [
      `Pongamos los números reales de Andina 2024 en la fórmula. Ventas **8.200**, CMV **5.740**, cuentas por cobrar **1.850**, inventario **2.400**, proveedores **1.280**. El **DSO = (1.850 / 8.200) × 365 ≈ 82 días**: Andina tarda casi tres meses en cobrarles a sus clientes, su plata vive en la calle. El **DIO = (2.400 / 5.740) × 365 ≈ 153 días**: la mercadería pasa más de **cinco meses** en el depósito antes de venderse. El **DPO = (1.280 / 5.740) × 365 ≈ 81 días**: le paga a los proveedores a 81 días, lo único que la sostiene.`,
      `**Ciclo = 82 + 153 − 81 ≈ 154 días.** Andina necesita financiar 154 días de operación. Como los proveedores solo le cubren 81 de esos días, **los otros 73 los financia con descubierto bancario al 85% de TNA**. Acá está el origen directo y demostrable de los **560 de intereses** que en la Semana 5 vimos cómo se comían el EBIT: no es mala suerte ni un mercado difícil, es un ciclo de conversión descontrolado que obliga a tapar el agujero con el producto bancario más caro que existe.`,
      `El problema más grave, lejos, es el **inventario**. Un DIO de 153 días no es "tener buen surtido para el cliente": es caja muerta esperando convertirse en pérdida, y de hecho dentro de ese stock hay **420 de mercadería obsoleta** valuada a costo histórico que a mercado vale bastante menos. Hagamos la cuenta de la oportunidad: si Andina llevara su DIO de 153 a 90 días, recortaría 63 días de inventario. Eso libera aproximadamente **63 × (5.740/365) ≈ 990 de caja**, suficiente para cancelar casi todo el descubierto de 540 y todavía sobra para bajar otros pasivos caros.`,
      `Si además mejorara el DSO de 82 a 65 días (17 días menos × 8.200/365 ≈ **382 de caja**) y estirara el DPO de 81 a 95 días como aliado estratégico (14 días más × 5.740/365 ≈ **220 de caja**), el ciclo bajaría de 154 a alrededor de 60 días y liberaría en conjunto cerca de **1.480 de caja**. No es un préstamo que hay que ir a pedir: es plata propia, gratis, que ya está adentro de la empresa, atrapada en una gestión perfectible.`,
    ],
  },
  {
    heading: 'Rotaciones: la otra cara de los días',
    paragraphs: [
      `Las **rotaciones** miden lo mismo que los días, pero al revés: en vez de "cuánto tarda", responden "cuántas vueltas da" tu plata en un año. Son útiles porque dialogan directamente con la rentabilidad y con el análisis DuPont que vimos antes. La **rotación del activo = Ventas / Activo total** indica cuántos pesos de venta generás por cada peso de activo invertido; es una medida pura de eficiencia. Andina, que vende 8.200 con un activo total cercano a 7.500, rota alrededor de **1,09 veces**: exprime poco cada peso, en buena medida por el exceso de inventario y de cuentas por cobrar.`,
      `La **rotación de cuentas por cobrar = Ventas / Cuentas por cobrar** dice cuántas veces al año cobrás toda tu cartera. En Andina, 8.200 / 1.850 ≈ **4,4 vueltas**, que es exactamente el inverso del DSO de 82 días (365 / 82 ≈ 4,4). Una rotación alta significa **buena cobranza**: el dinero vuelve rápido y se puede reinvertir. Análogamente, la **rotación de inventario = CMV / Inventario** en Andina da 5.740 / 2.400 ≈ 2,4 vueltas al año, el inverso de un DIO de 153 días: el inventario apenas da dos vueltas y media, cuando una metalmecánica sana debería estar en cinco o seis.`,
      `Una **buena cobranza** no es solamente cobrar: es cobrar en plazo, sin estirar, sin acumular mora. La cartera de Andina incluye **290 de mora mayor a 120 días con baja probabilidad de cobro**: eso no es una cuenta por cobrar, es una pérdida disfrazada de activo. Vender mucho y cobrar mal es regalar la mercadería con cara de negocio. Por eso conviene mirar la rotación junto con un **aging de cartera** (apertura por tramos de antigüedad): la rotación promedio te da el termómetro general, el aging te muestra dónde está la infección.`,
      `La técnica moderna acá es atar las rotaciones a **incentivos y a tecnología**. Comisiones de venta que se pagan recién al cobrar (no al facturar) alinean a la fuerza comercial con la caja. Tableros que muestran la rotación por cliente, por producto y por vendedor convierten un indicador anual en una herramienta de gestión semanal. Y sistemas de gestión de stock que avisan cuándo un SKU dejó de rotar permiten actuar antes de que se vuelva obsoleto.`,
    ],
  },
  {
    heading: 'Proveedores como aliados: financiamiento no oneroso',
    paragraphs: [
      `Acá está la jugada más inteligente y más subestimada del capital de trabajo. De todas las fuentes de financiamiento que tiene una empresa, **los proveedores son la única que no cuesta intereses**: es financiamiento **no oneroso**, gratis. Cada día que estirás —de forma negociada y cumpliendo— el pago a proveedores es un día menos que financiás con descubierto al 85%. Mientras el banco te cobra una tasa que te destruye el resultado, el proveedor te banca sin cobrarte un peso extra, siempre que la relación esté bien construida.`,
      `Pero esto **no se hace pagando tarde y mal**, generando conflicto y quedando en la lista negra. Se hace convirtiendo al proveedor en un **aliado, en un socio estratégico**. El proveedor que confía en vos te da más plazo, mejores precios y prioridad cuando hay escasez de insumos. Esa relación vale oro y se construye con previsibilidad, volumen y cumplimiento: si sos el cliente que siempre paga el día acordado y crece, el proveedor prefiere financiarte a vos antes que a otro.`,
      `Las palancas concretas para usar al proveedor como financista son varias: **negociar plazos más largos** a cambio de volumen, previsibilidad o exclusividad; acordar **esquemas de consignación** o entregas escalonadas que bajan tu inventario (el stock lo banca el proveedor hasta que lo usás); construir **reputación de buen pagador** que te abre crédito comercial cuando más lo necesitás; y, en cadenas más sofisticadas, usar **confirming o factoring inverso**, donde un banco le adelanta al proveedor y vos pagás al final, mejorando tu DPO sin perjudicarlo a él.`,
      `La ventaja decisiva es financiera **y** de riesgo: el proveedor bien gestionado te financia barato **sin aumentar tu riesgo financiero**. A diferencia del banco, no te ejecuta una garantía, no te acelera la deuda ni te sube la tasa de un día para el otro por una calificación crediticia. Convertir proveedores en aliados es, en esencia, **reemplazar deuda cara y riesgosa por financiamiento gratis y estable**. En Andina, subir el DPO de 81 a 95 días libera unos 220 de caja sin pisar un banco.`,
    ],
  },
  {
    heading: 'Interrelaciones: cómo el capital de trabajo se conecta con todo lo demás',
    paragraphs: [
      `El capital de trabajo no vive aislado: es el nudo donde se cruzan casi todos los conceptos del programa. Su conexión más directa es con la **caja y el flujo de fondos**. El Estado de Resultados puede mostrar 175 de ganancia, pero el aumento del capital de trabajo (880 en Andina) explica por qué esa ganancia nunca aparece en la cuenta bancaria. La utilidad no es caja hasta que se cobra y el stock se vende; el capital de trabajo es exactamente la brecha entre rentabilidad y liquidez.`,
      `Hay una cadena causal nítida que recorre todo el caso: **DIO alto + DSO alto → ciclo de 154 días → necesidad de financiar 73 días con descubierto al 85% → 560 de intereses → el EBIT de 830 se desploma a 175 de resultado neto**. Es decir, la mala gestión del capital de trabajo no se queda en el balance: viaja hasta la última línea del Estado de Resultados y se come la rentabilidad. El descubierto no es la enfermedad, es el síntoma; la enfermedad es el ciclo de conversión.`,
      `También conecta con la **rentabilidad sobre el capital (ROIC)** y con el **costo del capital (WACC)** que veremos en la Semana 9. El capital de trabajo es parte del **capital invertido**: cada peso atrapado en cuentas por cobrar e inventario es un peso que exige rendimiento. Si Andina tiene 4.250 inmovilizados en capital de trabajo operativo y su WACC ronda el 21-22%, ese capital ocioso "cuesta" cerca de 900 al año solo en costo de oportunidad. Liberar capital de trabajo mejora el ROIC por dos vías: sube la rotación y baja el capital invertido.`,
      `Por último, se enlaza con los **bienes de uso y el CAPEX** de la Semana 8. Ambos son caños por donde se va la caja cuando una empresa crece, y deben leerse juntos: la variación del capital de trabajo más el CAPEX explican por qué una empresa rentable puede estar siempre tensa. Y se conecta con la **valuación**, porque un comprador serio mira el capital de trabajo normalizado: un ciclo inflado es menor caja libre, y menor caja libre es menor valor de la empresa.`,
    ],
  },
  {
    heading: 'Errores frecuentes del CEO',
    paragraphs: [
      `**Confundir ganancia con caja.** El error madre. El CEO mira el resultado neto positivo y no entiende por qué vive en el descubierto. La respuesta casi siempre está en el capital de trabajo: la ganancia quedó atrapada en cuentas por cobrar e inventario. Si no separás rentabilidad de liquidez, vas a tomar decisiones de crecimiento que te ahogan la caja.`,
      `**Tratar el descubierto como financiamiento estructural.** El descubierto bancario debería tapar baches puntuales de días, nunca financiar de forma permanente tu inventario y tu cartera. A una TNA del 85%, usar descubierto para bancar 73 días estructurales de ciclo es lo que genera buena parte de los 560 de intereses de Andina. Es la solución más fácil de pedir y la más cara de pagar.`,
      `**Festejar el inventario alto como "buen surtido".** Muchos dueños se enorgullecen de tener depósito lleno. Pero un DIO de 153 días no es servicio al cliente: es caja muerta, costo de depósito, riesgo de obsolescencia y, tarde o temprano, remate bajo costo. El inventario que no rota es el peor de los males del capital de trabajo porque combina inmovilización con riesgo de pérdida directa.`,
      `**Calcular mal los indicadores y pagar mal a los proveedores.** Usar ventas en lugar de CMV para el DIO y el DPO infla la eficiencia aparente y te tranquiliza falsamente. Y, del otro lado, creer que "estirar al proveedor" es pagarle tarde y mal: eso destruye la relación, te corta el crédito y te empuja de vuelta al banco. Estirar el DPO solo funciona si es negociado, previsible y cumplido.`,
    ],
  },
  {
    heading: 'Qué decisiones habilita',
    paragraphs: [
      `Dominar el capital de trabajo habilita, primero, la decisión de **liberar caja propia antes de salir a pedir deuda**. Frente a una tensión de caja, el CEO entrenado no corre al banco: ordena el ciclo de conversión. Cobra un poco antes (baja el DSO), hace rotar el inventario (baja el DIO) y negocia plazo con proveedores (sube el DPO). En Andina eso significa liberar cerca de 1.480 de caja sin pisar una sucursal: el préstamo más barato es el que ya tenés adentro.`,
      `Habilita también **decidir el crecimiento con los ojos abiertos**. Crecer en ventas consume capital de trabajo; ahora el dueño puede calcular cuánta caja va a necesitar por cada millón adicional de facturación y financiarlo a tiempo, en vez de descubrirlo cuando ya está en el descubierto. La pregunta deja de ser "¿cuánto vendo más?" y pasa a ser "¿con qué financio el capital de trabajo de ese crecimiento?".`,
      `Permite **rediseñar la política comercial y de compras** con criterio financiero: ofrecer descuentos por pronto pago cuando el ahorro de descubierto los justifica, segmentar clientes por su comportamiento de cobranza, comprar contra pedido en vez de stockear, y construir relaciones de aliado con proveedores clave. Cada una de estas decisiones, antes intuitiva, ahora se mide en días de ciclo y en pesos de caja liberada.`,
      `Por último, habilita una **conversación distinta con el banco, con los socios y con un eventual comprador**. Un CEO que muestra que entiende y gestiona su ciclo de conversión, que tiene un plan de aging de cartera y de rotación de stock, negocia mejores condiciones y proyecta solidez. El capital de trabajo bien gestionado no solo libera caja: mejora la rentabilidad sobre el capital, baja el riesgo financiero y, en definitiva, **aumenta el valor de la empresa**.`,
    ],
  },
]
