// Material AMPLIADO para el Word de la Semana 5
// Andina Manufacturas S.A. — Lo económico vs lo financiero: liquidez y solvencia
// Español rioplatense, registro premium para CEO.

export const deepDive05: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'Dos relojes que no marcan la misma hora: el devengado y el percibido',
    paragraphs: [
      `Hay dos preguntas que un CEO confunde permanentemente, y confundirlas cuesta empresas enteras: **"¿gané plata?"** y **"¿tengo plata?"**. Parecen lo mismo, pero viven en planos distintos. La primera es **económica**: la responde el Estado de Resultados, que te dice si tu operación produjo un excedente. La segunda es **financiera**: la responde la caja, que te dice si en este momento tenés con qué pagar lo que vence. Son dos relojes que casi nunca marcan la misma hora, y el CEO que mira solo uno está siempre desfasado de la realidad.`,
      `La raíz del desfasaje es el **criterio de devengado**. La contabilidad registra una venta cuando ocurre el hecho económico —entregaste la mercadería, emitiste la factura—, no cuando entra la plata. Entonces tu Estado de Resultados puede mostrar una venta de 100 y una ganancia de 30 hoy, aunque el cliente te pague dentro de 90 días o no te pague nunca. Lo económico se devenga; lo financiero se percibe. Entre el "vendí" y el "cobré" puede haber un abismo de meses, y en ese abismo se ahoga más de una PyME rentable.`,
      `Lo mismo pasa del lado de los costos y las inversiones. Comprás una máquina por 1.000: la caja sale toda hoy (financiero), pero el resultado solo absorbe la amortización de a poco, año tras año (económico). Comprás inventario por 500: la plata se va hoy, pero el costo recién impacta el resultado cuando vendés esa mercadería. La amortización resta en el resultado pero no sale de la caja; el inventario sale de la caja pero todavía no resta en el resultado. Económico y financiero corren por carriles separados, con tiempos propios.`,
      `La conclusión operativa es contundente: **una empresa puede estar ganando en lo económico y muriéndose en lo financiero al mismo tiempo**, y no hay nada contradictorio en eso. Es, de hecho, el cuadro más común en una PyME que crece. El que gestiona mirando solo el margen no ve venir el ahogo de caja. El que mira solo la caja no entiende que está quemando rentabilidad para sobrevivir. Hay que leer los dos relojes a la vez y, sobre todo, entender cómo se hablan entre sí.`,
    ],
  },
  {
    heading: 'Liquidez: ¿puedo pagar lo que vence esta semana?',
    paragraphs: [
      `La **liquidez** mide tu capacidad de afrontar las obligaciones de corto plazo con los activos de corto plazo. Es la pregunta del viernes: ¿tengo con qué pagar el sueldo, el proveedor, el cheque que vence? Se lee con tres lentes, ordenados de más indulgente a más despiadado, y la gracia está en mirar los tres juntos, porque cada uno te cuenta una parte distinta de la verdad.`,
      `La **liquidez corriente** (Activo corriente / Pasivo corriente) es la foto gruesa: cuántos pesos de activo de corto tenés por cada peso de deuda de corto. Un valor cómodo está por encima de 1,5; cerca o por debajo de 1 ya es alerta. Pero es la lente más engañosa, porque mete adentro del activo corriente al inventario, que es lo más difícil de transformar en plata rápido y sin perder en el camino. Por eso existe la segunda lente.`,
      `La **prueba ácida** o liquidez seca ((Activo corriente − Inventarios) / Pasivo corriente) saca el inventario de la ecuación. ¿Por qué? Porque si mañana necesitás plata urgente, el stock no se vende a precio pleno: se remata, y rematar es perder margen. La ácida te pregunta: si no pudiera tocar el inventario, ¿igual llego a pagar? La diferencia entre la corriente y la ácida te dice exactamente **cuánto de tu liquidez depende de vender mercadería**. Si esa brecha es grande, tu liquidez es una ilusión óptica sostenida por stock.`,
      `La **liquidez de caja** o defensiva (Disponibilidades / Pasivo corriente) es la más cruel y la más honesta: solo cuenta lo que ya es plata —caja, bancos, inversiones líquidas inmediatas— contra todo lo que vence en el corto plazo. Es la lente de la urgencia real, la del "si tengo que pagar todo ahora, ¿con qué cuento de verdad?". En una empresa tensa, esta es la cifra que el CEO debería conocer de memoria, porque es la que separa seguir operando de tener que salir a pedir descubierto.`,
    ],
  },
  {
    heading: 'Solvencia: ¿aguanto hasta fin de año?',
    paragraphs: [
      `Si la liquidez es el corto plazo, la **solvencia** es la estructura. No pregunta si llegás a fin de mes, sino si la empresa puede sostener su deuda total a lo largo del tiempo sin quebrarse. Una empresa puede tener buena liquidez puntual y ser insolvente de fondo, o al revés. Por eso necesitás las dos miradas: la liquidez te dice si llegás a fin de mes, la solvencia te dice si llegás a fin de año.`,
      `El primer ratio de solvencia es el **endeudamiento** (Deuda total / Patrimonio Neto): cuánto pusieron los terceros por cada peso que pusieron los dueños. Cuanto más alto, más frágil sos ante cualquier sacudón, porque la deuda no espera ni negocia con tu mal momento: exige sí o sí, a término, con intereses corriendo. Una empresa muy apalancada tiene poco colchón: una caída de ventas que una empresa con poca deuda absorbería sin drama, a la apalancada la pone contra las cuerdas.`,
      `El segundo ratio —y probablemente **el más importante de toda la semana**— es la **cobertura de intereses** (EBIT / Intereses): cuántas veces tu resultado operativo cubre el costo de la deuda. Es el termómetro del estrangulamiento financiero. Si te da por encima de 3, respirás cómodo. Si te da entre 2 y 3, atención. Si te da menos de 2, estás en zona de peligro. Y si te da cerca de 1, los intereses se están comiendo casi todo lo que el negocio genera: cualquier viento en contra te tira por debajo de 1, el punto donde el negocio operativo ya no alcanza para pagarle al banco.`,
      `La cobertura de intereses es tan central porque conecta directamente lo económico con lo financiero: arriba tiene el EBIT (puro económico, lo que produce la operación) y abajo los intereses (puro financiero, el costo de la estructura). Cuando ese cociente cae, te está avisando que la estructura financiera se está tragando al negocio operativo. Es la cifra que un CEO debería mirar **todos los meses**, no una vez al año cuando ya es tarde.`,
    ],
  },
  {
    heading: 'Mini-caso numérico: el EBIT de Andina que se come la deuda',
    paragraphs: [
      `Apliquemos los lentes nuevos a **Andina 2024** y pongamos número al riesgo. Empecemos por la solvencia, que es donde duele. El EBIT (resultado operativo) es de **830**: el negocio, mirado en sí mismo, es bueno, genera un resultado operativo sano sobre ventas de 8.200. Pero los intereses financieros del año son de **560**. La cobertura de intereses es 830 / 560 = **1,48 veces**. Andina genera operativamente apenas un 48% más de lo que paga de intereses. El colchón es finísimo.`,
      `Traduzcamos ese 1,48 a lenguaje de riesgo. Significa que basta una suba de tasas, una caída de ventas del 10% o un cliente grande que deja de pagar, para que la cobertura perfore el 1. Y por debajo de 1, el EBIT ya no alcanza para cubrir los intereses: la empresa tiene que tomar **más deuda para pagar la deuda vieja**. Ahí empieza la espiral. Andina está caminando sobre una cornisa de 0,48 puntos de cobertura, y no lo sabe porque su Estado de Resultados todavía muestra ganancia.`,
      `El corazón del problema tiene nombre: el **descubierto bancario de 540 a una TNA cercana al 85%**, más los préstamos varios. Esos 560 de intereses no son un detalle financiero menor; son **la diferencia entre un resultado neto digno y los 175 raquíticos** que Andina terminó mostrando. Mirá la cadena: EBIT 830, menos intereses 560, da un resultado antes de impuestos de 270; menos el 35% de impuesto, quedan **175**. Sin esa deuda cara, el resultado neto sería más del doble. El negocio (EBIT 830) es bueno; la estructura financiera lo está estrangulando.`,
      `Ahora la liquidez, que confirma el cuadro. La caja es de apenas **180** (más 60 de inversiones transitorias), contra un descubierto de **540** ya tomado y un pasivo corriente total que supera los 3.200. La liquidez de caja es ínfima: 180 sobre más de 3.200 es del orden de **0,06**, seis centavos de plata real por cada peso que vence en el corto plazo. Andina no vive de su caja: vive del oxígeno del descubierto. Y el descubierto al 85% es el aire más caro del mercado. Caja 180 contra descubierto 540: esa sola comparación resume toda la fragilidad financiera de la empresa.`,
    ],
  },
  {
    heading: 'El círculo: cómo lo financiero alimenta lo económico y viceversa',
    paragraphs: [
      `Acá está la idea que de verdad cambia la cabeza de un CEO: lo económico y lo financiero **no son independientes, se retroalimentan**. No son dos diagnósticos separados que se hacen por las suyas; son dos engranajes de la misma máquina, y giran juntos. Entender la dirección en que se empujan es lo que permite anticipar el deterioro en vez de sufrirlo.`,
      `**De lo financiero a lo económico:** cuando te quedás sin caja, tomás descubierto. El descubierto genera intereses. Los intereses **bajan el resultado económico**. Un problema que nació financiero (faltaba caja) terminó convertido en un problema económico (cayó la ganancia). En Andina se ve cristalino: la falta de caja la empuja al descubierto del 85%, y esos 560 de intereses son los que hunden el resultado neto a 175. El agujero financiero se transformó en agujero económico.`,
      `**De lo económico a lo financiero:** y al revés también gira. Cuando el resultado económico cae, tenés menos utilidad para reinvertir y menos respaldo para conseguir deuda barata. Entonces dependés más del crédito caro, que **vuelve a drenar caja** vía intereses. Un problema que nació económico (cayó el margen) se convirtió en un problema financiero (más deuda cara, menos caja). Cada engranaje le pasa el deterioro al otro.`,
      `El círculo puede ser **virtuoso** (caja sana → poca deuda cara → buen resultado → más caja) o **vicioso** (poca caja → deuda cara → mal resultado → menos caja). Andina está claramente en el vicioso. Y lo grave del círculo vicioso es que no es lineal: en cada vuelta el costo financiero crece sobre una base de deuda más grande, mientras el resultado operativo, debilitado, crece menos o cae. Por eso la caída no es una pendiente suave: es una curva que se empina.`,
    ],
  },
  {
    heading: 'El punto crítico y la caída exponencial',
    paragraphs: [
      `La pregunta del millón es: ¿cuándo el círculo vicioso pasa de molesto a mortal? La respuesta tiene un umbral concreto: **cuando la cobertura de intereses cruza por debajo de 1**. Mientras el EBIT cubre a los intereses (cobertura mayor a 1), el círculo gira despacio y parece manejable: la empresa genera lo suficiente para pagar el costo de su deuda y le sobra algo. Es incómodo, pero es sostenible.`,
      `Cuando la cobertura perfora el 1, todo cambia de naturaleza. El negocio operativo ya no alcanza para pagar los intereses, así que hay que **tomar deuda nueva para pagar la deuda vieja**. Pero esa deuda nueva también genera intereses, sobre una base ahora más grande. Al período siguiente los intereses son mayores, el EBIT (debilitado por la falta de inversión y el clima de crisis) es igual o menor, y la cobertura cae aún más. Cada vuelta del círculo es **peor que la anterior**, y la distancia entre vueltas se acorta. El deterioro deja de ser lineal y se vuelve exponencial.`,
      `Para Andina, con cobertura de 1,48, el punto crítico está peligrosamente cerca. No hace falta una catástrofe: una recesión moderada, una devaluación que encarezca la deuda en dólares, o simplemente que el descubierto del 85% siga capitalizando intereses, pueden empujarla por debajo de 1 en cuestión de trimestres. Y una vez del otro lado, la velocidad de deterioro se multiplica. La diferencia entre 1,48 y 0,9 no son medio punto de ratio: es la diferencia entre una empresa tensa y una empresa en caída libre.`,
      `Lo más peligroso del punto crítico es que **se cruza en silencio**. No hay una sirena que suene. Un mes pedís un poco más de descubierto, al siguiente otro poco, las ventas siguen pareciendo normales, el Estado de Resultados todavía muestra ganancia. Y de pronto, sin un evento dramático, el costo financiero está creciendo más rápido que el resultado operativo. Para cuando se ve nítido en el balance, ya estás del otro lado de la curva. Por eso —insistimos— la cobertura de intereses se mira todos los meses, no una vez al año.`,
    ],
  },
  {
    heading: 'Interrelaciones: cómo esta semana conecta con todo el programa',
    paragraphs: [
      `La distinción económico/financiero es la **columna vertebral** que sostiene casi todos los conceptos del programa, y verla así ordena todo lo demás. Hacia atrás, conecta de lleno con la Semana 4 (EVA y spread). Recordá que el WACC de Andina ronda el 21% y arrastra hacia arriba justamente por la deuda cara: el descubierto al 85% no solo se come el resultado neto vía intereses, también **encarece el costo del capital** y por esa vía empeora el spread ROIC − WACC. El mismo problema financiero —la deuda cara— ataca a Andina por dos frentes: le baja la ganancia contable y le sube la valla del WACC. Lo financiero y la destrucción de valor son dos caras de la misma moneda.`,
      `Hacia adelante, conecta directamente con la Semana 6 (Free Cash Flow). El ahogo de caja de Andina no es solo culpa de los intereses: nace en el **capital de trabajo desbordado**. Las cuentas por cobrar que no se cobran y el inventario que no rota inmovilizan plata, y esa plata faltante es la que obliga a tomar descubierto. La Semana 6 va a mostrar con números cómo el ΔCxC de −330 y el Δinventario de −550 drenan el flujo; esta semana ya entendemos por qué ese drenaje es tan letal: cada peso atrapado en capital de trabajo es un peso que hay que reemplazar con deuda al 85%.`,
      `La cobertura de intereses, además, es el puente conceptual entre el **apalancamiento** (cuánta deuda) y la **estructura de costos** (cuán rígida es la empresa). Una empresa con mucha deuda y muchos costos fijos es doblemente rígida: cuando bajan las ventas, ni el resultado operativo ni el costo financiero se achican, y la cobertura se desploma. Por eso la salida de la caída exponencial pasa tanto por desarmar la deuda cara como por volver variable lo que hoy es fijo. Son la misma batalla por la elasticidad.`,
      `Finalmente, esta semana le da sentido financiero a la valuación que viene más adelante. Una empresa no vale por su ganancia contable sino por su capacidad de generar **caja sostenible** sin ahogarse, y eso requiere liquidez y solvencia sanas. Un comprador o un banco que mira a Andina no se queda en el resultado neto de 175: mira la cobertura de 1,48, la caja de 180 contra el descubierto de 540, y descuenta el riesgo de quiebre. Lo financiero, mal gestionado, no solo destruye caja: **destruye el precio** al que se podría vender la empresa.`,
    ],
  },
  {
    heading: 'Cómo salir: eficiencia, estructura liviana y comprar tiempo',
    paragraphs: [
      `Salir de la caída exponencial tiene tres movimientos, y el orden importa. El primero: **hacer eficientes los costos sin tocar el músculo**. No es recortar a ciegas —eso debilita el negocio y empeora el EBIT—, es eliminar quirúrgicamente lo que no genera valor para que el resultado operativo respire y la cobertura suba. Cada punto de margen operativo recuperado aleja el punto crítico. Si Andina lleva su EBIT de 830 a 950 limpiando ineficiencias, ya mejora su cobertura sin tocar la deuda.`,
      `El segundo movimiento: **estructuras variables, no pesadas**. Una empresa con costos fijos altos y deuda dura es rígida, y la rigidez mata en la curva: cuando bajan las ventas no puede achicarse y la caída la arrastra. Convertir fijo en variable —tercerizar procesos no centrales, alquilar en vez de comprar, pagar comisiones en vez de sueldos rígidos— le da elasticidad para doblarse sin quebrarse. Una empresa elástica sobrevive a la tormenta que hunde a la rígida con el mismo nivel de ventas.`,
      `El tercero: **ganar tiempo sin comprometer lo económico**. Reestructurar la deuda cara por deuda más barata o más larga, estirar plazos con proveedores, ordenar el capital de trabajo cobrando antes y liquidando el inventario muerto. La clave, y acá está la trampa que hay que evitar, es comprar tiempo **sin** rematar inventario a pérdida ni regalar margen para cobrar rápido. Porque eso apaga el incendio financiero prendiendo el económico: solucionás la caja de hoy destruyendo la rentabilidad de mañana, y el círculo vuelve a girar.`,
      `El objetivo de los tres movimientos es el mismo: **subir la cobertura de intereses por encima de 1 con holgura** y volver a poner el círculo a girar para el lado virtuoso. Una Andina ordenada —EBIT de 950 por costos más eficientes, intereses de 320 por reemplazar el descubierto del 85% con deuda más barata y larga— tendría una cobertura de 950 / 320 = **2,97**, saldría de la zona de peligro y su resultado neto treparía de 175 a más de 400. El negocio operativo siempre fue bueno; lo que faltaba era dejar de drenarlo por lo financiero.`,
    ],
  },
  {
    heading: 'Errores frecuentes del CEO',
    paragraphs: [
      `**Error 1: confundir rentabilidad con liquidez.** "Si soy rentable, no me puedo quedar sin plata." Falso, y peligrosamente intuitivo. La rentabilidad es económica (devengada), la caja es financiera (percibida). Podés ser muy rentable y no tener con qué pagar el sueldo del viernes, porque la ganancia está atrapada en cuentas por cobrar e inventario. Más PyMEs rentables quebraron por falta de caja que por falta de margen.`,
      `**Error 2: mirar la cobertura de intereses una vez al año.** El balance anual muestra la cobertura cuando el daño ya está hecho. El punto crítico se cruza en silencio, entre balances. El CEO que solo revisa la cobertura al cerrar el ejercicio se entera de que cruzó el umbral cuando ya está del otro lado de la curva. Esta cifra se monitorea mensualmente, como la presión arterial de la empresa.`,
      `**Error 3: tratar el descubierto como una herramienta normal.** El descubierto al 85% no es financiamiento, es una transfusión de aire carísimo. Usarlo de manera estructural —no para un bache puntual sino como fuente permanente— es garantizar la espiral. Andina lo usa todos los meses, y esos 560 de intereses son el precio de esa costumbre. El descubierto debería ser la excepción de emergencia, nunca el modo de operar.`,
      `**Error 4: apagar el incendio financiero rematando lo económico.** Bajo presión de caja, el reflejo es liquidar inventario a pérdida y dar descuentos agresivos por pago contado. Trae plata hoy, pero destruye margen y entrena a los clientes a no pagar a término. Es vender el futuro para sobrevivir el presente. La salida correcta gana tiempo sin sacrificar la rentabilidad que sostiene la empresa en el largo plazo.`,
    ],
  },
  {
    heading: 'Qué decisiones habilita',
    paragraphs: [
      `Dominar la distinción económico/financiero habilita, antes que nada, **gestionar con dos tableros en lugar de uno**. El CEO deja de pilotear mirando solo el Estado de Resultados y suma el tablero de caja: proyección de cobranzas y pagos, posición diaria, cobertura de intereses mensual. Decidir con los dos relojes a la vista permite anticipar el ahogo de caja semanas antes de que ocurra, en vez de descubrirlo el día que el banco rebota un cheque.`,
      `Habilita una **política de capital de trabajo activa**. Sabiendo que cada peso atrapado en cuentas por cobrar e inventario hay que reemplazarlo con descubierto al 85%, las decisiones de crédito a clientes, de niveles de stock y de plazos con proveedores dejan de ser administrativas y pasan a ser estratégicas. Apretar la cobranza, depurar el inventario muerto y negociar plazos con proveedores se vuelven palancas financieras de primer orden, no tareas del fondo de la oficina.`,
      `Habilita una **estrategia de desapalancamiento priorizada**. No toda la deuda es igual: el descubierto al 85% es el enemigo número uno, los préstamos en dólares al 18% son tolerables, los proveedores comerciales (financiamiento no oneroso) son aliados. La decisión que habilita esta semana es atacar la deuda por orden de toxicidad: matar primero lo más caro, reemplazándolo por estructura más barata y más larga, para subir la cobertura de intereses y aflojar el nudo financiero.`,
      `Finalmente, habilita una **conversación honesta con el banco y con uno mismo sobre el punto crítico**. En vez de negar la tensión hasta que estalla, el CEO puede poner el número sobre la mesa —"estamos en cobertura de 1,48, a 0,48 puntos del abismo"— y negociar una reestructuración desde una posición todavía de relativa fuerza, antes de cruzar el umbral. La diferencia entre reestructurar a tiempo y reestructurar en cesación de pagos es, muchas veces, la diferencia entre la supervivencia y el cierre. Esa anticipación es la decisión más valiosa que habilita la Semana 5.`,
    ],
  },
]
