// ============================================================================
// DEEP DIVE — SEMANA 1
// "Leer los estados contables sin miedo"
// Contenido ampliado y detallado para el documento Word de la Semana 1.
// Caso transversal: Andina Manufacturas S.A. (cifras en USD miles, 2024).
// ============================================================================

export const deepDive01: { heading: string; paragraphs: string[] }[] = [
  {
    heading: "Por qué un dueño necesita leer, no solo recibir, los estados contables",
    paragraphs: [
      "Hay una diferencia enorme entre **recibir** un balance y **leerlo**. Recibirlo es esperar a fin de mes que el contador te mande un PDF con un resultado abajo de todo, mirar esa última línea y decidir tu humor del trimestre en función de si dice ganancia o pérdida. Leerlo es otra cosa: es interrogar al documento, entender de dónde sale cada número, qué supuestos hay detrás y, sobre todo, qué te está ocultando. El programa entero parte de esta premisa incómoda: **el estado contable no fue diseñado para que vos decidas; fue diseñado para que rindas cuentas a terceros**. Por eso necesitás aprender a leerlo con desconfianza inteligente.",
      "Como CEO o dueño no estás obligado a saber registrar un asiento ni a dominar las normas de valuación. Esa es tarea del contador, y está bien delegarla. Lo que no podés delegar es el **juicio sobre lo que esos números significan para tu negocio**. Cuando delegás el juicio, alguien decide por vos sin querer: el sistema te muestra el margen porque es lo que está arriba y es lo más fácil de mirar, y vos terminás gobernando tu empresa con la información que el formato te puso enfrente, no con la que necesitabas.",
      "El recorrido del programa es deliberado y no se puede saltear. Primero aprendemos a **leer** los tres estados básicos: Balance, Estado de Resultados y Flujo de Efectivo. Recién cuando sabés leer la contabilidad de presentación, en las semanas siguientes vas a aprender a **buscar la información de gestión** que esa contabilidad esconde, y después a transformar todo eso en **valor**: ROIC, costo de capital, decisiones de inversión. Pero el cimiento es esta semana. Un CEO que no lee sus estados no puede pedir lo que no sabe que existe.",
      "Andina Manufacturas, nuestra empresa-caso, es el ejemplo perfecto de por qué esto importa. Su dueño mira un **resultado neto de 175** y ventas que crecieron de **7.400 a 8.200** y duerme tranquilo. Sin embargo, la caja siempre está tensa, usa descubierto bancario caro y los clientes pagan cada vez más tarde. Toda esa historia está escrita en los estados contables, pero no en la línea que el dueño mira. Está en los cruces. Aprender a leer es aprender a encontrarla.",
    ],
  },
  {
    heading: "El Balance: la foto del patrimonio a una fecha exacta",
    paragraphs: [
      "El **Balance** o Estado de Situación Patrimonial es una **foto**: capta la situación de la empresa en un instante congelado, típicamente el cierre del ejercicio. Responde tres preguntas simultáneas: qué tengo (el **Activo**), qué debo (el **Pasivo**) y qué es genuinamente mío (el **Patrimonio Neto**). No te dice qué pasó durante el año ni cómo llegaste ahí; te muestra el resultado acumulado de toda la historia de la empresa condensado en un punto del tiempo.",
      "El Activo se ordena por **liquidez**, es decir, por la velocidad con la que cada cosa se convierte en efectivo. Arriba va el **Activo Corriente**, lo que se vuelve caja en menos de un año: la caja misma, las inversiones transitorias, las cuentas por cobrar y los inventarios. Debajo va el **Activo No Corriente**, lo que está inmovilizado y produce a lo largo de varios ejercicios: terrenos, edificios, maquinaria, rodados. En Andina, el Activo Corriente está dominado por dos partidas pesadas: **cuentas por cobrar de 1.850 e inventarios de 2.400**. Esa concentración no es un detalle decorativo; es la primera señal de dónde está atrapada la plata de la empresa.",
      "El Pasivo también se ordena por exigibilidad: primero lo que hay que pagar pronto. En Andina conviven pasivos de naturaleza muy distinta que el balance presenta uno al lado del otro como si fueran equivalentes, cuando no lo son. El **descubierto bancario de 540** es un producto carísimo (con una TNA del orden del 85%); los **proveedores comerciales de 1.280** son, en cambio, financiamiento gratuito si se negocia bien. El balance los suma sin distinguir su costo, y esa indistinción es exactamente la trampa que un buen lector debe desarmar.",
      "El **Patrimonio Neto** es el residual: lo que quedaría para los dueños si se realizara todo el activo y se cancelara todo el pasivo. En Andina son **capital social de 600, reservas de 320 y resultados acumulados de 1.850**, que totalizan 2.770. Es crucial entender que el Patrimonio Neto **no es plata en una cuenta**: es una diferencia matemática, un derecho residual. Muchos dueños creen que tienen ese dinero disponible cuando en realidad está inmovilizado en máquinas, stock y cuentas por cobrar lentas.",
    ],
  },
  {
    heading: "La ecuación que sostiene todo: Activo = Pasivo + Patrimonio Neto",
    paragraphs: [
      "Toda la contabilidad descansa sobre una sola identidad: **Activo = Pasivo + Patrimonio Neto**. Lo que la empresa tiene (Activo) fue financiado o por terceros (Pasivo: bancos, proveedores, fisco) o por los dueños (Patrimonio Neto: capital aportado más resultados retenidos). No es una convención arbitraria: es una verdad lógica. Cada peso que entró a la empresa para comprar algo tuvo que venir de alguna parte, y solo hay dos fuentes posibles, terceros o dueños.",
      "Esta identidad, leída con ojos de finanzas y no de contabilidad, ya contiene una idea poderosa. El Activo es **dónde pusiste la plata**: en qué decidiste invertir. El Pasivo más el Patrimonio Neto es **de dónde salió la plata**: cómo financiaste esas inversiones. Es decir, el lado izquierdo del balance son tus **decisiones de inversión** y el lado derecho son tus **decisiones de financiamiento**. Toda la disciplina de las finanzas corporativas vive en la tensión entre esos dos lados, y por eso esta ecuación aparentemente trivial es, en realidad, el mapa completo del programa.",
      "De acá se desprende un principio que vamos a usar todo el tiempo: no todo el activo rinde lo mismo ni todo el pasivo cuesta lo mismo. Un terreno parado no produce; una máquina trabajando sí. Un proveedor que te financia gratis es un regalo; un descubierto al 85% es un agujero. El arte del CEO financiero consiste en **mejorar el lado izquierdo** (poner la plata donde más rinda) y **abaratar el lado derecho** (financiarse de la forma más barata posible). El balance es el tablero donde se juega esa partida.",
      "Un ejercicio simple con Andina lo deja claro. Su Activo total ronda los **7.470** (sumando corriente y no corriente a valor libro). Ese activo está financiado por un Pasivo de aproximadamente **4.700** (descubierto, cheques, proveedores, préstamos, cargas, previsiones) y un Patrimonio Neto de **2.770**. La identidad cierra. Pero fijate lo que cuenta: casi dos tercios del activo de Andina están financiados por terceros, y buena parte de ese pasivo es caro. Esa estructura es la semilla del problema que vamos a destripar en las semanas siguientes.",
    ],
  },
  {
    heading: "El Estado de Resultados: la película de lo económico",
    paragraphs: [
      "Si el Balance es una foto, el **Estado de Resultados** es una **película**: narra qué pasó a lo largo de un período completo, generalmente un año. Arranca con las ventas y va restando, en cascada, todo lo que costó generarlas, hasta llegar al resultado neto. Su lógica es **económica**, no financiera: registra ingresos cuando se devengan (cuando se hace la venta) y gastos cuando se incurren, **independientemente de si el dinero entró o salió de la caja**. Esta distinción —devengado versus percibido— es la madre de casi todas las confusiones de un dueño que recién empieza a leer.",
      "La cascada de Andina en 2024 es instructiva leerla escalón por escalón. **Ventas netas de 8.200**, menos un **costo de mercadería vendida de 5.740** (el 70% de las ventas), da un **resultado bruto de 2.460**. De ahí se restan **gastos de comercialización de 980 y de administración de 610**, llegando a un **EBITDA de 1.120**. Hasta acá la operación luce sana: la empresa vende, produce con un margen razonable y cubre sus gastos de estructura con holgura.",
      "Pero la película recién se pone interesante en los escalones de abajo. Las **amortizaciones de 290** —el desgaste contable de máquinas y edificios— bajan el resultado al **EBIT de 830**, el famoso resultado operativo. Y entonces aparece la línea que define el destino de Andina: **resultados financieros (intereses) de 560**. Acá se evapora la mayor parte de la ganancia operativa. El negocio genera 830 de resultado operativo, pero el costo de financiarse se lleva 560, dejando un **resultado antes de impuestos de apenas 270**. Tras el **impuesto de 95**, el **resultado neto es 175**.",
      "La lectura clave es esta: Andina tiene un **buen negocio operativo** (EBIT de 830) atrapado dentro de una **mala estructura financiera** (560 de intereses). El Estado de Resultados, leído de arriba hacia abajo, cuenta exactamente dónde se pierde la plata. El dueño que solo mira la última línea ve 175 y se conforma. El que lee la cascada ve que el negocio genera casi cinco veces eso, y que casi todo se lo come el financiamiento. Esa es la diferencia entre recibir y leer.",
    ],
  },
  {
    heading: "El Flujo de Efectivo: la otra película, la del dinero real",
    paragraphs: [
      "El **Estado de Flujo de Efectivo** es la segunda película, y para un CEO con caja tensa suele ser la más importante de las tres. Mientras el Estado de Resultados mide lo **económico** (devengado), el Flujo de Efectivo mide lo **financiero** (la caja que realmente entró y salió). Una empresa puede mostrar ganancia y quedarse sin efectivo, y puede mostrar pérdida y tener la caja llena. Resultado y caja son primos, no gemelos, y el Flujo de Efectivo existe justamente para mostrar la brecha entre ellos.",
      "El estado se divide en tres bloques que conviene leer como tres preguntas distintas. El **flujo operativo** responde: ¿el corazón del negocio genera o consume caja? El **flujo de inversión** responde: ¿cuánto estoy poniendo en activos de largo plazo? Y el **flujo de financiamiento** responde: ¿estoy tomando o devolviendo deuda y capital? Leerlos juntos te dice si la empresa se sostiene con su propia operación o si vive de inyecciones de financiamiento, que es precisamente el caso de Andina.",
      "El flujo operativo de Andina arranca con el **resultado neto de 175**, le suma de vuelta las **amortizaciones de 290** (porque no fueron una salida de caja, son un gasto contable) y los **intereses de 560**, y después aplica los ajustes del capital de trabajo: resta **330 por el aumento de cuentas por cobrar** y **550 por el aumento de inventarios** —plata que se quedó atrapada en clientes que no pagaron y stock que no se vendió— y suma **160 por el aumento de proveedores**. El resultado es un **flujo operativo de apenas 305** antes de intereses e impuestos. Una empresa que muestra 1.120 de EBITDA pero genera solo 305 de caja operativa está sufriendo una hemorragia de capital de trabajo.",
      "Los otros dos bloques completan el cuadro. En inversión, Andina gastó **440 en CAPEX (maquinaria)** y recuperó **30 por venta de rodados**. En financiamiento, tomó **230 de descubierto** nuevo, amortizó **150 de préstamos**, pagó **560 de intereses** y repartió **120 de dividendos**. El mensaje es brutal: Andina paga intereses (560) que casi igualan toda su caja operativa (305), y aún así reparte dividendos y toma más descubierto para cubrir el bache. El Flujo de Efectivo no opina; solo muestra. Pero lo que muestra es una empresa que se está financiando para sostener una ilusión de salud.",
    ],
  },
  {
    heading: "Cómo se conectan los tres estados: el sistema, no las islas",
    paragraphs: [
      "El error más común del lector principiante es tratar a los tres estados como documentos independientes. No lo son: forman un **sistema articulado** donde cada uno alimenta a los otros. La verdadera lectura financiera no nace de leerlos por separado, sino de **saltar entre ellos** siguiendo el rastro de un mismo número. Quien domina esos saltos puede detectar en segundos lo que a otro le toma una auditoría.",
      "El primer puente es el más importante: el **resultado neto del Estado de Resultados se acumula en el Patrimonio Neto del Balance**, en la cuenta de resultados acumulados. Los 175 que ganó Andina en 2024 (menos los 120 de dividendos) engrosan el patrimonio del próximo balance. Por eso el Estado de Resultados explica **cómo cambió el patrimonio** entre la foto de un año y la del siguiente. El balance te dice cuánto vale el patrimonio; el estado de resultados te dice por qué cambió respecto del año anterior. Sin esta conexión, el Patrimonio Neto sería un número que aparece de la nada.",
      "El segundo puente conecta el resultado con la caja, y es donde Andina se delata. Las **amortizaciones de 290** restan en el Estado de Resultados pero no salen de la caja, por eso el Flujo de Efectivo las vuelve a sumar. A la inversa, el **aumento de cuentas por cobrar (330) e inventarios (550)** no aparece como gasto en el Estado de Resultados —la venta se contabilizó como ingreso aunque no se haya cobrado— pero drena caja real, por eso el Flujo de Efectivo los resta. Estos ajustes son el mecanismo exacto por el cual una empresa rentable se queda sin efectivo: la ganancia está, pero está atrapada en activos que todavía no se hicieron líquidos.",
      "El tercer puente cierra el círculo: el saldo final de caja que calcula el Flujo de Efectivo es, exactamente, la línea de **caja y bancos del Balance** del cierre. Los tres estados encajan como un mecanismo de relojería. El Balance da el punto de partida y de llegada; el Estado de Resultados explica la generación económica; el Flujo de Efectivo explica el movimiento del dinero. Leer financieramente es recorrer ese circuito de ida y vuelta, verificando que cada número cierre con su contraparte en otro estado.",
    ],
  },
  {
    heading: "Foto versus película, y resultado versus caja: las dos grandes distinciones",
    paragraphs: [
      "Toda la semana se condensa en dos pares de conceptos que conviene grabar a fuego. El primero es **foto versus película**. El Balance es una foto: un instante. El Estado de Resultados y el Flujo de Efectivo son películas: períodos. Confundirlos lleva a errores absurdos, como comparar una partida del balance (un stock, un saldo) con una del estado de resultados (un flujo, una corriente) sin ajustar la temporalidad. Cuando más adelante calculemos rotaciones y ROIC, vamos a estar precisamente cruzando una foto con una película, y hay que saber qué se cruza con qué.",
      "El segundo par es **resultado versus caja**, o lo económico versus lo financiero. El resultado mide si el negocio, en términos devengados, ganó o perdió. La caja mide si entró o salió dinero. Andina es el ejemplo de manual de por qué no son lo mismo: muestra **175 de resultado** pero su flujo operativo, después de la sangría del capital de trabajo, es de apenas **305**, y tras pagar 560 de intereses queda en terreno claramente negativo, tapado solo con más descubierto. El resultado dice una cosa; la caja dice otra; ambas son ciertas, miden cosas distintas.",
      "¿Por qué importa tanto esta distinción para un dueño? Porque las empresas no quiebran por dar pérdida contable: quiebran por **quedarse sin caja**. Podés aguantar años de pérdidas si tenés liquidez, pero no aguantás un mes sin poder pagar sueldos o proveedores. El dueño que solo mira el resultado va a sentir que todo está bien hasta el día en que el banco le corta el descubierto. El que mira la caja ve venir el problema con meses de anticipación. Por eso, para una PyME con caja tensa, el Flujo de Efectivo no es el tercer estado en importancia: muchas veces es el primero.",
      "La interrelación entre estas dos distinciones es lo que da profundidad a la lectura. Una empresa puede estar en cualquiera de cuatro cuadrantes: gana y tiene caja (ideal), pierde y no tiene caja (terminal), gana pero no tiene caja (Andina: la trampa del crecimiento mal financiado), o pierde pero tiene caja (típico de quien está liquidando activos). Saber en qué cuadrante estás —y eso solo se sabe cruzando resultado con caja— es el primer diagnóstico estratégico que habilita esta semana.",
    ],
  },
  {
    heading: "Errores frecuentes del CEO al leer estados contables",
    paragraphs: [
      "**Mirar solo la última línea.** El error rey. El resultado neto es el final de una historia larga, y mirarlo aislado es como leer solo la última página de una novela. Andina muestra 175 de resultado neto y eso parece bueno, hasta que subís a ver que el negocio generó 830 de EBIT y que 560 se los comieron los intereses. La última línea esconde más de lo que revela; la riqueza está en la cascada completa.",
      "**Confundir ganancia con caja.** El segundo error más caro. Muchísimos dueños asumen que si la empresa ganó, tiene plata. Andina ganó 175 y vive en descubierto. La ganancia puede estar atrapada en cuentas por cobrar (1.850, de las cuales una parte ni se va a cobrar) y en inventarios (2.400, con stock que no rota). Quien confunde resultado con caja toma dividendos o compromisos que la empresa no puede sostener.",
      "**Tratar todo el pasivo como igual.** El balance suma el descubierto al 85% con los proveedores gratuitos en una misma columna de pasivo corriente. El CEO desprevenido ve un número total de deuda y no distingue que una parte lo está fundiendo y otra parte es un regalo. No leer la **calidad** del pasivo, solo su cantidad, lleva a no atacar la deuda cara mientras se desperdicia el financiamiento barato de proveedores.",
      "**Leer los estados por separado.** Quien mira el Estado de Resultados sin abrir el Flujo de Efectivo nunca ve la hemorragia de capital de trabajo. Quien mira el Balance sin conectarlo con el resultado no entiende por qué cambió su patrimonio. La información que importa casi siempre vive en el **cruce** entre dos estados, no dentro de uno solo. Leer de a uno es quedarse con la mitad de la verdad, siempre.",
    ],
  },
  {
    heading: "Qué decisiones habilita saber leer los tres estados",
    paragraphs: [
      "Saber leer los estados contables no es un fin en sí mismo: es la **llave que abre todas las decisiones** que vienen después. La primera y más inmediata es saber **qué preguntarle a tu contador**. En lugar de recibir un PDF y archivarlo, ahora podés preguntar: ¿cuánto de las cuentas por cobrar tiene mora dura? ¿qué porción del inventario no rotó este año? ¿por qué la caja operativa es tan inferior al EBITDA? Esas preguntas, que antes ni se te ocurrían, son las que destraban el verdadero diagnóstico.",
      "La segunda decisión es **dónde mirar para encontrar el problema**. Antes de esta semana, un dueño preocupado por la caja tendería a apretar gastos o pedir más crédito a ciegas. Ahora sabe que la respuesta está en el cruce entre el Estado de Resultados y el Flujo de Efectivo, y específicamente en los ajustes de capital de trabajo: las cuentas por cobrar que crecen 330 y el inventario que crece 550. El diagnóstico dejó de ser intuición y pasó a ser lectura.",
      "La tercera decisión es **distinguir el problema de negocio del problema de financiamiento**. Andina no tiene un mal negocio: tiene un buen negocio (EBIT 830) mal financiado (intereses 560). Esa distinción cambia por completo el plan de acción. Si el problema fuera el negocio, habría que tocar precios, costos o productos. Como el problema es el financiamiento y el capital de trabajo, hay que atacar la cobranza, el stock y la estructura de deuda. Confundir ambos diagnósticos lleva a curar la enfermedad equivocada.",
      "Finalmente, esta semana habilita todo el resto del programa. La Semana 2 te va a enseñar a ver lo que el balance esconde —activos ocultos y sobrevaluados—; la Semana 3 te va a llevar de la utilidad al valor con NOPAT, capital invertido y ROIC. Pero ninguna de esas capas tiene sentido si no sabés leer la base. Esta semana construiste el alfabeto. Lo que sigue es aprender a leer la novela completa de tu empresa, y a reescribir su final.",
    ],
  },
];
