// Material AMPLIADO para el Word de la Semana 6
// Andina Manufacturas S.A. — Free Cash Flow: FCFF, FCFE, FCFD y CFROI
// Español rioplatense, registro premium para CEO.

export const deepDive06: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'La caja libre es lo único que de verdad sobra',
    paragraphs: [
      `Llegamos al paso decisivo del programa: aprender a medir la **caja libre**, es decir, cuánta plata genera el negocio **después de mantenerse en pie**. No la ganancia contable, que ya sabemos que miente sin querer; no el EBITDA, que es una promesa optimista; sino la plata que de verdad queda disponible para repartir entre quienes financiaron la empresa. La caja libre es el último filtro de la realidad: lo que sobra cuando ya pagaste todo lo que el negocio necesita para seguir existiendo.`,
      `El **Free Cash Flow** es esa caja. Es el flujo que queda una vez que el negocio cubrió sus costos operativos, pagó los impuestos sobre la operación, reinvirtió en activos fijos para no quedarse atrás (el CAPEX) y financió el crecimiento de su capital de trabajo (más cuentas por cobrar, más inventario). Lo que sobra después de todo eso es lo único que se puede usar para pagarle intereses al banco, devolverle capital, o repartir dividendos a los dueños. Es la materia prima de cualquier valuación seria.`,
      `Acá conviene un cambio de mentalidad profundo: pasar de pensar en **utilidad** a pensar en **caja libre**. La utilidad es una opinión contable sujeta a criterios de devengamiento, amortización y valuación. La caja libre es un hecho: o la plata está disponible o no está. Dos empresas con idéntica utilidad pueden generar caja libre radicalmente distinta, según cuánto CAPEX necesiten y cuánto capital de trabajo inmovilicen. El valor vive en la caja libre, no en la utilidad.`,
      `Y la consecuencia es contundente: si una empresa no genera caja libre de forma sostenida, no importa cuánta "ganancia" muestre, **no está creando valor: está consumiendo el de alguien más** —el del banco que la financia, el del proveedor que le da plazo, el del dueño que reinyecta capital—. La caja libre es el juez final. Esta semana aprendemos a calcularla bien, a entender entre quiénes se reparte, y a descubrir dónde se drena antes de llegar al bolsillo.`,
    ],
  },
  {
    heading: 'Las tres caras del flujo: FCFF, FCFE y FCFD',
    paragraphs: [
      `El flujo de caja libre tiene tres caras, y confundirlas lleva a errores de valuación y de decisión. La primera y madre de todas es el **FCFF (Free Cash Flow to the Firm)**: la caja que genera el negocio para **todos** los que lo financian —accionistas y acreedores juntos—, antes de decidir cómo se reparte. Es la torta completa que produce la operación, mirada con independencia de cómo se financió la empresa. Por eso es la medida más limpia del desempeño del negocio en sí.`,
      `La segunda cara es el **FCFE (Free Cash Flow to Equity)**: la caja que queda para los **accionistas** después de atender a los acreedores, es decir, después de pagar intereses y de amortizar deuda (neto de la deuda nueva que se haya tomado). Es lo que efectivamente podría llegar al bolsillo del dueño en forma de dividendos. El FCFE depende de la estructura de financiamiento: si la empresa tiene mucha deuda cara, el FCFE puede ser una porción mísera del FCFF.`,
      `La tercera cara es el **FCFD (Free Cash Flow to Debt)**: la caja que va a los **acreedores**, esto es, los intereses pagados más la amortización de capital de la deuda, restando la nueva deuda tomada en el período. Si la empresa tomó más deuda de la que pagó, el FCFD puede ser negativo: los acreedores netos pusieron plata. El FCFD es la porción de la torta que se lleva el banco.`,
      `Y todo cierra con una identidad de reparto elegante: **FCFF = FCFE + FCFD**. El flujo que produce la firma se reparte enteramente entre dueños y acreedores. La imagen mental para un CEO es exacta: el FCFF es la torta que hornea el negocio; el FCFD y el FCFE son cómo se corta esa torta entre el banco y vos. Si la deuda es cara, el banco se lleva una porción enorme y al dueño le queda apenas una rebanada fina, aunque el negocio sea bueno. La calidad del negocio se mide en el FCFF; cuánto te toca a vos se decide en el reparto.`,
    ],
  },
  {
    heading: 'Cómo se arma el FCFF, paso a paso',
    paragraphs: [
      `El FCFF se construye desde el **NOPAT** (Net Operating Profit After Taxes), que es el EBIT después de impuestos pero **antes** de intereses. Acá hay una decisión conceptual clave que conviene entender, no memorizar: ¿por qué arrancar antes de los intereses? Porque el FCFF mide la caja del **negocio**, no la del dueño. Los intereses son una decisión de **financiamiento**, no de operación. Si los restáramos, estaríamos contaminando la medida del negocio con cómo se financió. El FCFF debe ser ciego a la estructura de capital.`,
      `La receta tiene cuatro pasos. Primero, partís del **NOPAT = EBIT × (1 − tasa de impuesto)**: la ganancia operativa "limpia" de financiamiento. Segundo, **sumás las amortizaciones**, porque restaron en el resultado pero no salieron de la caja: son un cargo contable que reconoce el desgaste de los activos, no un egreso real de plata. La caja no se enteró de esa resta, así que se la devolvemos.`,
      `Tercero, **restás el CAPEX**: la inversión en activos fijos necesaria para sostener y hacer crecer el negocio. Esto sí es plata que sale de verdad, este año, para comprar la máquina o renovar el equipo. Si el EBITDA ignora el CAPEX, el FCFF lo enfrenta de cara, y por eso es mucho más honesto. Cuarto, **restás el aumento del capital de trabajo (ΔCapital de trabajo)**: más cuentas por cobrar y más inventario inmovilizan caja; más proveedores la liberan. El crecimiento que no se autofinancia se paga acá, en caja contante.`,
      `Lo que queda después de los cuatro pasos es el FCFF: **FCFF = NOPAT + Amortizaciones − CAPEX − ΔCapital de trabajo**. Es la caja real que produjo la operación, disponible para repartir entre banco y dueños. Fijate la belleza del esqueleto: empieza en una medida económica (el NOPAT) y la corrige por todos los desfasajes entre lo económico y lo financiero que vimos la semana pasada —la amortización que no es caja, el CAPEX que es caja pero no resultado, el capital de trabajo que atrapa caja sin tocar el resultado—. El FCFF es, literalmente, el puente entre el resultado y la caja.`,
    ],
  },
  {
    heading: 'Por qué el FCFF es la medida clave (y el EBITDA, la trampa)',
    paragraphs: [
      `De las tres caras del flujo, el **FCFF es la medida clave**, y vale la pena entender por qué con precisión. Primero, porque mide la salud del **negocio en sí**, sin la distorsión de cómo se financió. Dos empresas idénticas en operación pero distintas en deuda tienen el mismo FCFF: eso lo hace comparable y justo. Es la medida que un comprador, un banco o un inversor usan para juzgar la calidad intrínseca de la operación, antes de discutir quién se queda con qué.`,
      `Segundo, porque el FCFF es la base de la **valuación**. El valor de una empresa (Enterprise Value) es el valor presente de sus FCFF futuros descontados al WACC. Toda la maquinaria de valuación que viene en las próximas semanas se monta sobre el FCFF. Por eso no es un cálculo más: es el cimiento. Quien no entiende el FCFF no puede entender de dónde sale el precio de su propia empresa.`,
      `Tercero, y acá está la lección más práctica, porque **expone la trampa del EBITDA**. El EBITDA es la promesa; el FCFF es la realidad. El EBITDA ignora dos cosas enormes: el CAPEX que tenés que invertir para no quedarte atrás y el capital de trabajo que el crecimiento te exige. Dos empresas con el mismo EBITDA pueden tener FCFF radicalmente distintos: la que rota bien su capital de trabajo y necesita poco CAPEX vale mucho más que la que inmoviliza caja en stock y cuentas por cobrar. El EBITDA seduce; el FCFF no se deja seducir.`,
      `Cuarto, porque el FCFF **separa el negocio del financiamiento**, y esa separación es la que permite tomar buenas decisiones. Si tu FCFF es sano pero tu FCFE es magro, el problema no es el negocio: es la deuda. Y eso se arregla reestructurando el pasivo, no tocando la operación. Si el FCFF mismo es flojo, el problema es operativo y hay que ir al margen, al CAPEX o al capital de trabajo. El FCFF te dice **dónde** está el problema antes de que gastes energía resolviendo el equivocado.`,
    ],
  },
  {
    heading: 'Mini-caso numérico: Andina, FCFF de 305 con resultado neto de 175',
    paragraphs: [
      `Acá se ve, con los números de **Andina 2024**, por qué la caja libre cuenta otra historia que la utilidad. Andina cerró el año con un **resultado neto de 175**, pero su flujo operativo antes de intereses e impuestos —que se aproxima al FCFF del negocio— fue de **305**. La primera sorpresa: ¿cómo puede la caja del negocio superar a la ganancia? Por las **amortizaciones**: el flujo le vuelve a sumar los **290** que el resultado había restado sin que saliera un solo peso de la caja. Esos 290 son desgaste contable, no egreso real, y la caja los recupera.`,
      `Pero ahí, escondida detrás de ese número que parece bueno, está la trampa, y es brutal. Mirá qué le pasó al flujo por el capital de trabajo. El **aumento de cuentas por cobrar drenó −330**: Andina vendió más (las ventas subieron de 7.400 a 8.200), pero no cobró. Esa venta extra es ganancia en el papel y agujero en la caja. Vendiste, lo anotaste como ingreso, pero la plata se quedó en la calle, en manos de clientes que pagan tarde o no pagan.`,
      `El segundo golpe: el **aumento de inventarios drenó −550**. Medio millón de dólares quedó inmovilizado en mercadería dormida en el depósito. Es caja que salió para comprar o fabricar stock que todavía no se vendió. Entre las cuentas por cobrar y el inventario, el capital de trabajo se llevó **880 de caja** en un solo año. A favor jugó solo el aumento de proveedores (+160), financiamiento no oneroso que ayudó un poco. El neto del capital de trabajo fue un drenaje de −720.`,
      `Hagamos la cuenta completa para que quede grabada. Partimos del NOPAT: EBIT 830 × (1 − 0,35) = **540**. Sumamos amortizaciones: +290. Restamos CAPEX: −440 (la máquina del año). Restamos el ΔCapital de trabajo: −720 (los −330 de cobranzas, −550 de inventario, +160 de proveedores). El FCFF da 540 + 290 − 440 − 720 = **−330**. ¡Negativo! El flujo operativo "lindo" de 305 que mostraba el cuadro se vuelve **caja libre negativa** una vez que enfrentás el CAPEX y el capital de trabajo completos. Si Andina hubiera ordenado su capital de trabajo, su FCFF habría sido fuertemente positivo. El negocio genera caja; la mala gestión del capital de trabajo se la come antes de que llegue al bolsillo. Esa es la diferencia entre los 175 de ganancia que celebra el dueño y la caja libre real que se le escurre entre los dedos.`,
    ],
  },
  {
    heading: 'CFROI: el retorno de caja sobre la inversión',
    paragraphs: [
      `El **CFROI (Cash Flow Return on Investment)** lleva la lógica de la caja libre un paso más allá. En vez de preguntar "¿cuánta caja generé?" (un monto), pregunta **"¿qué tasa de retorno de caja obtuve sobre todo lo que invertí en el negocio?"** (una tasa). Es el mismo salto que dimos en la Semana 4 al pasar del EVA en pesos al spread en porcentaje: convertir un monto en una tasa lo hace comparable contra el costo del capital.`,
      `Conceptualmente, el CFROI compara el flujo de caja operativo que produce la empresa contra la base de activos brutos que se invirtieron para producirlo. Es, en espíritu, **la TIR del negocio mirado en términos de caja**: una tasa interna de retorno que sintetiza cuán eficientemente la inversión total se transforma en flujo. Una vez que tenés esa tasa, la comparás contra el costo del capital —el WACC, que profundizamos en la próxima semana— y obtenés el veredicto: por encima del WACC, creás valor; por debajo, lo destruís.`,
      `¿Qué **determina** el CFROI? Dos cosas, y ninguna se puede ignorar. Primero, cuánta caja genera la operación por cada peso invertido: la **eficiencia operativa** (margen, conversión de ventas en caja). Segundo, cuánto capital quedó inmovilizado para generar esa caja: la **eficiencia de la inversión** (qué tan poco capital de trabajo y activo fijo necesitás). Una empresa puede tener buen margen y aun así un CFROI mediocre si inmoviliza demasiado capital. Andina es el caso de manual: genera caja operativa, pero necesitó atrapar 880 en capital de trabajo y 440 en CAPEX para hacerlo, y eso le hunde el retorno.`,
      `Y qué **implica** el CFROI: implica que un negocio crea valor **solo si su retorno de caja supera el costo de financiar esa inversión**. No alcanza con generar caja; hay que generarla a una tasa mayor que el WACC. Es la misma lógica del spread de la Semana 4, ahora expresada en términos de flujo de caja en vez de utilidad operativa. El CFROI es el puente entre el mundo del FCFF de esta semana y el mundo de la creación de valor que recorre todo el programa.`,
    ],
  },
  {
    heading: 'Interrelaciones: cómo el FCFF conecta con todo el programa',
    paragraphs: [
      `El FCFF es uno de los grandes nudos del programa, y entender sus conexiones convierte una fórmula en una forma de ver la empresa. Hacia atrás, conecta con la Semana 4 (EVA): el FCFF y el EVA son **dos formas de mirar lo mismo desde ángulos distintos**. El EVA pregunta si el NOPAT superó el costo del capital invertido; el FCFF pregunta cuánta caja sobró después de reinvertir. Ambos parten del NOPAT, ambos castigan el capital inmovilizado. Una empresa con EVA negativo, como Andina, tiende a tener FCFF débil o negativo, porque el mismo capital de trabajo inflado que le baja el ROIC le drena la caja. Son el mismo problema visto en dos monedas.`,
      `Hacia atrás también, conecta con la Semana 5 (económico vs financiero) de manera directísima. El FCFF es la **materialización numérica** de la idea de que lo económico no es lo financiero. El resultado neto de 175 (económico) se transforma en caja libre negativa (financiero) precisamente por los desfasajes que estudiamos la semana pasada: la amortización que no es caja, el CAPEX que es caja pero no resultado, y el capital de trabajo que atrapa plata. El círculo vicioso de la Semana 5 —poca caja, descubierto, intereses— nace justamente acá: cuando el FCFF no alcanza, hay que tapar el hueco con deuda al 85%.`,
      `La conexión con el capital de trabajo es la columna del caso entero. El ΔCxC de −330 y el Δinventario de −550 que drenan el FCFF son **los mismos** activos sobredimensionados que inflan el capital invertido del ROIC (Semana 4) y que comprometen la liquidez (Semana 5). Un único problema operativo —cobrar tarde y stockear de más— se manifiesta simultáneamente como ROIC bajo, como FCFF negativo y como liquidez ahogada. Por eso ordenar el capital de trabajo es la palanca que más cosas mejora a la vez: sube el ROIC, libera caja libre y descomprime la liquidez de un solo golpe.`,
      `Hacia adelante, el FCFF es el **insumo directo de la valuación** (Semanas 9 y 10). El Enterprise Value de Andina es el valor presente de sus FCFF futuros descontados al WACC. Si el FCFF de hoy es negativo por el capital de trabajo desbordado, la valuación lo castiga doble: descuenta flujos pobres y le suma el riesgo de ahogo. El CFROI, por su parte, prepara el terreno para la Semana 7 (WACC), porque la tasa de retorno de caja solo cobra sentido cuando se la enfrenta al costo del capital. Esta semana produce la caja; las próximas le ponen precio.`,
    ],
  },
  {
    heading: 'Técnicas modernas: del FCFF estático a la gestión de caja libre',
    paragraphs: [
      `El cálculo del FCFF a fin de año es solo el comienzo; las empresas que mejor crean valor lo usan de forma dinámica. La primera técnica moderna es descomponer el FCFF en sus **drivers de caja** y proyectarlos por separado: margen operativo, intensidad de CAPEX (CAPEX sobre ventas) y días de capital de trabajo (días de cobranza, días de stock, días de pago). Modelar cada palanca permite ver, antes de actuar, cuánta caja libera reducir la cobranza en diez días o el inventario en una semana. En Andina, ese ejercicio mostraría que bajar los días de stock es la palanca de mayor impacto inmediato.`,
      `La segunda técnica es el **FCFF marginal**: en vez de mirar el flujo total, evaluar cuánta caja libre agrega o consume cada decisión nueva —cada cliente, cada línea, cada proyecto de CAPEX—. Un proyecto puede ser rentable en utilidad y aun así destruir caja si exige demasiado capital de trabajo para arrancar. Pensar al margen, en términos de caja, evita la trampa de crecer hacia un agujero negro de FCFF con cara de éxito comercial.`,
      `La tercera técnica conecta el FCFF con la valuación mediante el **descuento de flujos (DCF)** y el análisis de sensibilidad. Las herramientas de IA hoy permiten correr cientos de escenarios moviendo márgenes, CAPEX y días de capital de trabajo para ver qué combinación maximiza el valor presente de los FCFF futuros. Esto transforma la gestión de caja de un ejercicio reactivo —apagar incendios de tesorería— en uno estratégico: gestionar deliberadamente para maximizar la caja libre descontada, que es, en el fondo, maximizar el valor de la compañía.`,
    ],
  },
  {
    heading: 'Errores frecuentes del CEO',
    paragraphs: [
      `**Error 1: confundir EBITDA con caja.** "Mi EBITDA es 1.120, genero un montón de caja." El EBITDA ignora el CAPEX y el capital de trabajo, los dos grandes consumidores de plata. En Andina, ese EBITDA convive con un FCFF que se vuelve negativo una vez que enfrentás los 440 de CAPEX y los 880 de capital de trabajo. El EBITDA es la promesa; la caja libre es lo que de verdad queda. Gestionar mirando EBITDA es gestionar mirando una ilusión.`,
      `**Error 2: festejar la ganancia ignorando dónde está la caja.** El resultado neto de 175 suena bien hasta que preguntás dónde está esa plata. Está atrapada: 330 en clientes que no pagaron, 550 en inventario dormido. La ganancia contable puede ser perfectamente real y estar perfectamente inaccesible. El CEO que no rastrea en qué se convirtió su utilidad —si en caja o en activos inmovilizados— maneja sin saber si tiene combustible.`,
      `**Error 3: crecer sin medir el costo de caja del crecimiento.** Crecer en ventas embriaga, pero cada peso de venta nueva a crédito exige más cuentas por cobrar, y cada peso de venta exige más inventario para sostenerla. Si el capital de trabajo crece más rápido que el flujo operativo, el crecimiento drena caja en vez de generarla. Andina creció de 7.400 a 8.200 y ese crecimiento le costó 880 de caja. Crecer mal es destruir caja con cara de éxito.`,
      `**Error 4: restar los intereses al calcular el FCFF.** Un error técnico pero costoso: mezclar la caja del negocio con la del financiamiento. El FCFF se construye desde el NOPAT, antes de intereses, porque mide la operación, no la estructura de deuda. Restar los intereses ahí confunde un problema de financiamiento con uno operativo, y lleva a "arreglar" la operación cuando lo que hay que arreglar es la deuda. Los intereses entran después, al pasar del FCFF al FCFE.`,
    ],
  },
  {
    heading: 'Qué decisiones habilita',
    paragraphs: [
      `Pensar en términos de FCFF habilita, antes que nada, **gestionar el capital de trabajo como una fuente de caja**. Una vez que ves que el ΔCxC de −330 y el Δinventario de −550 son los que hunden tu flujo, las decisiones de crédito, stock y plazos dejan de ser administrativas y se vuelven la palanca de caja más poderosa que tenés. Apretar la cobranza, depurar el inventario obsoleto (esos 420 de mercadería dormida) y estirar plazos con proveedores liberan caja contante, mucho más rápido y barato que cualquier financiamiento externo.`,
      `Habilita **disciplinar el CAPEX**. Cada inversión en activo fijo se mide ahora por su impacto en el FCFF y en el CFROI: ¿esta máquina genera caja libre incremental que justifique los 440 que sale? El CAPEX deja de aprobarse por "necesitamos modernizarnos" y pasa por el filtro de la caja que devuelve. Esto evita la sobreinversión, uno de los grandes drenajes silenciosos de caja libre en las PyMEs industriales.`,
      `Habilita **separar el problema operativo del financiero con precisión quirúrgica**. Si el FCFF es sano pero el FCFE es pobre, el problema es la deuda y se ataca reestructurando el pasivo —el descubierto al 85%—, no tocando la operación. Si el FCFF mismo es débil, el problema es operativo y hay que ir al margen, al CAPEX o al capital de trabajo. El FCFF y su reparto le dicen al CEO exactamente qué palanca mover, en vez de gastar energía resolviendo el problema equivocado.`,
      `Finalmente, habilita **hablar el idioma de la valuación y del comprador**. Quien quiera comprar Andina, prestarle o asociarse, no va a mirar el resultado neto de 175: va a mirar el FCFF y el CFROI, porque ahí está el valor real. El CEO que gestiona para maximizar la caja libre sostenible no solo evita el ahogo financiero: **construye el precio** al que algún día podrá vender o financiar su empresa. La decisión más profunda que habilita la Semana 6 es dejar de dirigir una empresa para que muestre ganancia, y empezar a dirigirla para que genere caja libre, que es lo único que, al final del día, vale.`,
    ],
  },
]
