// Material ampliado (deep dive) para el Word de la Semana 8.
// Bienes de uso, CAPEX, valor contable vs valor de mercado.
// Caso central: Andina Manufacturas S.A. (cifras en miles de USD).

export const deepDive08: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'El balance te muestra el costo, no el valor',
    paragraphs: [
      `Cuando mirás los **Bienes de uso** en tu balance, no estás viendo lo que valen: estás viendo lo que **costaron**, menos las amortizaciones acumuladas. Es la **valuación histórica**, una regla contable nacida de tres principios —prudencia, objetividad y verificabilidad— que prioriza no inflar el patrimonio por encima de reflejar la realidad económica. El contador registra un dato duro (la factura de compra) y le va restando un desgaste teórico. El resultado es prolijo y auditable, pero responde a una pregunta distinta de la que se hace un dueño.`,
      `Para un CEO esto genera **dos problemas opuestos al mismo tiempo**. Por un lado, los **activos ocultos**: cosas que valen mucho más de lo que figura. Un terreno comprado hace veinte años sigue en libros a su costo histórico mientras el mercado lo cotiza al triple. Por el otro, los **activos sobrevaluados**: cosas que figuran caras pero ya no valen eso. Una máquina tecnológicamente obsoleta conserva un valor neto contable digno, pero si tuvieras que venderla mañana nadie te paga ese número.`,
      `El balance, además, está atado al **principio del costo histórico** y a la idea de **empresa en marcha**: asume que vas a usar los activos, no venderlos, y por eso no los ajusta a precio de liquidación ni de reposición. En contextos inflacionarios esto se agrava, porque un activo comprado hace años en moneda local quedó registrado a un valor que el tiempo y la inflación volvieron irrisorio. De ahí que el caso de Andina trabaje en USD: para neutralizar ese ruido y poder comparar costo contra valor con sentido.`,
      `El balance no miente: simplemente responde a otra pregunta. La contabilidad pregunta "¿cuánto costó y cuánto se desgastó?". El dueño necesita preguntar "**¿cuánto valen realmente mis activos hoy y cuánto me cuesta mantenerlos?**". Son dos lecturas legítimas del mismo activo, y un CEO financiero tiene que saber traducir de una a la otra, porque las decisiones de inversión, venta, garantía y valuación se toman con la segunda, no con la primera.`,
    ],
  },
  {
    heading: 'CAPEX y bienes de uso: parecidos pero no son lo mismo',
    paragraphs: [
      `El **CAPEX (Capital Expenditure)** es la inversión **real** en activo fijo que hacés en un período: plata que sale de la caja hoy para comprar capacidad futura. Vive en el **Flujo de Efectivo**, en la sección de inversión, y es un **flujo** (algo que pasa durante el año). Los **bienes de uso contables**, en cambio, son el **stock** acumulado de todos esos activos a lo largo del tiempo, valuados a costo histórico y reducidos por amortización. Viven en el **Balance** y son una foto a una fecha. Flujo versus stock: esa es la primera gran distinción.`,
      `La **amortización** es la bisagra entre ambos. Es el reconocimiento contable del desgaste del activo a lo largo de su vida útil; reparte el costo de una compra grande a lo largo de los años en que ese activo trabaja. Tiene una característica que confunde a casi todos los dueños: **no es una salida de caja**. La plata salió cuando compraste el bien (eso fue el CAPEX). La amortización es solo un asiento contable que "consume" valor en libros sin tocar la cuenta bancaria. Por eso en el flujo de fondos la amortización se **suma de nuevo** al resultado: nunca se fue de la caja.`,
      `La relación entre las piezas se resume en una identidad simple: **Bien de uso neto al cierre = Bien de uso neto al inicio + CAPEX − Amortización del período − Bajas**. El CAPEX alimenta el stock, la amortización y las ventas o retiros lo erosionan. La consecuencia, contraintuitiva pero importantísima, es que **el activo fijo neto puede caer aunque sigas invirtiendo todos los años**: basta con que la amortización del período supere al CAPEX. Una empresa que muestra bienes de uso netos en baja no necesariamente dejó de invertir; puede estar amortizando más rápido de lo que repone.`,
      `Hay aquí una diferencia conceptual clave entre **CAPEX e "inversión contable"**. El CAPEX es desembolso de caja por capacidad productiva real. Lo que el balance llama variación de activo fijo mezcla ese desembolso con efectos puramente contables (amortización, revalúos, bajas) que no son caja. Cuando un CEO quiere saber cuánto le costó de verdad sostener su capacidad, tiene que mirar el CAPEX del flujo de fondos, no la variación neta del rubro en el balance: esta última está "contaminada" por la amortización, que es ficción contable, no plata.`,
    ],
  },
  {
    heading: 'Categorías de bienes de uso: cada una envejece distinto',
    paragraphs: [
      `Mezclar todos los bienes de uso en un solo renglón te ciega, porque cada categoría se comporta de manera radicalmente distinta. El **terreno** no se amortiza —la tierra no se desgasta— y suele **revaluarse** con el tiempo y con la valorización de la zona. Es el candidato número uno a ser un activo oculto: comprado hace décadas, sigue en libros a costo histórico mientras su valor de mercado se multiplicó. El **edificio** se amortiza lentísimo, en décadas, y su valor de mercado supera al contable cuando la ubicación se valorizó.`,
      `La **maquinaria** es donde se concentra el riesgo. Se amortiza, pero además sufre **obsolescencia tecnológica**: una máquina puede tener un valor neto contable respetable y, al mismo tiempo, valer mucho menos en el mercado porque apareció una generación más eficiente. Acá el problema es inverso al del terreno: el libro **sobrevalúa** el activo. Los **rodados** se deprecian rápido y de forma predecible —un camión pierde valor desde que sale de la concesionaria—, y casi siempre valen menos que su costo, aunque el neto contable puede quedar desfasado en una dirección o en otra.`,
      `Los **intangibles** —marca, cartera de clientes, know-how, patentes, software propio— son el caso más extremo. Cuando son **generados internamente**, la contabilidad casi nunca los reconoce: figuran en **cero** en el balance, porque no hubo una transacción de compra que los registre. Sin embargo, suelen valer muchísimo: la marca de una PyME con veinte años de trayectoria y una cartera de clientes fieles puede ser el activo más valioso de la empresa, y no aparece en ninguna línea. Solo se contabilizan cuando se compran a un tercero (un valor llave en una adquisición).`,
      `La **administración eficiente de los bienes de uso** arranca por mirarlos de a uno y hacerse, para cada activo, la pregunta del dueño: **¿este activo trabaja para mí o solo ocupa lugar en el balance?** Un terreno baldío que se revaloriza trabaja distinto de una máquina parada que se oxida. Categorizar no es un capricho contable: es la base para decidir qué vender, qué revaluar, qué reemplazar y qué proteger.`,
    ],
  },
  {
    heading: 'Andina: la brecha entre el libro y el mercado',
    paragraphs: [
      `Abramos los bienes de uso de **Andina Manufacturas** y comparemos columna contra columna. El **terreno** figura a **350** en libros pero a precio de mercado vale **900**: hay **550 de valor oculto** en un solo renglón, porque se compró hace décadas y nunca se revaluó. El **edificio** figura a **620** y vale del orden de **780**: otros **160 de valor oculto** por la valorización de la zona. Solo entre estos dos activos inmobiliarios, Andina tiene **710 de patrimonio que su balance no muestra**.`,
      `Del otro lado de la brecha está la **maquinaria**, que figura a **1.450** pero cuyo valor de mercado realista, descontando la parte tecnológicamente obsoleta, es **1.150**: hay **300 de "valor de mentira"** inflando el activo. Los **rodados** figuran a 140 y valen unos 110: otros 30 de sobrevaluación menor. Y los **intangibles** —la marca y la cartera de clientes— valen del orden de **650** y **figuran en cero**, porque fueron generados internamente y la contabilidad no los reconoce.`,
      `En el período, Andina invirtió **440 de CAPEX** en maquinaria nueva (sale del Flujo de Efectivo, sección inversión), mientras que la **amortización del año fue de 290**. Es decir: invirtió 150 más de lo que amortizó, por lo que su stock de activo fijo bruto creció, pero ese dato del flujo no dice nada sobre si lo que compró vale lo que pagó ni sobre la brecha acumulada en el resto de los activos. CAPEX y valuación de mercado son dos análisis distintos que hay que hacer en paralelo.`,
      `Sumemos las correcciones: **terreno +550, edificio +160, maquinaria −300, rodados −30, intangibles +650**. El neto es **+1.030 de patrimonio económico** que el balance no refleja. El dueño de Andina cree que su patrimonio es el contable; en realidad tiene un terreno que vale el doble, una máquina que vale menos de lo que cree y una marca que no figura. Tres correcciones que, juntas, cambian la valuación de su empresa más que un año entero de ganancia (que fue de apenas 175).`,
    ],
  },
  {
    heading: 'El verdadero costo de crecer: capital de trabajo + CAPEX',
    paragraphs: [
      `Cuando una empresa crece, la caja se va por **dos caños** que el Estado de Resultados no muestra, y hay que leerlos juntos para entender la tensión de liquidez. El primero es la **variación del capital de trabajo** (lo que vimos en la Semana 7): más ventas piden más cuentas por cobrar y más inventario. En Andina, las cuentas por cobrar subieron **330** y los inventarios **550** en el año, contra solo **160** que aportaron los proveedores: un drenaje neto cercano a **720** solo por capital de trabajo operativo.`,
      `El segundo caño es el **CAPEX**: para sostener o ampliar capacidad hay que invertir, y eso es plata que sale de la caja hoy. Andina puso **440** en maquinaria. Sumando ambos caños, entre capital de trabajo y CAPEX se fueron del orden de **1.160 de caja**, contra una utilidad de apenas 175 y un flujo operativo (antes de intereses e impuestos) de 305. La cuenta no cierra: por eso la empresa, rentable en el papel, vive del descubierto.`,
      `Esto explica una de las paradojas centrales de las finanzas corporativas: **una empresa rentable puede estar siempre tensa de caja**. El resultado neto fue positivo, pero entre el capital de trabajo que se infla y el CAPEX que hay que desembolsar, se fue muchísima más plata de la que entró por utilidad. Leer juntas estas dos variaciones es lo que separa al que mira el margen del que entiende el flujo. El crecimiento no es gratis: tiene un costo de caja que hay que financiar a tiempo.`,
      `La técnica moderna para gestionar esto es distinguir **CAPEX de mantenimiento** (lo mínimo para sostener la capacidad actual, que suele aproximarse a la amortización) del **CAPEX de expansión** (lo que agrega capacidad nueva). En Andina, si la amortización de 290 representa el desgaste real, entonces de los 440 invertidos, unos 290 fueron mantenimiento y unos 150 expansión. Esta apertura permite calcular el **flujo de caja libre** con realismo y decidir cuánto del crecimiento se autofinancia y cuánto exige deuda o aporte de capital.`,
    ],
  },
  {
    heading: 'Interrelaciones: cómo los bienes de uso se conectan con todo',
    paragraphs: [
      `Los bienes de uso y el CAPEX son el puente entre el **balance, el flujo de fondos y el Estado de Resultados**. Una sola compra de maquinaria toca los tres estados: sale de la caja como **CAPEX** (flujo de inversión), se asienta como **activo fijo** (balance) y, año a año, se reconoce como **amortización** (Estado de Resultados), que a su vez vuelve a sumarse en el flujo operativo por no ser caja. Entender esta triangulación es entender cómo respira la información financiera de una empresa.`,
      `Se conectan de manera directa con el **capital de trabajo** de la Semana 7: ambos son los dos caños por los que crecer consume caja, y un activo fijo grande que no produce es el mismo problema que el inventario obsoleto, capital inmovilizado que no rota, solo que más difícil de vender. También dialogan con el **ROIC**, porque los bienes de uso son una parte central del **capital invertido**: una máquina sobrevaluada o subutilizada infla el denominador del ROIC y disfraza la verdadera eficiencia con la que la empresa usa su capital.`,
      `La relación con la **valuación y el costo del capital (Semana 9)** es íntima. El valor económico de la empresa no es el patrimonio contable, sino el patrimonio ajustado a mercado: el terreno revaluado (+550), el edificio (+160), la máquina obsoleta (−300) y la marca invisible (+650) reescriben por completo el patrimonio neto. Y cada peso invertido en activo fijo debe rendir por encima del **WACC** (21-22% en Andina); una máquina que no genera retorno suficiente destruye valor aunque figure prolija en el balance.`,
      `Finalmente, se enlazan con las decisiones de **financiamiento y garantías**. Un terreno con 550 de valor oculto es una garantía real mucho más sólida de lo que el banco vería en el balance contable: bien presentado, puede mejorar el acceso al crédito y bajar la tasa. Conocer el valor de mercado de los activos no es un ejercicio académico: es munición para negociar deuda más barata y para no malvender en una eventual reestructuración.`,
    ],
  },
  {
    heading: 'Errores frecuentes del CEO',
    paragraphs: [
      `**Creer que el patrimonio del balance es lo que vale la empresa.** El patrimonio neto contable es el residual de números históricos. En Andina, ajustar a mercado (+550, +160, −300, −30, +650) cambia el patrimonio en más de mil, más que un año entero de ganancia. Confiar en el número contable lleva a vender barato, asegurar mal y subestimar el poder de negociación frente a bancos y compradores.`,
      `**Confundir amortización con salida de caja.** Muchos dueños creen que la amortización "se lleva plata" cada año. No es así: la plata salió cuando se compró el activo (el CAPEX). La amortización es un asiento contable que no toca la caja, y por eso se suma de nuevo en el flujo de fondos. Confundir ambos lleva a leer mal el flujo operativo y a pensar que la empresa genera menos caja de la que realmente genera.`,
      `**Festejar tener muchos bienes de uso.** "Tengo un montón de máquinas" no es lo mismo que "tengo una empresa valiosa". Un activo fijo grande que no rota ni produce rentabilidad es capital inmovilizado, el mismo problema que el inventario obsoleto pero más difícil de liquidar. Antes de comprar más maquinaria, hay que preguntarse cuánto de la que ya se tiene está trabajando de verdad por encima del costo del capital.`,
      `**No separar CAPEX de mantenimiento de CAPEX de expansión, ni mirar la obsolescencia.** Tratar todo el CAPEX como "inversión que crece" oculta que buena parte solo repone desgaste. Y dejar maquinaria obsoleta valuada a neto contable infla el activo y el ROIC aparente. El CEO que no audita periódicamente el valor de mercado y la utilidad real de sus activos fijos navega con un mapa equivocado.`,
    ],
  },
  {
    heading: 'Qué decisiones habilita',
    paragraphs: [
      `Distinguir valor contable de valor de mercado habilita la decisión de **revaluar y poner a trabajar los activos ocultos**. El terreno de Andina, con 550 de valor no registrado, puede usarse como garantía para conseguir crédito más barato, puede venderse y arrendarse (sale and leaseback) para liberar caja, o simplemente entrar en la valuación correcta de la empresa frente a un socio o comprador. Lo que no se conoce no se puede capitalizar.`,
      `Permite **decidir con realismo sobre los activos sobrevaluados**: dar de baja o reemplazar la maquinaria obsoleta antes de que el deterioro sea total, en lugar de arrastrar en el balance un valor que el mercado no convalida. Y habilita reconocer los **intangibles invisibles** —la marca, la cartera— para protegerlos, potenciarlos e incorporarlos en cualquier negociación de venta, donde suelen valer más que toda la maquinaria junta.`,
      `Leer juntos capital de trabajo y CAPEX habilita **planificar el financiamiento del crecimiento antes de que ahogue la caja**. El CEO puede calcular cuánta caja consumirá expandirse —por capital de trabajo y por CAPEX— y conseguir el financiamiento a plazo y costo adecuados, en lugar de descubrir el agujero cuando ya está en el descubierto al 85%. La separación entre CAPEX de mantenimiento y de expansión le dice cuánto crecimiento se autofinancia.`,
      `Por último, habilita **decidir cada inversión en activo fijo contra el WACC**. Comprar una máquina deja de ser una corazonada y pasa a ser una pregunta financiera: ¿el retorno que genera supera el costo del capital? Un CEO que valúa sus activos a mercado, separa CAPEX de amortización y mide cada inversión contra su umbral de rentabilidad toma decisiones de capital que **crean valor** en lugar de inmovilizarlo.`,
    ],
  },
]
