// Contenido ampliado y detallado para el Word de la Semana 11.
// Tasas, tiempo y financiamiento inteligente.
// Markdown-lite: **negrita** y líneas que arrancan con "- " para listas.

export const deepDive11: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'La tasa que te dicen casi nunca es la tasa que pagás',
    paragraphs: [
      'Cuando un banco o un proveedor te ofrece financiamiento, te entrega un número. Ese número es casi siempre el más bajo de todos los que podrían describir la operación, porque está pensado para la vidriera, no para tu caja. Entre la tasa que te anuncian y la plata que efectivamente sale de tu cuenta hay tres capas que un CEO tiene la obligación de saber leer: **la capitalización**, que suma intereses sobre intereses; **la inflación**, que licúa o encarece el costo real; y **los gastos, comisiones e impuestos** que rodean a toda operación financiera. Cada capa puede sumar varios puntos, y juntas pueden duplicar lo que creías que pagabas.',
      'El error más caro de un dueño no es tomar deuda; es tomar deuda sin conocer su verdadero costo. Un CEO que firma mirando solo la tasa nominal está decidiendo con información deliberadamente incompleta, y va a descubrir el costo real recién cuando lo vea descontado de su caja, mes a mes, durante años. La diferencia entre un dueño que sufre el financiamiento y uno que lo administra es exactamente esta: el segundo sabe traducir cualquier oferta al único número que importa, cuánto me cuesta esto de verdad, todo incluido.',
      'Esta capacidad de traducción es lo que convierte una conversación con el gerente del banco en una negociación entre pares. Cuando podés mirar dos ofertas y decir cuál tiene mejor tasa efectiva, cuál tiene mejor costo financiero total y cuál tiene mejor tasa real según tu moneda de ingresos, dejás de ser un tomador de precio y pasás a elegir con criterio. El objetivo de la semana no es matemático por el gusto de la matemática: es darte el poder de no pagar de más.',
      'Andina vive esta confusión en carne propia. Toma descubierto bancario que le anuncian como una TNA del 85%, pero ese descubierto capitaliza a diario y arrastra impuestos y comisiones, de modo que su costo efectivo real supera holgadamente el 130%. El dueño cree que paga 85%; en los hechos paga la mitad otra vez más. Toda la semana se ordena alrededor de desarmar esa distancia entre el número anunciado y el número verdadero.',
    ],
  },
  {
    heading: 'TNA vs TEA: el efecto silencioso de la capitalización',
    paragraphs: [
      'La **TNA**, Tasa Nominal Anual, es una tasa que se anuncia en términos anuales pero se aplica por subperíodos. Si te dicen TNA del 60% con capitalización mensual, el banco en realidad te cobra un 5% por mes (60% dividido 12), y cada mes ese 5% se suma al capital y vuelve a generar intereses al mes siguiente. Esa reinversión automática del interés es la capitalización, y es la razón por la cual la tasa que efectivamente pagás termina siendo mayor que la que te anunciaron. La TNA ignora este efecto a propósito, porque mostrarlo la haría parecer más cara.',
      'La **TEA**, Tasa Efectiva Anual, sí incorpora la capitalización y por eso es la tasa honesta. La fórmula es **TEA = (1 + TNA/m)^m − 1**, donde m es la cantidad de veces que se capitaliza en el año: 12 si es mensual, 365 si es diaria. Hagamos el número: una TNA del 60% con capitalización mensual da una TEA de (1 + 0,05)^12 − 1 ≈ **79,6%**. Casi veinte puntos de diferencia respecto del 60% anunciado, generados por el solo mecanismo de cómo se capitaliza. Nada cambió en el contrato; solo lo leímos bien.',
      'El parámetro m es decisivo y explica por qué algunos productos son tan brutales. Cuanto más frecuente la capitalización, más se separa la TEA de la TNA, porque los intereses generan intereses más seguido. Un préstamo que capitaliza una vez al año tiene TEA igual a TNA; uno que capitaliza mensual ya se despega; y un descubierto que capitaliza a diario, como el de Andina, hace que una TNA del 85% se transforme en una TEA muy superior, porque cada día el interés se monta sobre el del día anterior. La frecuencia de capitalización es el motor oculto del costo.',
      'De acá sale la regla de oro de la semana, simple y salvadora: **nunca compares dos ofertas por su TNA**. La TNA sirve para la publicidad y para nada más. Para decidir, pasá siempre todo a TEA, y mejor todavía a costo financiero total. Dos préstamos con la misma TNA pueden tener TEAs muy distintas según cómo capitalicen, y elegir por el número de vidriera es elegir a ciegas.',
    ],
  },
  {
    heading: 'Tasa nominal vs tasa real: la ecuación de Fisher y la trampa de la moneda',
    paragraphs: [
      'Una tasa del 80% anual suena aterradora, pero el adjetivo correcto depende de la inflación. Si los precios suben 70% en el año, el dinero con el que vas a pagar esa deuda vale mucho menos al final que al principio, y tu deuda se licúa sola. En poder de compra real, ese 80% nominal cuesta muchísimo menos de lo que parece. Al revés, una tasa del 8% en dólares con inflación cero en esa moneda es 8% real puro, y puede resultar más cara en términos económicos que aquel 80% en moneda blanda. El número desnudo engaña; hay que vestirlo con la inflación.',
      'La **ecuación de Fisher** separa con precisión las dos componentes de toda tasa nominal: la parte que solo compensa la inflación y la parte que es el costo real del dinero. Su forma es **(1 + nominal) = (1 + real)·(1 + inflación)**, de donde se despeja **tasa real = (1 + nominal)/(1 + inflación) − 1**. Lo crucial es que Fisher no es una resta: con una tasa nominal del 80% y una inflación del 70%, la tasa real no es 80 − 70 = 10%, sino 1,80/1,70 − 1 ≈ **5,9%**. La intuición de restar lleva a errores grandes justo cuando las tasas son altas, que es cuando más importa acertar.',
      'Para un CEO que opera en LatAm, este concepto es vital y a menudo mal usado. Tomar deuda en pesos a tasa nominal alta puede ser perfectamente racional si tus ingresos también crecen con la inflación, porque la tasa real que pagás es moderada. Y tomar deuda barata en dólares puede ser una trampa mortal si tus ingresos están en moneda local: el día que esa moneda se devalúa, tu deuda en dólares se multiplica medida en lo que vendés, aunque la tasa nominal sea bajísima. El riesgo no está solo en la tasa, está en el descalce entre la moneda de tu deuda y la moneda de tus ingresos.',
      'La pregunta correcta, entonces, nunca es simplemente la tasa es alta. La pregunta correcta tiene tres partes que van juntas: en qué moneda están mis ingresos, en qué moneda es mi deuda, y cuál es la tasa real en cada caso. Un dueño que solo mira la tasa nominal de un solo producto está mirando una foto de un rompecabezas que necesita verse entero. Andina, cuyos ingresos siguen la inflación local, tiene un margen distinto de tolerancia a una tasa nominal alta que el que tendría si vendiera en dólares; ese matiz cambia toda la estrategia de financiamiento.',
    ],
  },
  {
    heading: 'El Costo Financiero Total: la única tasa que mide lo que de verdad pagás',
    paragraphs: [
      'La TEA captura el interés puro, pero ninguna operación financiera es solo interés. Encima del interés viaja una constelación de costos: gastos de otorgamiento, comisiones de administración, seguros de vida sobre el saldo, sellados, IVA sobre los intereses y el impuesto a los débitos y créditos, el famoso impuesto al cheque. Todo eso, sumado a la tasa, conforma el **Costo Financiero Total (CFT)**, y en operaciones de PyME suele ubicarse varios puntos por encima de la TEA. El CFT es la única tasa que responde la pregunta del dueño: cuánto sale esto de mi caja, absolutamente todo incluido.',
      'Hay un detalle que confunde a muchos dueños y conviene clarificar: algunos de estos impuestos son recuperables en el tiempo. El IVA sobre los intereses genera crédito fiscal, y una parte del impuesto al cheque se computa contra otros tributos. Es tentador concluir que entonces no son un costo real. Falso. Recuperarlos en el tiempo no es gratis, porque mientras tanto financiaste vos ese dinero, lo adelantaste de tu caja y lo recuperás meses después. El valor tiempo del dinero dice que un peso que te devuelven dentro de seis meses vale menos que un peso hoy, así que el recupero diferido tiene un costo financiero implícito que hay que contar.',
      'La disciplina que se desprende es concreta y debería ser un reflejo antes de cada firma. Primero, pedir siempre el CFT por escrito; un financiamiento serio lo informa, y quien se resiste a darlo está escondiendo algo. Segundo, si hay impuestos recuperables, calcular cuándo se recuperan y descontar ese flujo a valor presente, para reconocer el costo de adelantarlos. Recién con el CFT en la mano y los recuperos descontados sabés el costo verdadero, y recién ahí podés comparar manzanas con manzanas entre distintas ofertas.',
      'En el caso de Andina, su préstamo bancario con TNA del 60% se traduce en una TEA del orden del 79,6%, pero cuando se le suman gastos, sellados, IVA e impuesto al cheque, el CFT trepa a aproximadamente el 92%. Y descontada la inflación del 70%, la tasa real ronda apenas el 5,9%, que es baja siempre que sus ingresos sigan a la inflación. Esto muestra cómo un mismo préstamo se ve completamente distinto según el lente: catastrófico por CFT nominal, manejable por tasa real. Un CEO necesita los dos lentes para decidir bien.',
    ],
  },
  {
    heading: 'Sistemas de amortización: francés, alemán y americano',
    paragraphs: [
      'No solo importa cuánto cuesta la deuda; importa cómo la devolvés, porque el esquema de devolución cambia los intereses totales y el perfil de caja. Hay tres sistemas clásicos, cada uno con una lógica propia. El **sistema francés**, de cuota constante, es el más extendido en créditos, leasing y la mayoría de los préstamos bancarios: pagás siempre la misma cuota, pero su composición cambia, al principio casi todo es interés y poco capital, y con el tiempo se invierte. Su virtud es la previsibilidad de una cuota fija; su costo es que pagás más intereses totales que en el alemán, porque amortizás el capital más lento.',
      'El **sistema alemán**, de amortización constante, devuelve siempre la misma porción de capital, de modo que la cuota arranca alta y va bajando mes a mes a medida que el saldo adeudado se reduce. Como el capital baja más rápido, los intereses se calculan sobre saldos menores y el total de intereses pagados es menor que en el francés. Es el sistema ideal cuando tu caja es fuerte al principio y querés minimizar el costo total de la deuda; el precio es esa cuota inicial más exigente que hay que poder afrontar.',
      'El **sistema americano**, llamado bullet, tiene la lógica más distinta: durante toda la vida del préstamo pagás solo intereses, y el capital lo devolvés todo junto al final, en una sola bala. Libera caja durante el plazo, porque las cuotas intermedias son bajas, pero te deja un vencimiento final grande que tenés que tener planificado y fondeado. Es útil para puentear un período hasta un ingreso grande y conocido, por ejemplo financiar producción hasta el cobro de una exportación; es peligroso si llegás al final sin la bala lista.',
      'La elección, y este es el punto central, no es una cuestión financiera abstracta de cuál es mejor: es una cuestión de calce con tu flujo de caja. Si esperás caja floja ahora y fuerte después, el bullet o el francés te dan aire en el presente. Si ya tenés caja fuerte y querés pagar menos intereses en total, el alemán es superior. Andina, con su caja tensa hoy, probablemente necesite estructuras que descompriman el corto plazo, pero solo si eso forma parte de un plan para abaratar su deuda cara, no para postergar el problema. La pregunta correcta no es cuál sistema es mejor, sino cuál encaja con la forma de mi caja.',
    ],
  },
  {
    heading: 'El valor tiempo del dinero y el arte de ganar tiempo',
    paragraphs: [
      'El **valor tiempo del dinero** es uno de los principios más profundos de las finanzas y, bien entendido, cambia la forma de decidir de un CEO. La idea es simple: un peso hoy vale más que un peso mañana, porque el peso de hoy lo podés poner a trabajar, y porque sobre el peso futuro pesa la incertidumbre de que llegue. De este principio se desprende que el momento en que recibís o pagás dinero importa tanto como el monto. Dos operaciones por la misma cifra pero en distintos plazos no son equivalentes; descontadas a hoy, valen distinto.',
      'De acá surge una idea poderosa que muchos dueños subestiman: a veces conviene pagar un poco de costo financiero para ganar tiempo. Estirar un pago, financiar una compra, tomar plazo de un proveedor, son maneras de retener caja que te permite seguir operando, sostener la rueda del negocio y no descapitalizarte. Ganar tiempo no es sinónimo de patear problemas; cuando se hace bien, es comprar la posibilidad de que el negocio siga generando con esa caja que de otro modo habrías inmovilizado en un pago anticipado.',
      'La condición que separa el ganar tiempo inteligente del ruinoso es nítida: el costo de ganar ese tiempo tiene que ser menor que lo que el negocio gana operando con esa caja. Si tu negocio genera un retorno operativo del 30% sobre el capital que mueve y un proveedor te financia a un costo efectivo del 10%, ganar tiempo crea valor, porque la caja retenida rinde más que lo que cuesta retenerla. Si en cambio tapás un agujero con un descubierto al 130% solo para postergar el dolor, ganar tiempo es ruinoso, porque el costo de la espera supera de lejos cualquier rendimiento.',
      'La síntesis es que ganar tiempo es virtuoso cuando lo financiero está al servicio de lo económico, y destructivo cuando lo financiero se vuelve un fin en sí mismo para esconder un problema. Un CEO disciplinado se pregunta, cada vez que va a financiar algo para ganar tiempo, si la caja que retiene va a rendir más de lo que le cuesta retenerla. Si la respuesta es sí, gana tiempo con orgullo; si es no, paga y resuelve. Esa pregunta convierte el plazo en una herramienta de gestión en lugar de un calmante.',
    ],
  },
  {
    heading: 'Interrelaciones: cómo las tasas se conectan con todo el programa',
    paragraphs: [
      'La conexión más inmediata es con el **apalancamiento de la Semana 10**. El costo real de la deuda que entra en la fórmula del ROE apalancado no es la tasa nominal del contrato, sino el costo financiero total descontada la inflación. Un mismo nivel de deuda apalanca de manera completamente distinta según si su costo efectivo es del 12% o del 130%. Por eso no se puede diagnosticar bien el apalancamiento de Andina sin antes haber desarmado sus tasas: el descubierto al 85% nominal que capitaliza a diario es lo que vuelve negativo su diferencial entre ROIC y costo de deuda. Las dos semanas son una sola lectura.',
      'La segunda conexión es con el **capital de trabajo**. El financiamiento de proveedores, que aparece en el balance de Andina como 1280, es el crédito más barato que existe porque suele ser sin tasa explícita. Negociar 60 o 90 días de plazo en lugar de pagar al contado es, en los hechos, tomar un préstamo a costo casi cero, y cada peso que te financia un proveedor es un peso que no le pedís al banco al 85%. La negociación con proveedores no es solo comprar barato; es ingeniería financiera disfrazada de gestión de compras, y es el puente directo entre esta semana y la gestión del capital de trabajo.',
      'La tercera conexión es con el **costo de capital y la valuación**. El costo de la deuda que desarmamos acá es uno de los dos grandes componentes del WACC, la tasa con la que en la Semana 12 vamos a descontar los flujos para valuar la empresa. Abaratar la deuda, sustituyendo descubierto caro por financiamiento de proveedores o préstamos largos y baratos, baja el costo de la deuda, baja el WACC y, con todo lo demás constante, sube el valor de la empresa. Entender las tasas es, por esta vía, una palanca directa de creación de valor que se va a materializar en la valuación final.',
      'La cuarta conexión es con la **lectura económico-financiera de los estados** que atravesó todo el programa. Los 560 de intereses que figuran en el resultado de Andina, y que se comen el 67% de su EBIT de 830, son la traducción contable de todas las tasas mal gestionadas. Cuando un dueño aprende a leer las tasas, entiende por primera vez de dónde sale esa línea de resultados financieros que le destruye la utilidad, y deja de verla como un costo inevitable para empezar a verla como una variable que controla. Esa es la integración: las tasas no son un tema técnico aislado, son la causa de una de las líneas más dolorosas del estado de resultados.',
    ],
  },
  {
    heading: 'Errores frecuentes del CEO con las tasas y el financiamiento',
    paragraphs: [
      'El primer error es **comparar ofertas por la TNA**. Es el reflejo más común y el más caro, porque la TNA es justamente la tasa diseñada para esconder la capitalización. Dos préstamos con idéntica TNA pueden tener costos efectivos muy distintos según cómo capitalicen, y el dueño que elige por el número de vidriera suele terminar con la peor opción creyendo que eligió la mejor. La cura es un hábito: antes de comparar, pasar todo a TEA y a CFT.',
      'El segundo error es **abusar de los productos fáciles y caros**, el descubierto bancario y el descuento de cheques. Se contratan en cinco minutos y se pagan durante años. Son la heroína financiera de la PyME: alivio inmediato y dependencia crónica. El descubierto de Andina, con TEA real por encima del 130%, es el ejemplo perfecto de un producto que debería usarse solo como puente cortísimo y con fecha de salida, y que en cambio se volvió financiamiento estructural permanente. Confundir un puente con un piso es uno de los caminos más rápidos al sobreendeudamiento.',
      'El tercer error es **firmar cheques diferidos sin un calendario consolidado**. Cada cheque que firmás es una promesa de caja en una fecha futura, y el dueño desprolijo firma mirando la necesidad de hoy sin un cronograma de lo que vence. Cuando los vencimientos se amontonan en la misma semana, aparece el descubierto caro para salvar el cheque, y arranca la espiral. Andina arrastra 430 en cheques diferidos a pagar; sin un flujo de cheques por fecha cruzado contra las cobranzas, cada uno es una mini crisis esperando su turno.',
      'El cuarto error es **ignorar el descalce de monedas**. Tomar deuda barata en dólares cuando tus ingresos están en moneda local se siente inteligente por la tasa nominal baja, hasta el día de la devaluación, cuando esa deuda se multiplica medida en lo que vendés. La tasa más baja del mercado puede ser la decisión más cara si la moneda está descalzada. Un CEO prudente calza, en lo posible, la moneda de su deuda con la moneda de sus ingresos, y cuando no puede, dimensiona conscientemente el riesgo que está tomando en lugar de descubrirlo de golpe.',
    ],
  },
  {
    heading: 'Qué decisiones habilita dominar las tasas y el financiamiento',
    paragraphs: [
      'Un CEO que internaliza esta semana gana, antes que nada, el poder de **elegir financiamiento con criterio en lugar de aceptar el que le ofrecen**. Puede tomar tres ofertas, traducirlas todas a CFT y a tasa real según su moneda de ingresos, y elegir la genuinamente más barata, que muchas veces no es la del número de vidriera más bajo. Esa sola capacidad le ahorra, a lo largo de los años, sumas que suelen superar varios sueldos.',
      'La segunda decisión que habilita es **diseñar la estructura de repago a medida de su caja**. Sabiendo cómo funcionan los sistemas francés, alemán y americano, el dueño elige el que calza con su perfil de flujo: alemán si tiene caja fuerte y quiere pagar menos intereses, francés si necesita previsibilidad, bullet si está puenteando hasta un ingreso grande conocido. La amortización deja de ser un detalle impuesto por el banco y se vuelve una decisión de management alineada con la realidad de la empresa.',
      'La tercera decisión es **convertir a los proveedores en su banco más barato**. Entendido que el financiamiento sin tasa explícita es el mejor del mundo, el CEO invierte energía en negociar plazos de pago, porque cada día de plazo ganado a un proveedor es un día menos de descubierto al 85%. Si Andina estirara treinta días el plazo de sus 1280 de proveedores, liberaría caja que hoy cubre con su producto más caro. La gestión de compras se transforma, así, en una de las herramientas financieras más potentes y subutilizadas que tiene la empresa.',
      'La decisión final, y la más estratégica, es **saber cuándo ganar tiempo y cuándo pagar y resolver**. Armado con el valor tiempo del dinero, el dueño ya no patea problemas por inercia ni paga anticipado por ansiedad: calcula si la caja que retiene rinde más de lo que cuesta retenerla, y decide en consecuencia. Esa disciplina, sumada a la capacidad de leer cualquier tasa hasta el hueso, es lo que separa a una empresa que sangra por sus intereses, como Andina hoy, de una empresa que usa el financiamiento como un aliado del negocio. Lo financiero, bien dominado, deja de ser una amenaza y pasa a estar al servicio de lo económico.',
    ],
  },
]
