// Material AMPLIADO para el Word de la Semana 4
// Andina Manufacturas S.A. — EVA y el spread ROIC − WACC
// Español rioplatense, registro premium para CEO.

export const deepDive04: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'Por qué la ganancia contable miente sin querer',
    paragraphs: [
      `Cuando un CEO abre el Estado de Resultados y ve "Resultado neto: 175", su cerebro registra una palabra: **ganamos**. Y es verdad, contablemente ganamos. El problema es que la contabilidad fue diseñada para responder una pregunta muy específica —¿la empresa produjo un excedente luego de cubrir sus costos y sus impuestos?— y no fue diseñada para responder la pregunta que de verdad le importa al dueño: ¿este negocio crea o destruye riqueza? Son preguntas distintas, y confundirlas es el error más caro y más silencioso de la dirección de empresas.`,
      `La raíz del malentendido es estructural, no un descuido del contador. El Estado de Resultados resta **todos** los costos explícitos: la materia prima, los sueldos, los alquileres, los impuestos e incluso los intereses de la deuda. Pero hay un costo que jamás aparece en ninguna línea: **el costo del capital propio**, el de la plata que pusieron los dueños. Para la lógica contable, esa plata es gratis. Para la lógica económica, esa plata es lo más caro que tiene la empresa, porque podría estar rindiendo en otro lado y eligió quedarse acá.`,
      `Pensalo así: si vos como dueño pusiste capital en Andina, ese capital tiene un "alquiler" implícito. Es lo que ese mismo dinero te rendiría en una alternativa de riesgo equivalente —otro negocio, un bono, una inversión comparable—. Si Andina no te paga al menos ese alquiler, te está usando el capital gratis y vos estás subsidiando a tu propia empresa sin darte cuenta. El resultado neto de 175 no descuenta ese alquiler. Por eso puede ser positivo y, aun así, esconder una pérdida económica.`,
      `La consecuencia práctica es brutal: una empresa puede pasar **años** mostrando ganancias contables, repartiendo dividendos, dándole tranquilidad al dueño, y todo ese tiempo estar evaporando el patrimonio real de sus accionistas. Nadie suena la alarma porque el indicador que todos miran —la utilidad— está, técnicamente, en verde. Por eso esta semana es la bisagra del programa: a partir de acá, dejamos de preguntar "¿ganamos?" y empezamos a preguntar "¿creamos valor?".`,
    ],
  },
  {
    heading: 'El costo de oportunidad del capital: el dinero nunca es gratis',
    paragraphs: [
      `El concepto que sostiene todo lo demás es el **costo de oportunidad del capital**. La idea es simple de enunciar y difícil de internalizar: cada peso que está invertido en tu empresa **no está** invertido en otra cosa. Y esa "otra cosa" tendría un rendimiento. Ese rendimiento al que renunciás por tener la plata acá es el costo de tenerla acá. No te llega ninguna factura por él, pero es tan real como el sueldo que pagás a fin de mes.`,
      `Para la deuda, el costo es obvio porque hay una factura: el banco te cobra una tasa, y esa tasa figura en el Estado de Resultados como "Resultados financieros". En Andina, esos intereses son **560**, e incluyen el descubierto al ~85% anual y los préstamos en dólares al ~18%. Nadie discute que la deuda cuesta. El salto conceptual es entender que **el capital propio también cuesta**, aunque su costo no se pague con un cheque y no aparezca en ningún papel.`,
      `¿Cuánto cuesta el capital propio? Cuesta lo que los dueños podrían ganar arriesgando esa misma plata en una inversión de riesgo similar. Como Andina opera en una región de alto riesgo país, es una PyME (más riesgosa que una gran empresa) y está apalancada, el retorno que sus dueños exigirían es alto. No es un capricho: es la compensación lógica por el riesgo asumido. Cuanto más riesgoso el negocio, más caro el capital propio, porque nadie arriesga gratis.`,
      `Acá conviene desarmar un mito muy común entre los dueños de PyME: "la plata que puse yo no me cuesta nada, total es mía". Es exactamente al revés. La plata propia es la **más cara** de todas las fuentes de financiamiento, porque el dueño está en la última fila para cobrar (después del banco, del proveedor, del fisco y de los empleados) y por lo tanto soporta el mayor riesgo. A mayor riesgo, mayor retorno exigido. Tratar al capital propio como gratis es el origen de casi todas las decisiones de inversión que destruyen valor.`,
    ],
  },
  {
    heading: 'WACC: la valla que el negocio tiene que superar',
    paragraphs: [
      `Si la deuda tiene un costo y el capital propio tiene otro, necesitamos un número que combine ambos en una sola valla. Ese número es el **WACC** (Weighted Average Cost of Capital, costo promedio ponderado del capital). El WACC es el promedio del costo de cada fuente de financiamiento, ponderado por cuánto pesa cada una en la estructura total. Es, dicho en criollo, **cuánto cuesta en promedio cada peso que financia la empresa**, venga del banco o del bolsillo del dueño.`,
      `La palabra clave es "ponderado". No es un promedio simple: cada fuente entra según su peso. Si una empresa se financia 45% con deuda y 55% con capital propio, el WACC pesa el costo de la deuda al 45% y el costo del capital propio al 55%. Por eso una empresa muy endeudada con deuda barata puede tener un WACC bajo, mientras que una empresa apalancada con deuda cara —como Andina, con su descubierto al 85%— arrastra el WACC hacia arriba sin piedad.`,
      `Hay un detalle técnico que importa y que conviene que el CEO entienda: el costo de la deuda entra al WACC **neto de impuestos**. ¿Por qué? Porque los intereses son deducibles del impuesto a las ganancias: cada peso de interés que pagás reduce tu base imponible y te ahorra impuesto. Ese ahorro abarata la deuda en términos efectivos. Es el famoso "escudo fiscal" de la deuda, y es una de las pocas ventajas reales de endeudarse. El capital propio, en cambio, no genera escudo: los dividendos no son deducibles.`,
      `Para Andina, con su deuda cara y el riesgo país de la región, el WACC ronda el **21%**. No vamos a desarmarlo línea por línea esta semana —eso lo hacemos en la Semana 9, donde construimos el WACC con el modelo CAPM y los parámetros de mercado—. Por ahora alcanza con grabarse una idea: **21% es la valla**. Todo peso invertido en Andina que rinda menos de 21% por año está empobreciendo a sus dueños, sin importar lo que diga el resultado neto.`,
    ],
  },
  {
    heading: 'El spread ROIC − WACC: la brújula de la creación de valor',
    paragraphs: [
      `Acá llegamos al corazón de todo el programa, y cabe en una resta: **Spread = ROIC − WACC**. El ROIC (Return on Invested Capital) te dice cuánto rinde tu negocio por cada peso invertido. El WACC te dice cuánto cuesta cada peso invertido. La resta entre ambos te dice lo único que importa: si lo que el negocio produce **supera** lo que el negocio cuesta financiar. Si el spread es positivo, creás valor. Si es negativo, lo destruís. Así de simple y así de implacable.`,
      `La analogía más clara es la de la deuda personal. Imaginá que pedís un préstamo al 21% para invertirlo en algo que te rinde 9%. Cada mes perdés la diferencia: ganás 9, pagás 21, te empobrecés 12. No importa que la inversión "dé ganancia" (rinde 9%, es positiva en términos absolutos); en términos relativos al costo del dinero, es una sangría. Eso es exactamente lo que le pasa a Andina, pero a escala de toda la empresa y sin que el resultado neto lo grite.`,
      `El EVA (Economic Value Added) es simplemente ese spread expresado en dinero, no en porcentaje: **EVA = (ROIC − WACC) × Capital Invertido**. El spread te dice el "cuánto por ciento", y al multiplicarlo por todo el capital invertido obtenés el "cuántos pesos". Un spread de −1% sobre un capital pequeño es un problema chico; el mismo −1% sobre un capital enorme es una catástrofe. Por eso el EVA es tan poderoso: traduce la rentabilidad relativa a la moneda en la que realmente pensás.`,
      `Lo más importante del spread es que **convierte cada decisión en un filtro binario**. ¿Comprar esta máquina sube o baja el ROIC respecto del WACC? ¿Darle más crédito a este cliente acerca o aleja el spread? ¿Tomar este préstamo abarata o encarece el WACC? Todas las decisiones del CEO —absolutamente todas las que tocan capital— pueden y deben pasar por este único tamiz. El que dirige mirando el spread dirige mirando la creación de valor; el que dirige mirando el resultado neto dirige a ciegas.`,
    ],
  },
  {
    heading: 'Mini-caso numérico: Andina gana 175 y destruye valor',
    paragraphs: [
      `Pongamos los números de **Andina 2024** sobre la mesa y hagamos la cuenta completa, sin atajos. El punto de partida es el NOPAT (resultado operativo después de impuestos): EBIT de **830** menos el impuesto del 35%, lo que da un NOPAT cercano a **540** (830 × 0,65 ≈ 540). Esta es la ganancia operativa "limpia", sin la distorsión de cómo se financia la empresa. Es lo que el negocio produce para todos los que lo bancan.`,
      `Ese NOPAT de 540 hay que compararlo contra el capital invertido en el negocio. Sumando el capital de trabajo operativo (cuentas por cobrar de 1.850, inventarios de 2.400, otros créditos, menos proveedores y cargas) y el activo fijo neto (terreno, edificio, maquinaria, rodados, por encima de 2.500), el capital invertido de Andina es pesado: ronda los **6.000**. Dividiendo 540 sobre ese capital, el **ROIC da aproximadamente 9%**. El negocio rinde 9 centavos por cada peso invertido.`,
      `Ahora la comparación que lo cambia todo. **ROIC ≈ 9% contra WACC ≈ 21%.** El spread es **9% − 21% = −12%**. Negativo, y no por poco: por doce puntos enteros. Cada peso invertido en Andina rinde 9% pero cuesta 21%. Llevado a dinero: **EVA = −12% × 6.000 ≈ −720**. Andina destruyó alrededor de **720 de valor** en el año. Y mientras tanto, el Estado de Resultados mostraba, orgulloso, una ganancia de 175.`,
      `Detengámonos en esa contradicción porque es el alma del caso. **Contablemente: +175. Económicamente: −720.** No es que uno de los dos esté mal calculado; es que miden cosas distintas. El +175 es lo que sobró después de pagar costos, intereses e impuestos. El −720 es lo que se perdió después de exigirle al capital que rinda lo que cuesta. El dueño que solo mira el +175 duerme tranquilo mientras su patrimonio se erosiona a razón de cientos de miles de dólares por año. Esa es la trampa, con nombre, apellido y número.`,
    ],
  },
  {
    heading: 'Cómo se conecta con todo lo demás (interrelaciones)',
    paragraphs: [
      `El EVA no es una métrica aislada: es el **punto donde convergen** casi todos los conceptos del programa, y verlo así es lo que separa a un CEO financiero de uno contable. Empecemos por el ROIC, que vimos la semana pasada. El ROIC se descompone en margen (NOPAT sobre ventas) por rotación (ventas sobre capital invertido). Todo lo que mejora el margen o acelera la rotación **sube el ROIC** y, por lo tanto, ensancha el spread. El EVA es, en este sentido, el destino final de la palanca DuPont: margen y rotación terminan acá.`,
      `La conexión con la Semana 5 (económico vs financiero) es directa y dolorosa. La deuda cara de Andina —el descubierto al 85%— no solo se come el resultado neto vía intereses (560 que reducen los 175); también **encarece el WACC** y, por esa vía, hace más exigente la valla del spread. Es decir: el mismo problema financiero ataca a Andina por dos frentes simultáneos. Por un lado le baja la ganancia contable; por el otro le sube el costo del capital. Resolver el descubierto mejora ambas cosas a la vez.`,
      `La conexión con la Semana 6 (Free Cash Flow) cierra el círculo. El capital invertido que aparece en el denominador del ROIC está inflado justamente por lo mismo que drena la caja libre: cuentas por cobrar abultadas (clientes que no pagan) e inventario inmovilizado (mercadería dormida en el depósito). Ese capital de trabajo desbordado **agranda el capital invertido**, lo que **baja el ROIC** y empeora el spread. Y al mismo tiempo, ese capital atrapado es exactamente lo que la Semana 6 muestra drenando el FCFF. Un solo problema —la mala gestión del capital de trabajo— se manifiesta en tres lugares distintos.`,
      `Por último, el EVA se enlaza con la valuación (Semanas 9 y 10). El valor de una empresa es, en última instancia, el valor presente de los EVA futuros que sea capaz de generar (esta es la base del modelo MVA, Market Value Added). Una empresa que genera EVA negativo de forma sostenida no solo destruye valor año a año: **vale menos que el capital que tiene invertido**, porque el mercado descuenta esa destrucción futura. El spread de hoy es la semilla del valor de mañana.`,
    ],
  },
  {
    heading: 'Errores frecuentes del CEO',
    paragraphs: [
      `**Error 1: festejar el resultado neto.** El más universal y el más caro. El dueño ve "ganamos 175" y cierra el balance satisfecho. No se pregunta si esos 175 cubren el costo del capital. Andina lleva años "ganando" y empobreciendo a sus accionistas. El resultado neto es condición necesaria pero **no suficiente** para crear valor: hay que ganar más que el costo del capital, no apenas algo positivo.`,
      `**Error 2: creer que el capital propio es gratis.** "Es plata mía, no me cuesta". Este error lleva a aprobar inversiones que rinden 10% o 12% pensando que "algo es mejor que nada", cuando en realidad cualquier cosa que rinda menos del WACC (21%) destruye valor. El capital propio es la fuente más cara, no la más barata. Tratarlo como gratis distorsiona absolutamente todas las decisiones de inversión.`,
      `**Error 3: perseguir crecimiento sin mirar el spread.** Muchos CEO creen que crecer siempre es bueno. Pero si el ROIC es menor que el WACC, **crecer destruye más valor**, no menos: cada peso adicional invertido en un negocio con spread negativo agranda la pérdida económica. Andina, que creció de 7.400 a 8.200 en ventas, está agrandando el problema, no resolviéndolo, porque crece con un spread de −12%.`,
      `**Error 4: tomar deuda cara para "aprovechar oportunidades".** Cada vez que Andina toma descubierto al 85% para financiar una venta o un stock, encarece su WACC y empeora su spread. La oportunidad solo es oportunidad si rinde más que el costo de la plata que usás para tomarla. Financiar al 85% un negocio que rinde 9% es la receta perfecta para acelerar la destrucción de valor con cara de estar muy activo.`,
    ],
  },
  {
    heading: 'Qué decisiones habilita',
    paragraphs: [
      `Entender el spread y el EVA habilita la decisión más importante de todas: **un criterio único para asignar capital**. A partir de ahora, ninguna inversión se aprueba sin pasar por el filtro "¿esto rinde más que el WACC?". Comprar una máquina, abrir una sucursal, dar más crédito, lanzar un producto: todo se mide contra la misma valla del 21%. El capital escaso va donde el spread es más ancho, y se retira de donde el spread es negativo.`,
      `Habilita también una **estrategia de saneamiento en dos frentes** para Andina. Frente uno, subir el ROIC: mejorar el margen recortando lo que no agrega valor, acelerar la rotación cobrando antes y liquidando el inventario obsoleto (esos 420 de mercadería dormida), y desprenderse de activos que no rinden (el terreno subvaluado que vale 900 a mercado podría monetizarse). Frente dos, bajar el WACC: cambiar el descubierto del 85% por deuda estructurada más barata, reduciendo el costo promedio del capital de golpe.`,
      `Habilita una **conversación distinta con el directorio y con el banco**. En vez de presentar "ganamos 175", el CEO puede mostrar el EVA real y plantear el problema con números: "destruimos 720 de valor por año, y acá está el plan para cerrar el spread". Es una conversación incómoda pero honesta, y es la única que permite reaccionar a tiempo. La empresa que solo reporta utilidad contable se entera de su destrucción de valor cuando ya es tarde.`,
      `Finalmente, habilita un **cambio de mentalidad permanente**: pensar como dueño de capital y no como administrador de un Estado de Resultados. El CEO que internaliza el spread deja de preguntarse "¿este año dio ganancia?" y empieza a preguntarse "¿este año el capital de mis accionistas rindió más de lo que les costó tenerlo acá?". Esa pregunta, sostenida en el tiempo, es la diferencia entre una empresa que parece próspera y una que de verdad construye riqueza.`,
    ],
  },
]
