// Contenido ampliado y detallado para el Word de la Semana 10.
// Apalancamiento: la deuda como multiplicador de ganancias y pérdidas.
// Markdown-lite: **negrita** y líneas que arrancan con "- " para listas.

export const deepDive10: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'Qué es realmente el apalancamiento (y por qué casi nadie lo entiende del todo)',
    paragraphs: [
      'La palabra apalancamiento viene de palanca, y la imagen no es decorativa: es la esencia del concepto. Una palanca permite mover un peso enorme con una fuerza pequeña, siempre que tengamos un punto de apoyo. En finanzas, el peso es el activo que querés poner a trabajar, la fuerza pequeña es tu capital propio, y el punto de apoyo es la deuda. Cuando un CEO toma deuda, lo que hace en realidad es controlar más activos de los que su patrimonio le permitiría por sí solo. Esa es la primera idea que hay que grabar a fuego: **la deuda no es un costo, es un multiplicador de escala**.',
      'Ahora bien, hay dos apalancamientos distintos que muchas veces se mezclan. El **apalancamiento operativo** nace de la estructura de costos: cuanto más pesan los costos fijos frente a los variables, más se amplifica el efecto de un cambio en las ventas sobre el resultado operativo. El **apalancamiento financiero** nace de la estructura de financiamiento: cuanta más deuda con costo fijo (intereses) tengas, más se amplifica el efecto del resultado operativo sobre el rendimiento del dueño. Esta semana nos concentramos en el segundo, pero un CEO lúcido sabe que los dos se suman: una empresa con muchos costos fijos Y mucha deuda tiene un apalancamiento combinado feroz, que la vuelve gloriosa en los buenos años y letal en los malos.',
      'El error conceptual más común es creer que endeudarse es bueno o malo en abstracto. No lo es. El apalancamiento financiero es éticamente neutro y financieramente ambiguo: es una herramienta que multiplica lo que ya tenés. Si tu negocio rinde, multiplica el rendimiento; si tu negocio pierde, multiplica la pérdida. La deuda nunca convierte un mal negocio en bueno; solo convierte un buen negocio en mejor, o un mal negocio en una catástrofe más rápida. Por eso la decisión de apalancarse nunca debería ser una decisión financiera aislada: es una apuesta sobre la calidad y la estabilidad del negocio subyacente.',
      'Andina Manufacturas es el caso de estudio perfecto porque encarna el lado oscuro de la palanca. No tomó deuda para multiplicar un negocio que rendía: la tomó para sobrevivir, para tapar baches de caja. Su descubierto bancario de 540 al 85% de TNA no financió una máquina que genera valor; financió la diferencia entre lo que vendió y lo que pudo cobrar. Esa es la diferencia entre apalancamiento estratégico y apalancamiento de supervivencia, y es la línea que separa a un CEO que usa la deuda de un dueño que es usado por ella.',
    ],
  },
  {
    heading: 'La fórmula del ROE apalancado, desarmada término por término',
    paragraphs: [
      'La ecuación central de la semana es **ROE = ROIC + (ROIC − i·(1−t))·D/E**, y conviene desarmarla porque cada símbolo es una decisión de management. El **ROIC** es el rendimiento que genera el negocio sobre todo el capital invertido, sin importar de dónde salió ese capital: es la calidad pura del negocio. La **i·(1−t)** es el costo de la deuda después del escudo fiscal, porque los intereses son deducibles del impuesto a las ganancias y eso abarata la deuda real. La **D/E** es la relación deuda sobre patrimonio: la intensidad de la palanca. Y el **ROE** es el premio final para el dueño, lo que rinde su capital propio.',
      'Leída con atención, la fórmula cuenta una historia de tres actos. Primer acto: el negocio genera un ROIC. Si no hubiera deuda (D/E = 0), el ROE sería exactamente igual al ROIC. Segundo acto: aparece el diferencial **(ROIC − i·(1−t))**, que mide cuánto le gana el negocio al costo de su deuda. Tercer acto: ese diferencial se multiplica por D/E, la cantidad de palanca. Si el diferencial es positivo, cada vuelta de palanca suma al ROE; si es negativo, cada vuelta resta. El signo del diferencial es, literalmente, la diferencia entre la riqueza y la ruina apalancada.',
      'Hagamos el número con Andina. Supongamos un ROIC del 8% (el negocio rinde poco porque tiene mucho capital atrapado en cuentas por cobrar e inventario). El costo de la deuda antes de impuestos ronda el 18% en dólares según los supuestos del programa, así que después del escudo fiscal del 35% queda en aproximadamente 18%·(1−0,35) = **11,7%**. El diferencial es 8% − 11,7% = **−3,7%**: negativo. Cada peso de deuda que Andina suma a su estructura le resta rentabilidad al dueño. Con una D/E elevada, ese −3,7% se multiplica y el ROE termina por debajo del ROIC. La palanca está jugando en contra.',
      'El contraste es revelador: si Andina lograra subir su ROIC al 25% liberando capital de trabajo y abaratando su deuda, el diferencial pasaría a 25% − 11,7% = **+13,3%**, y la misma D/E que hoy la hunde la catapultaría. Esto demuestra el principio más importante de la semana: **la deuda no se arregla refinanciando la deuda; se arregla mejorando el negocio que está debajo**. El management del ROIC manda sobre el management de la deuda.',
    ],
  },
  {
    heading: 'Riesgo económico vs riesgo financiero: dos capas que no hay que confundir',
    paragraphs: [
      'Toda empresa carga dos riesgos que se apilan uno sobre el otro. El **riesgo económico** o del negocio es la incertidumbre inherente a la actividad: que caigan las ventas, que suba la materia prima, que un cliente grande migre, que aparezca un competidor. Este riesgo existe aunque la empresa no tenga ni un peso de deuda; depende del sector, de la estructura de costos, de la diversificación de clientes y de la posición competitiva. Andina, como fabricante de autopartes de reposición, tiene un riesgo económico moderado: el mercado de reposición es relativamente estable, pero sus clientes están concentrados y su margen es sensible al precio del acero.',
      'El **riesgo financiero** es el que agrega la deuda, y tiene una naturaleza distinta y más traicionera: es un riesgo de compromisos fijos. Los intereses y las amortizaciones de capital hay que pagarlos llueva o truene, vendas mucho o poco. En un mal año, el negocio puede absorber una caída de ventas reduciendo costos variables o márgenes; lo que no puede hacer es renegociar unilateralmente la cuota del banco. El riesgo financiero convierte la flexibilidad del negocio en rigidez de caja, y la rigidez en un mundo incierto es peligrosa.',
      'La clave estratégica es que **el riesgo financiero se monta sobre el económico y los dos se potencian**. Una empresa con negocio estable y predecible puede tolerar bastante deuda, porque la probabilidad de no poder pagar la cuota es baja. Una empresa con negocio volátil debería endeudarse poco, porque sumar compromisos fijos a ingresos inciertos es una receta de insolvencia. El pecado capital es el inverso de lo prudente: tomar mucha deuda en un negocio inestable. Ahí, un solo trimestre malo activa los dos riesgos a la vez y la empresa pasa de un problema de rentabilidad a un problema de supervivencia en semanas.',
      'Andina ilustra una versión particular de esta trampa: su riesgo económico es manejable, pero su deuda es de pésima calidad (corto plazo, carísima, atada al descubierto y a los cheques diferidos). No es tanto el monto de la deuda lo que la asfixia, sino su composición. Esto enseña un matiz fino: el riesgo financiero no se mide solo por cuánta deuda tenés, sino por qué tan exigente es esa deuda en términos de plazo, tasa y rigidez de los vencimientos. Una deuda larga y barata genera mucho menos riesgo financiero que una deuda corta y cara del mismo monto.',
    ],
  },
  {
    heading: 'La cobertura de intereses y el nivel óptimo de deuda',
    paragraphs: [
      'Si hubiera que elegir un solo número para diagnosticar la salud financiera de una empresa apalancada, sería la **cobertura de intereses**: cuántas veces el resultado operativo (EBIT) alcanza para pagar los intereses. La fórmula es simple, **Cobertura = EBIT / Intereses**, pero su lectura es profunda, porque mide el colchón que separa a la empresa del default. Una cobertura de 5x dice que aunque el EBIT cayera un 80%, todavía alcanzaría para pagar la deuda. Una cobertura de 1,5x dice que un tropezón del 33% en el EBIT ya deja a la empresa sin poder honrar sus intereses.',
      'Conviene tener un mapa de zonas. **Cobertura de 3x o más**: zona sana, hay holgura para pagar y hasta margen para tomar más deuda si la inversión lo justifica. **Cobertura entre 1,5x y 2x**: zona de alerta, los intereses ya consumen una porción importante del resultado operativo y cualquier sacudón económico se traslada directo al riesgo de impago. **Cobertura menor a 1x**: zona crítica, el negocio ni siquiera genera lo necesario para pagar sus intereses y la empresa está, de hecho, financiando intereses con más deuda, en una espiral que se acelera sola.',
      'Andina muestra el caso de manual de la zona de alerta. Su EBIT del año fue de **830** y pagó **560 de intereses**, de modo que su cobertura es 830 / 560 ≈ **1,5x**. Traducido: de cada peso de resultado operativo, casi dos tercios se evaporan en intereses antes de pagar un solo peso de impuesto o de dividendo. Le queda un colchón mínimo. Si las ventas cayeran apenas, o si subiera la tasa del descubierto, los 560 de intereses se comerían todo el EBIT y la empresa entraría en pérdida financiera estructural. Está caminando por el borde.',
      'El concepto de **nivel óptimo de deuda** surge de equilibrar dos fuerzas opuestas. De un lado, el escudo fiscal y el menor costo de la deuda frente al capital propio empujan a endeudarse más. Del otro, el aumento del riesgo de quiebra, los costos de estrés financiero y la pérdida de flexibilidad empujan a endeudarse menos. El óptimo no es un punto matemático exacto, sino un rango razonable donde la empresa captura el beneficio fiscal sin acercarse al precipicio. Para una PyME LatAm con volatilidad de ingresos, ese óptimo suele estar en coberturas de 3x a 4x: ni el extremo de cero deuda (que deja valor sobre la mesa) ni el extremo de Andina (que ya cruzó la raya de la prudencia).',
    ],
  },
  {
    heading: 'Modigliani-Miller: de la teoría pura a la decisión cotidiana',
    paragraphs: [
      'En 1958, Franco Modigliani y Merton Miller publicaron un teorema que dio vuelta las finanzas corporativas y les valió, con el tiempo, sendos premios Nobel. Su proposición, en un mundo idealizado sin impuestos, sin costos de quiebra y con información perfecta, era contraintuitiva hasta la provocación: **el valor de una empresa no depende de cómo se financia**. Da exactamente lo mismo que tenga mucha deuda o ninguna; el valor lo crea el negocio, no la mezcla del financiamiento. Cambiar la proporción de deuda y capital propio es como cortar una pizza en más o menos porciones: la pizza sigue siendo del mismo tamaño.',
      'La genialidad del teorema no estuvo en describir la realidad, porque ese mundo perfecto no existe, sino en obligar a toda la profesión a preguntarse: si en el vacío el financiamiento no importa, entonces ¿cuáles son exactamente las fricciones del mundo real que lo hacen importar? Esa pregunta es la que abrió la puerta a la versión práctica del teorema, la que un CEO realmente usa.',
      'Al relajar los supuestos aparecen dos fuerzas concretas. Con **impuestos**, la deuda gana una ventaja real: los intereses son deducibles, así que el Estado subsidia parte del costo financiero a través del escudo fiscal. Esto crea un incentivo genuino a usar algo de deuda, porque abarata el costo promedio del capital. Pero con **costos de quiebra y estrés financiero**, la deuda en exceso se vuelve cara de un modo que no aparece en la tasa de interés: proveedores que endurecen condiciones, bancos que cierran líneas, clientes que dudan de la continuidad, talento que se va, y un management que toma decisiones de corto plazo con la soga al cuello en lugar de invertir en el futuro.',
      'El punto donde el beneficio fiscal marginal de un peso más de deuda se iguala con el aumento marginal del costo esperado de quiebra es el nivel óptimo de la teoría del trade-off, la heredera práctica de Modigliani-Miller. La lección para el dueño es nítida: la deuda agrega valor solo en el margen y solo hasta cierto punto. Quien cree que va a salvar un negocio que no rinde consiguiendo más crédito entendió el teorema al revés. Modigliani y Miller no dicen endeudate; dicen que el valor nace del negocio y que el financiamiento solo lo afina en los bordes.',
    ],
  },
  {
    heading: 'Interrelaciones: cómo el apalancamiento se conecta con todo el programa',
    paragraphs: [
      'El apalancamiento no es un tema aislado: es el nudo donde se anudan casi todos los conceptos del programa. La conexión más directa es con el **ROIC y el WACC**. El apalancamiento solo crea valor cuando el ROIC del negocio supera el costo de la deuda después de impuestos, que a su vez es uno de los componentes del WACC. Por eso la pregunta de la deuda no se puede contestar sin antes haber contestado la pregunta del rendimiento: si el ROIC ya está por debajo del WACC, sumar deuda no rescata a la empresa, la hunde más rápido. El diagnóstico de valor precede al diagnóstico de financiamiento.',
      'La segunda gran conexión es con el **capital de trabajo**. Andina no se endeudó para comprar máquinas; se endeudó porque su capital de trabajo le devora la caja: las cuentas por cobrar crecieron 330 y los inventarios 550 en el año, casi 880 de caja atrapada que tuvo que financiar con descubierto al 85%. Esto revela una verdad incómoda: gran parte de lo que parece un problema de deuda es en realidad un problema de gestión operativa disfrazado. Cobrar más rápido y rotar mejor el inventario libera caja que repaga deuda cara, sin pedir un peso prestado. El capital de trabajo y el apalancamiento son dos caras de la misma moneda de liquidez.',
      'La tercera conexión es con el **costo del capital y la valuación**. Un nivel de deuda prudente y de buena calidad reduce el riesgo financiero percibido y puede, con el tiempo, bajar el WACC al que el mercado descuenta los flujos de la empresa. Un WACC más bajo, manteniendo todo lo demás constante, eleva el valor de la empresa. Por eso desapalancar y mejorar la calidad de la deuda no es solo una cuestión de dormir tranquilo: es una palanca directa de creación de valor que se va a materializar en la valuación por DCF de la Semana 12.',
      'La cuarta conexión, más sutil, es con las **tasas y los sistemas de amortización** de la Semana 11. El costo real de la deuda de Andina no es la tasa nominal que figura en el contrato, sino su costo financiero total con capitalización, comisiones e impuestos, y depende también del sistema de amortización elegido. Un mismo monto de deuda apalanca distinto según si su costo efectivo es del 12% o del 130%. Entender el apalancamiento sin entender cómo se forma la tasa es entender solo la mitad del problema; las dos semanas se leen juntas.',
    ],
  },
  {
    heading: 'Errores frecuentes del CEO con el apalancamiento',
    paragraphs: [
      'El primer error, y el más grave, es **confundir crédito disponible con salud financiera**. Muchos dueños sienten que el negocio va bien porque el banco les sigue prestando, cuando en realidad el banco presta mientras haya garantías, no mientras el negocio cree valor. Andina podría seguir consiguiendo descubierto un tiempo más, y eso no cambia que cada peso de ese descubierto al 85% destruye valor. La disponibilidad de crédito es un dato del mercado, no un diagnóstico de la empresa.',
      'El segundo error es **endeudarse para tapar problemas operativos en lugar de resolverlos**. Cuando la caja está tensa por cobranzas lentas e inventario inmovilizado, la salida fácil es el descubierto; la salida correcta es arreglar la cobranza y la rotación. La deuda usada como anestésico oculta el síntoma y permite que la enfermedad avance. El CEO debe entrenarse para distinguir, cada vez que va a tomar deuda, si está financiando crecimiento que rinde o tapando una hemorragia que debería suturar de otro modo.',
      'El tercer error es **mirar solo la cuota y no la cobertura ni el costo total**. Un dueño que evalúa una deuda por si puede pagar la cuota mensual está mirando el síntoma de hoy, no la estructura de riesgo. La pregunta correcta no es solo puedo pagar esta cuota, sino qué cobertura de intereses me deja esta deuda, qué pasa si las ventas caen 20%, y cuál es el costo financiero total verdadero. Mirar la cuota aislada es como manejar mirando solo el velocímetro y nunca el tanque de nafta.',
      'El cuarto error es el opuesto y también cuesta caro: **el dueño fóbico a toda deuda**. Quien jamás se endeuda por temor renuncia al escudo fiscal, financia todo con capital propio que es más caro, y suele crecer más lento que competidores que usan la palanca con prudencia. El extremo de cero deuda no es virtud financiera, es valor dejado sobre la mesa. La sabiduría no está en evitar la deuda ni en abrazarla, sino en calibrarla: la cantidad justa, de la calidad justa, para un negocio que rinde más que su costo.',
    ],
  },
  {
    heading: 'Cómo salir del sobreendeudamiento: un plan ordenado',
    paragraphs: [
      'Salir del sobreendeudamiento no es simplemente pagar deuda; es **cambiar la calidad del endeudamiento y atacar la causa que lo genera**. El primer movimiento, casi siempre, es matar la deuda más cara. En Andina, el descubierto bancario al 85% de TNA es el enemigo número uno: cada peso que sale de ahí rinde más que casi cualquier inversión que la empresa pudiera hacer. No existe proyecto industrial que rinda lo que cuesta no pagar ese descubierto, así que la prioridad absoluta es eliminarlo.',
      'El segundo movimiento es **estirar el plazo y cambiar deuda corta y cara por deuda larga y barata**. Aunque la deuda total no baje de inmediato, reemplazar el descubierto y los cheques diferidos por una línea de préstamo a mayor plazo descomprime la presión de caja inmediata, baja el riesgo financiero y da aire para gestionar. La gestión de pasivos no se trata solo de cuánto debés, sino de cuándo y a qué costo lo debés. Reperfilar la deuda es, muchas veces, la diferencia entre asfixiarse y respirar.',
      'El tercer movimiento es el que conecta con el resto del programa: **liberar el capital atrapado**. Acelerar cobranzas reduce las cuentas por cobrar, depurar y vender el inventario obsoleto (Andina tiene 420 de mercadería de lenta rotación) recupera caja inmovilizada, y monetizar activos ociosos como maquinaria obsoleta o incluso el terreno revaluado genera fondos para desendeudarse sin pedir un solo peso prestado. Esta es la fuente de repago más sana que existe, porque no agrega riesgo: simplemente desentierra caja que la propia empresa tenía atascada.',
      'Los dos últimos movimientos son disciplina pura. **No repartir dividendos mientras la cobertura sea frágil**: cada peso retenido fortalece el patrimonio y reduce la dependencia de la deuda; Andina repartió 120 de dividendos en un año en que su cobertura era de 1,5x, una decisión difícil de justificar. Y, por encima de todo, **atacar la causa y no el síntoma**: si la empresa se endeuda porque su negocio no genera caja, ninguna refinanciación la salva en el tiempo. Primero hay que hacer que el ROIC supere al costo del capital; recién entonces el desapalancamiento se vuelve sostenible en lugar de un parche que se vuelve a romper.',
    ],
  },
  {
    heading: 'Qué decisiones habilita dominar el apalancamiento',
    paragraphs: [
      'Un CEO que internaliza esta semana deja de tomar decisiones de financiamiento por intuición o por la oferta que le acerca el banco, y empieza a tomarlas con una vara clara. La primera decisión que habilita es **cuánta deuda tomar**: ya no se pregunta solo si puede pagar la cuota, sino si el ROIC del negocio supera el costo de la deuda después de impuestos y qué cobertura de intereses le deja la nueva estructura. Esa doble pregunta convierte una corazonada en un criterio.',
      'La segunda decisión es **qué calidad de deuda buscar**. Entendido que el riesgo financiero depende del plazo, la tasa y la rigidez tanto como del monto, el CEO prioriza deuda larga, barata y flexible, y huye de los productos fáciles y caros como el descubierto y el descuento de cheques salvo como puente cortísimo con fecha de salida. La gestión activa de la composición del pasivo pasa a ser una herramienta de management, no un trámite bancario.',
      'La tercera decisión es **cuándo desapalancar y con qué fuente**. Sabiendo que la caja más sana para repagar deuda no es más deuda sino el capital de trabajo liberado y los activos ociosos monetizados, el dueño ordena sus prioridades de repago de lo más caro a lo más barato y elige las fuentes de repago que no agregan riesgo. Y reconoce el momento en que debe suspender dividendos para fortalecer el patrimonio, una decisión impopular puertas adentro pero correcta cuando la cobertura es frágil.',
      'La decisión final, y la más importante, es **cómo transformar la deuda de amenaza en herramienta**. El objetivo no es una empresa sin deuda, sino una empresa que usa la deuda en el punto justo: lo suficiente para capturar el escudo fiscal y multiplicar un ROIC sano, sin acercarse al precipicio de la cobertura crítica. Cuando un dueño llega a ese punto, deja de temerle a la palanca y empieza a manejarla. Esa es la diferencia entre una empresa que la deuda controla y una empresa que controla su deuda, y es precisamente la posición desde la cual Andina podría dejar de destruir valor y empezar a crearlo.',
    ],
  },
]
