// ============================================================================
// DEEP DIVE — SEMANA 2
// "Contabilidad de presentación vs. información de gestión"
// Contenido ampliado y detallado para el documento Word de la Semana 2.
// Caso transversal: Andina Manufacturas S.A. (cifras en USD miles, 2024).
// ============================================================================

export const deepDive02: { heading: string; paragraphs: string[] }[] = [
  {
    heading: "Las dos contabilidades que conviven en toda empresa",
    paragraphs: [
      "La semana pasada aprendiste a **leer** los estados contables sin miedo. Esta semana damos un salto incómodo pero liberador: descubrir que **lo que los libros muestran no siempre es lo que realmente pasa**. No porque haya fraude ni error, sino porque la contabilidad que recibís fue diseñada con un propósito distinto al tuyo. Aprender a leer ya no alcanza; ahora hay que aprender a **traducir**.",
      "Toda empresa tiene, en la práctica, dos contabilidades. La primera es la **contabilidad de presentación**: la que se arma para mostrarle a terceros. El fisco quiere ver una base imponible y por eso prefiere que los activos no se inflen y que las ganancias no se escondan. Los bancos quieren ver garantías y ratios para decidir cuánto te prestan. Los consejos profesionales imponen normas de valuación que privilegian la **prudencia** y el **costo histórico**, porque su función es proteger a los terceros de una empresa que se sobrevalúe. Es una contabilidad pensada para **rendir cuentas hacia afuera**, no para tomar decisiones hacia adentro.",
      "La segunda es la **información de gestión**: la que un CEO necesita para entender qué está creando o destruyendo valor, dónde se atrapa la caja, qué activos rinden y cuáles pesan. Esta no aparece firmada en ningún balance. No la entrega el contador con el cierre. Hay que **buscarla, ajustarla y construirla**, partida por partida, comparando lo que dicen los libros con lo que la realidad indica. Ese trabajo de traducción es, justamente, el oficio financiero que se aprende esta semana y que ningún software te da hecho.",
      "La relación entre ambas no es de enemistad sino de **públicos distintos**. La contabilidad de presentación está perfectamente bien para lo suyo: cumple ante el fisco, el banco y la norma. El problema nace cuando el CEO la usa para decidir, como si la foto retocada para terceros fuera la verdad para él. Para el fisco, prudencia; para vos, la verdad de gestión. Confundir los públicos es el origen de la mitad de las malas decisiones patrimoniales de una PyME.",
    ],
  },
  {
    heading: "Por qué la prudencia y el costo histórico te ocultan la realidad",
    paragraphs: [
      "El principio que más distorsiona la foto contable se llama **costo histórico**: los activos se registran al precio que pagaste cuando los compraste, no al valor que tienen hoy. Este criterio tiene una virtud —es objetivo, verificable, no se presta a manipulación— y un defecto enorme para la gestión: **el tiempo lo vuelve mentiroso**. Un activo comprado hace veinte años figura a precios de hace veinte años, y nadie lo actualiza solo porque las normas no lo permiten libremente.",
      "El segundo principio es la **prudencia** (o conservadurismo): ante la duda, la contabilidad prefiere subvaluar antes que sobrevaluar, y prefiere no reconocer una ganancia hasta que sea segura. Por eso un terreno que se revalorizó no se ajusta hacia arriba en los libros, pero una pérdida probable sí debería reconocerse. El sesgo es deliberadamente pesimista, porque proteger a los terceros exige no mostrarles riqueza que quizás no existe. Para el dueño, ese pesimismo sistemático esconde patrimonio real.",
      "El tercer punto ciego es que la contabilidad **no reconoce los intangibles construidos internamente**. Si comprás una marca, figura; si la construiste vos a lo largo de veintidós años, vale cero en los libros. Lo mismo con la cartera de clientes fieles, el conocimiento del equipo, los procesos afinados. Es decir, **lo que más diferencia a tu empresa de un competidor cualquiera es exactamente lo que la contabilidad ignora**. Para el fisco tiene sentido (no se puede gravar algo tan difícil de medir); para vos, significa que tu activo más valioso es invisible.",
      "El cuarto sesgo es la **lentitud para castigar lo deteriorado**. La mora vieja sigue figurando como cuenta por cobrar mientras no se la dé formalmente por incobrable; el stock obsoleto sigue valuado a su costo de compra mientras no se lo previsione. La contabilidad reconoce el deterioro tarde, cuando ya es innegable, no cuando empieza a oler mal. El resultado combinado de estos cuatro sesgos es un balance que **subvalúa lo bueno y sobrevalúa lo malo** al mismo tiempo, en direcciones opuestas, lo que lo vuelve doblemente engañoso.",
    ],
  },
  {
    heading: "Valor contable vs. valor real: la brecha que corre en dos direcciones",
    paragraphs: [
      "El **valor contable** (o valor libro) es lo que figura registrado según las normas. El **valor real** (o de mercado, o de gestión) es lo que ese activo o pasivo vale verdaderamente hoy si tuvieras que venderlo, cobrarlo o realizarlo. La diferencia entre ambos es la **brecha**, y entenderla es el corazón de la semana. Lo traicionero es que la brecha **corre en las dos direcciones a la vez**, y por eso no se puede corregir con un simple coeficiente.",
      "En una dirección, los libros **subestiman** la riqueza. Hay **activos ocultos**: cosas que valen mucho más de lo que figuran, o que directamente no figuran. Un terreno comprado hace dos décadas, una marca construida a pulso, una cartera de clientes que vuelve año tras año. Estos activos existen, generan valor real, y sin embargo el patrimonio contable los ignora o los muestra a una fracción de su valor. Un dueño que no los ve cree ser más pobre de lo que es, y a veces vende o se descapitaliza sin necesidad.",
      "En la otra dirección, los libros **sobreestiman** la riqueza. Hay **pérdidas latentes** todavía no reconocidas: cuentas por cobrar que nunca se van a cobrar, inventario que ya nadie compra, maquinaria tecnológicamente vieja que vale menos que su valor neto contable. Estos quebrantos están escondidos dentro de partidas que el balance presenta como activos sanos. Un dueño que no los ve cree ser más rico de lo que es, y toma dividendos o compromisos sobre una riqueza que en parte es ficción.",
      "El problema, entonces, no es que exista la brecha: la brecha es inevitable dado cómo funciona la contabilidad de presentación. El problema es **decidir como si la brecha no existiera**. Un mismo balance puede tener al dueño simultáneamente más rico (por sus activos ocultos) y más pobre (por sus pérdidas latentes) de lo que cree. Solo construyendo el balance de gestión —ajustando cada partida a su valor real— se ve el patrimonio verdadero, que es la única base sólida para decidir.",
    ],
  },
  {
    heading: "Andina al microscopio: cuatro brechas que cambian todo",
    paragraphs: [
      "Abramos los libros de Andina y comparemos valor contable contra valor real, partida por partida. Empecemos por los **activos ocultos**, los que el balance subvalúa. **El terreno figura en libros a 350**, su valor histórico de hace más de dos décadas, pero a precio de mercado vale **900**. Hay **550 de riqueza oculta** que ningún estado contable muestra. Para colmo, ese terreno aparece sepultado entre los bienes de uso, sin ninguna nota que avise que vale casi el triple de lo registrado.",
      "El segundo activo oculto son los **intangibles**: la marca y la cartera de clientes que Andina construyó en veintidós años. Su valor de gestión ronda los **650**, y en los libros figuran en **0**. Pensalo: lo que hace que un cliente elija a Andina sobre un competidor, lo que sostiene sus ventas de 8.200, vale 650 de patrimonio real que la contabilidad sencillamente no reconoce. Sumando terreno e intangibles, Andina es **1.200 más rica** de lo que dice su balance solo por estos dos activos ocultos.",
      "Ahora los **activos sobrevaluados**, los que el balance infla. **Las cuentas por cobrar figuran en 1.850**, pero **290 corresponden a mora mayor a 120 días** con baja probabilidad de cobro. El valor real es **1.560**. Esos 290 el balance los cuenta como activo y la realidad casi no. Y **los inventarios figuran en 2.400**, pero **420 son mercadería obsoleta o de lenta rotación** valuada a costo histórico; a mercado valen mucho menos, el valor real ronda los **1.980**. Entre incobrables y obsoletos, hay **710 de activo que es más ficción que realidad**.",
      "La lectura combinada es reveladora y muestra por qué la brecha es tan traicionera. Por sus activos ocultos (terreno e intangibles, +1.200), Andina es **más rica** de lo que dice el balance. Por sus pérdidas latentes (incobrables y obsoletos, −710), en su capital de trabajo es **más pobre**. Ninguna de estas cuatro verdades está firmada por el contador, pero todas cambian cómo deberías dirigir la empresa: te dicen que tu patrimonio de largo plazo es sólido, pero que tu liquidez operativa es más frágil de lo que parece.",
    ],
  },
  {
    heading: "Interrelación: cómo la brecha de la Semana 2 reescribe la lectura de la Semana 1",
    paragraphs: [
      "Esta semana no reemplaza a la anterior: la **corrige**. Todo lo que leíste en los estados contables de la Semana 1 era valor de presentación, y ahora sabés que ese valor tiene una brecha sistemática contra la realidad. El ejercicio de gestión consiste en volver sobre cada estado y preguntarse: ¿este número es el de presentación o el real? La respuesta cambia conclusiones enteras.",
      "Tomemos el Patrimonio Neto, esa cuenta del balance que en la Semana 1 calculamos en **2.770** (capital 600 + reservas 320 + resultados acumulados 1.850). Ese es el patrimonio de presentación. El patrimonio de gestión es otro: hay que sumarle los activos ocultos (+550 del terreno, +650 de intangibles) y restarle las pérdidas latentes (−290 de incobrables, −420 de obsoletos). El neto de esos ajustes es **+490**, lo que lleva el patrimonio real a alrededor de **3.260**. Es decir, Andina tiene casi 500 más de patrimonio que el que muestra el balance, pero ese plus está concentrado en activos ilíquidos (un terreno, una marca) mientras el faltante está en su capital de trabajo, que es lo que necesita líquido.",
      "La conexión con el resto del programa es directa. La distinción entre lo **contable, lo económico y lo financiero** que vimos la semana pasada —resultado versus caja— se profundiza acá con una tercera capa: el **valor de gestión**. El resultado dice si ganaste en lo devengado; la caja dice si entró dinero; el valor de gestión dice cuánto vale realmente tu patrimonio. Tres lentes sobre la misma empresa, y un CEO completo usa los tres sin confundirlos.",
      "Y mira hacia adelante: la Semana 3 va a calcular el **capital invertido** de Andina para medir su ROIC. Si usáramos el capital de presentación, el ROIC saldría distorsionado, porque el capital invertido incluye cuentas por cobrar e inventarios que sabemos están inflados en 710. Los ajustes de gestión de esta semana son, literalmente, el insumo que hace que el cálculo de valor de la semana siguiente sea creíble. Sin traducir el balance a valor real, todo lo que viene después se construye sobre arena.",
    ],
  },
  {
    heading: "De datos a conocimiento, y de conocimiento a acciones",
    paragraphs: [
      "Los estados contables son **datos**. Por sí solos no deciden nada. El trabajo del CEO financiero es subir tres escalones, y cada partida de Andina ilustra el ascenso. **Primer escalón, el dato:** las cuentas por cobrar figuran en 1.850. Es un número en una hoja, neutro, sin interpretación. La contabilidad de presentación te entrega esto y te deja ahí.",
      "**Segundo escalón, el conocimiento:** 290 de esos 1.850 tienen mora mayor a 120 días y probablemente no se cobren; mi cobranza se está deteriorando y mi capital de trabajo está más comprometido de lo que el total sugiere. Ya no es un número: es una lectura, una interpretación que cruza el dato contable con el conocimiento del negocio. Subir este escalón requiere preguntar lo que el balance no dice: ¿qué antigüedad tiene esta cartera? ¿qué clientes la componen?",
      "**Tercer escalón, la acción:** reviso la política de crédito, le pongo límite a los clientes morosos, previsiono los 290 para verlos en el balance, y dejo de contarlos como caja futura en mis proyecciones. Eso es gestión. El mismo recorrido aplica al inventario: dato (figura 2.400), conocimiento (420 son obsoletos que no rotan), acción (liquidar el stock muerto aunque sea con pérdida, dejar de comprar lo que no gira, liberar la caja atrapada). Y aplica al terreno: dato (figura 350), conocimiento (vale 900, hay garantía ociosa), acción (usarlo como respaldo para refinanciar el descubierto caro con deuda más barata).",
      "La regla que ordena todo esto es simple y exigente: **si un análisis financiero no termina en una decisión concreta, todavía no terminó**. El propósito de construir el balance de gestión no es tener un número más lindo o más feo; es producir una **lista de acciones**. Cada brecha que detectás debe traducirse en algo que vas a hacer distinto el lunes. Si no, fue un ejercicio intelectual, no gestión.",
    ],
  },
  {
    heading: "Controlar lo estimado contra lo realmente sucedido",
    paragraphs: [
      "Hay una segunda disciplina de gestión que la contabilidad de presentación tampoco te da servida: **comparar lo que estimaste con lo que efectivamente pasó**. Cada vez que previsionaste incobrables, valuaste un inventario o proyectaste una cobranza, hiciste una **estimación**, un supuesto sobre el futuro. La contabilidad registra el supuesto, pero no vuelve a auditarlo contra la realidad. Esa vuelta es trabajo del CEO.",
      "La gestión madura consiste en regresar, meses después, y preguntarse sin piedad: ¿se cumplió mi estimación? Andina estimó que su cartera era cobrable, y la realidad le devolvió **290 de mora dura**. Estimó que su stock rotaba a un ritmo normal, y le quedaron **420 obsoletos** valuados a costo histórico. Estimó —implícitamente, al crecer— que las ventas se cobrarían a tiempo, y en cambio las cuentas por cobrar se estiraron 330 en el año. Cada una de esas brechas entre lo estimado y lo sucedido es un supuesto que se rompió.",
      "Lo valioso es que cada brecha es **información de altísima calidad sobre dónde tu modelo mental de la empresa está equivocado**. Si estimaste que la cartera era sana y resultó tener 290 de mora dura, aprendiste algo concreto: tu política de crédito es más laxa de lo que creías, o tu percepción de qué clientes son confiables está sesgada. Esa lección vale más que el número en sí, porque te permite ajustar el próximo presupuesto y la próxima decisión de crédito. El que controla sistemáticamente lo estimado contra lo real está calibrando su instrumento de navegación cierre tras cierre.",
      "Esta disciplina conecta directamente con la cultura de gestión que el programa quiere instalar. La contabilidad mira **hacia atrás y hacia afuera**: registra lo que pasó para mostrárselo a terceros. La gestión mira **hacia adelante y hacia adentro**: usa lo que pasó para decidir mejor lo que viene. El control de estimado contra real es el puente entre ambas: convierte el pasado contable en aprendizaje futuro. El dueño que lo practica deja de sorprenderse cada cierre; ya vio venir el problema porque viene midiendo la distancia entre lo que supuso y lo que ocurrió.",
    ],
  },
  {
    heading: "Errores frecuentes del CEO con el valor contable",
    paragraphs: [
      "**Creer que el patrimonio del balance es tu patrimonio real.** El error más caro de la semana. El balance de Andina dice 2.770 de patrimonio; el real ronda 3.260. Quien toma el número contable como verdad subestima su patrimonio en casi 500, pero —peor aún— no entiende que ese plus está atrapado en activos ilíquidos mientras su liquidez operativa está sobreestimada. El patrimonio contable no es ni tu riqueza real ni tu liquidez; es una convención para terceros.",
      "**Festejar activos que ya no valen lo que dicen.** Andina cuenta 2.400 de inventario y 1.850 de cuentas por cobrar como si todo fuera sólido. Pero 420 del stock es obsoleto y 290 de la cartera es incobrable. El CEO que se apoya en esos totales para pedir crédito, proyectar caja o repartir dividendos está construyendo sobre 710 de activo fantasma. El deterioro no reconocido a tiempo es una bomba que estalla en el peor momento, cuando hay que realizar esos activos y no aparece el comprador ni el pagador.",
      "**No ver lo que no figura.** El espejo del error anterior. Andina tiene 650 de marca y cartera, y 550 de plusvalía en su terreno, que el balance ignora. El dueño que solo mira los libros no sabe que tiene una garantía valiosísima ociosa (el terreno) ni que su activo competitivo más importante (la marca) ni siquiera está en el radar contable. No ver los activos ocultos lleva a desaprovechar palancas de financiamiento y a subvalorar la empresa al venderla o sucederla.",
      "**Usar la contabilidad de presentación para decidir.** El error que engloba a todos los anteriores. La contabilidad de presentación no está mal: cumple su función ante el fisco, el banco y la norma profesional. El error es del CEO que la usa para gobernar. Decidir con la foto retocada para terceros, en lugar de con el balance de gestión a valor real, es navegar con un mapa dibujado para otro viajero. La herramienta no falla; falla el uso.",
    ],
  },
  {
    heading: "Qué decisiones habilita distinguir presentación de gestión",
    paragraphs: [
      "La primera decisión que se desbloquea es **construir tu balance de gestión** y, con él, saber tu patrimonio real. Para Andina eso significa pasar de los 2.770 contables a los ~3.260 de gestión, pero sabiendo exactamente dónde está cada peso: 1.200 en activos ocultos sólidos pero ilíquidos, −710 en activos sobrevaluados dentro del capital de trabajo. Esa radiografía corregida es la base de cualquier decisión patrimonial seria: vender, suceder, asociarse, garantizar.",
      "La segunda decisión es **aprovechar los activos ocultos como palancas**. El terreno que vale 900 y figura a 350 es una garantía real subutilizada: puede respaldar la refinanciación del descubierto al 85% por deuda mucho más barata, atacando de raíz los 560 de intereses que ahogan el resultado. La marca y la cartera de 650 son activos que se pueden monetizar, licenciar o, como mínimo, valuar correctamente al momento de negociar con un socio o un comprador. Lo que no se ve, no se usa; verlo habilita usarlo.",
      "La tercera decisión es **sincerar y limpiar los activos sobrevaluados**. Reconocer los 290 de incobrables y los 420 de obsoletos duele en el resultado del período, pero limpia el balance y, sobre todo, libera gestión: una política de crédito más estricta corta la sangría de cobranzas, y liquidar el stock muerto recupera caja que estaba inmovilizada. Sincerar no es solo prudencia contable; es la condición para que el capital de trabajo deje de drenar la caja que vimos sufrir en la Semana 1.",
      "Finalmente, esta semana habilita la cultura del **control estimado-versus-real** como hábito permanente. No es una decisión puntual sino un sistema: cada cierre, comparar lo que se supuso con lo que ocurrió, y ajustar el modelo mental. Ese hábito es lo que separa al dueño que se sorprende del que anticipa. Y prepara el terreno para la Semana 3, donde con el balance ya sincerado a valores reales vamos a medir, por fin, si Andina crea o destruye valor: la pregunta que el margen nunca pudo responder.",
    ],
  },
];
