// Material ampliado (deep dive) para el Word de la Semana 9.
// Costo del capital: WACC en mercados emergentes, CAPM ajustado.
// Caso central: Andina Manufacturas S.A. (cifras en miles de USD).

export const deepDive09: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'La plata nunca es gratis, aunque el balance no te la cobre',
    paragraphs: [
      `Hay un costo que no aparece en ninguna línea de tu Estado de Resultados y que, sin embargo, es el más importante de todos: el **costo del capital propio**. Los intereses de los préstamos sí se ven —Andina paga **560 de intereses** al año, bien visibles—. Pero el dinero que pusieron los dueños, el patrimonio neto, parece "gratis" porque no hay un renglón que lo cobre. **No lo es.** Que no se facture no significa que no cueste; significa que el costo está escondido, y los costos escondidos son los que más daño hacen.`,
      `Cuando un dueño pone plata en su empresa, **deja de poder ponerla en otro lado**: un plazo fijo, un bono soberano, otro negocio, el mercado accionario. El rendimiento que resigna al elegir su empresa es su **costo de oportunidad**, y es un costo tan real como un interés bancario, aunque ningún contador lo registre. Si la empresa rinde menos que esa alternativa de riesgo comparable, el dueño estaría mejor cerrando y poniendo la plata en otra cosa, **aunque el balance muestre ganancia**. La rentabilidad contable positiva puede convivir con la destrucción de valor económico.`,
      `El **WACC** (Weighted Average Cost of Capital, costo promedio ponderado del capital) junta las dos fuentes de financiamiento —la deuda y el capital propio— en una sola tasa que responde: **¿cuánto cuesta, en promedio, cada peso que financia la empresa?** No es un peso de deuda ni un peso de equity por separado, sino la mezcla ponderada de ambos. Es la síntesis de todo lo que la empresa le debe pagar a quienes pusieron plata, sean acreedores o dueños.`,
      `El WACC es la **contracara exacta del ROIC**. El ROIC mide cuánto **rinde** el capital invertido; el WACC mide cuánto **cuesta**. La regla de oro de las finanzas corporativas se reduce a comparar estos dos números: si **ROIC > WACC**, la empresa crea valor; si **ROIC < WACC**, lo destruye, por más que el Estado de Resultados muestre utilidad. Conocer el verdadero costo del capital no es un lujo académico: es la vara contra la que se mide si la empresa, y cada inversión dentro de ella, vale la pena.`,
    ],
  },
  {
    heading: 'Las dos piezas: Ke y Kd, y por qué se ponderan',
    paragraphs: [
      `El costo del capital tiene dos componentes. El **Ke (costo del equity)** es lo que exigen los dueños por su dinero: no se factura, pero es un costo de oportunidad real, y se estima con el modelo **CAPM**. El **Kd (costo de la deuda)** es la tasa que cobran los acreedores: en Andina, **18% en USD**, y tiene una ventaja que el equity no tiene: los intereses son **deducibles del impuesto a las ganancias** (el escudo fiscal). Estas dos fuentes no cuestan lo mismo ni asumen el mismo riesgo.`,
      `La deuda es **estructuralmente más barata** que el capital propio, por dos razones. Primero, los acreedores **cobran antes**: en caso de problemas, la deuda tiene prioridad sobre los dividendos, así que asume menos riesgo y exige menos retorno. Segundo, los intereses son deducibles, mientras que los dividendos no lo son. Por eso, en la fórmula del WACC, **la deuda entra después de impuestos y el equity entra entero**. Esta asimetría es la base de toda la discusión sobre estructura de capital óptima.`,
      `La **ponderación (E/V y D/V)** es decisiva: no da lo mismo una empresa financiada 80% con capital propio que otra 50/50. Se calcula cuánto pesa cada fuente sobre el total (**V = E + D**) y, idealmente, se usan **valores de mercado** y una **estructura objetivo** —la mezcla hacia la que la empresa apunta— en lugar de la foto contable de hoy, que puede ser circunstancial. Andina trabaja con una estructura objetivo de alrededor de **45% deuda y 55% capital propio**.`,
      `El **WACC** resultante es el promedio ponderado de Ke y Kd (este último neto de impuestos), y funciona como el **umbral mínimo de rentabilidad** que la empresa debe superar para crear valor. Todo proyecto, toda compra de maquinaria, toda expansión, debe rendir por encima del WACC. Es, simultáneamente, la tasa con la que se descuentan los flujos futuros en una valuación y el piso contra el que se mide cada decisión de inversión. Una sola tasa con dos usos centrales.`,
    ],
  },
  {
    heading: 'CAPM ajustado: por qué arrancamos mirando a Estados Unidos',
    paragraphs: [
      `El **CAPM (Capital Asset Pricing Model)** dice que el rendimiento exigido a una inversión riesgosa es la tasa libre de riesgo más una prima proporcional a su riesgo sistemático. En su forma de manual: **Ke = Rf + β × Prima de mercado**. La tasa libre de riesgo es el piso (lo que rinde no arriesgar nada), y la prima compensa por el riesgo asumido, escalada por el **beta**, que mide cuánto se mueve la inversión respecto del mercado: un beta de 1 se mueve igual que el mercado, mayor a 1 amplifica, menor a 1 amortigua.`,
      `El problema es que esa fórmula **nació para mercados desarrollados, líquidos y eficientes**, como el de Estados Unidos, donde hay décadas de datos confiables de tasas, betas y primas. En LatAm no tenemos esos datos: nuestros mercados son chicos, ilíquidos y volátiles, y las series están contaminadas por inflación y saltos de tipo de cambio. Construir un beta o una prima de mercado puramente local sería **armar un castillo sobre arena**: los números existirían, pero no serían confiables para tomar decisiones de millones.`,
      `La salida que usa la práctica profesional —el enfoque de Damodaran y de la banca de inversión— es **empezar con los indicadores robustos de EEUU y trasladarlos a la economía local sumándole los riesgos que esa economía agrega**. Dos ajustes son los protagonistas. El **riesgo país** es la prima extra que exige el mercado por invertir en una economía emergente: default soberano, controles de cambio, inestabilidad institucional. Se aproxima con el **EMBI**, el índice de bonos emergentes. La **prima por tamaño** reconoce que una PyME es más riesgosa que una multinacional cotizante: menos acceso al crédito, más dependencia de pocos clientes, menos espalda para aguantar un mal año.`,
      `Así, el CAPM "puro" de EEUU se convierte en un **CAPM ajustado** que sí refleja lo que de verdad le cuesta el capital a una PyME latinoamericana: **Ke = Rf + β × ERP + Riesgo País + Prima por tamaño**. La lógica es honesta: usamos los cimientos sólidos de un mercado maduro (Rf, ERP, beta sectorial) y le sumamos, de forma explícita y justificada, los riesgos reales del lugar donde la empresa opera. No es trampa ni atajo: es la única forma rigurosa de estimar un costo de capital donde los datos locales no alcanzan.`,
    ],
  },
  {
    heading: 'Beta apalancada: el ajuste de Hamada',
    paragraphs: [
      `El **beta** que se publica para un sector suele ser un **beta apalancado**, que mezcla el riesgo del negocio con el riesgo de la estructura de deuda de las empresas que se usaron para calcularlo. Para usarlo en tu empresa, hay que limpiarlo y volverlo a ensuciar con **tu** propio apalancamiento. Ese proceso es la **ecuación de Hamada**, una de las técnicas más útiles y menos conocidas por los dueños de PyME.`,
      `Primero se **desapalanca** el beta sectorial para aislar el riesgo puro del negocio, sin efecto de deuda: el **beta desapalancado (unlevered)**. En el caso de Andina, ese beta del sector autopartes es **0,85**, ya limpio de estructura financiera. Refleja únicamente cuán riesgoso es el negocio de fabricar autopartes, con independencia de cómo se financie cada empresa del sector. Es el punto de partida correcto, porque el riesgo operativo del negocio es comparable entre empresas, pero el financiero no.`,
      `Luego se **reapalanca** con la estructura objetivo de tu empresa, usando la fórmula de Hamada: **β apalancado = β desapalancado × [1 + (1 − t) × (D/E)]**. Con la mezcla objetivo de Andina (D ≈ 45%, E ≈ 55%, es decir D/E ≈ 0,82) y una tasa del 35%: **β apalancado = 0,85 × [1 + 0,65 × 0,82] ≈ 0,85 × 1,53 ≈ 1,30**. El apalancamiento amplifica el riesgo que perciben los accionistas, porque la deuda mete prioridad de pago por delante de ellos y vuelve más volátil el retorno del equity.`,
      `En el caso simplificado de Andina trabajamos directamente con el beta de **0,85** para no recargar la cuenta —y el resultado del WACC queda en el mismo orden—, pero es importante que el CEO entienda el mecanismo: **el beta no es un dato fijo, depende de cuánta deuda tenés**. Más deuda sube el beta apalancado, sube el Ke y, hasta cierto punto, puede subir el WACC, aunque la deuda sea más barata. Acá está la tensión central de la estructura de capital: la deuda baja el costo promedio por ser barata, pero encarece el equity por riesgo. Hamada es la herramienta que cuantifica ese ida y vuelta.`,
    ],
  },
  {
    heading: 'Andina: construimos su Ke y su WACC paso a paso',
    paragraphs: [
      `Tomemos los parámetros de mercado del caso (LatAm, en USD para neutralizar la inflación local). **Tasa libre de riesgo (Rf): 4,3%** (bono del Tesoro de EEUU a 10 años). **Beta (β): 0,85** (riesgo del sector autopartes). **Prima de mercado (ERP): 5,5%** (prima por invertir en acciones vs. bonos en un mercado maduro, según Damodaran). **Riesgo país: 6,5%** (riesgo soberano LatAm, EMBI ajustado). **Prima por tamaño: 3,5%** (Andina es una PyME, no una multinacional cotizante).`,
      `Armamos el **costo del equity** con el CAPM ajustado: **Ke = 4,3% + 0,85 × 5,5% + 6,5% + 3,5%**. Desarrollado: el componente de mercado es **0,85 × 5,5% = 4,68%**; sumamos **4,3% + 4,68% + 6,5% + 3,5% ≈ 19,0%**. Le pedimos casi **19%** al capital propio. Parece alto, pero es lo coherente con poner plata en una PyME industrial de un país emergente: si el dueño no le saca cerca de eso, estaría mejor con la plata en otro lado de riesgo comparable. Notá que el riesgo país (6,5%) y la prima por tamaño (3,5%) **juntos pesan 10 puntos**: la mitad del Ke viene de operar en LatAm siendo PyME.`,
      `Ahora el **costo de la deuda con su escudo fiscal**. Andina paga **18%** de tasa y la alícuota es **35%**, así que el costo real de esa deuda para la empresa no es 18% sino **Kd después de impuestos = 18% × (1 − 0,35) = 11,7%**. El **escudo fiscal** es la diferencia: el Estado te "devuelve" 6,3 puntos vía menor impuesto a las ganancias, porque los intereses son deducibles. Esa es la ventaja estructural de la deuda que el equity nunca tiene.`,
      `Combinamos ambos en el **WACC = (E/V) × Ke + (D/V) × Kd × (1 − t)**. Con la estructura objetivo (E ≈ 55%, D ≈ 45%): **0,55 × 19,0% + 0,45 × 18% × (1 − 0,35) ≈ 10,45% + 5,27% ≈ 21,7%**, es decir, un WACC del orden de **21-22%**. Ese es el costo promedio de cada peso que financia Andina, y el umbral que cualquier inversión suya tiene que superar. Comparalo con su ROIC: si Andina rinde sobre el capital invertido menos de 21-22%, está destruyendo valor aunque su Estado de Resultados muestre 175 de ganancia.`,
    ],
  },
  {
    heading: 'Interrelaciones: el WACC como vara de toda la empresa',
    paragraphs: [
      `El WACC es el concepto que **cierra y unifica** todo el programa, porque es la vara contra la que se mide cada decisión vista hasta acá. Su conexión más fuerte es con el **ROIC**: son los dos lados de la misma moneda, rendimiento contra costo del capital invertido. La gestión financiera entera se puede resumir en empujar el ROIC hacia arriba y el WACC hacia abajo, ensanchando la brecha (el "spread de valor") entre lo que el capital rinde y lo que cuesta.`,
      `Se conecta directamente con el **capital de trabajo (Semana 7)** y con los **bienes de uso (Semana 8)**, porque ambos forman el **capital invertido** que el WACC pone precio. Cada peso atrapado en el inventario de 153 días de Andina, cada peso inmovilizado en una máquina obsoleta, "cuesta" 21-22% al año en costo de oportunidad. Liberar capital de trabajo y poner a trabajar el activo fijo no solo mejora la caja: **reduce el capital sobre el que aplica el WACC**, mejorando el spread de valor por el lado del denominador.`,
      `Hay una interrelación interna fascinante dentro del propio WACC, que es la **tensión de la estructura de capital**. Tomar más deuda baja el WACC porque la deuda es barata y trae escudo fiscal... hasta cierto punto. Vía Hamada, más deuda sube el beta apalancado, sube el Ke y aumenta el riesgo de quiebra. Existe un punto óptimo donde el WACC se minimiza; pasarse de deuda —como hace Andina, que financia capital de trabajo con descubierto al 85%— no baja el WACC sino que dispara el riesgo y el costo financiero. La deuda barata y bien dosificada crea valor; la deuda cara y desesperada lo destruye.`,
      `Finalmente, el WACC es el motor de la **valuación**: el valor de una empresa es el flujo de caja libre futuro descontado al WACC. Un punto más o menos de WACC cambia la valuación de forma dramática, sobre todo en flujos perpetuos. Por eso subestimar el costo del capital —usar una tasa de EEUU ignorando riesgo país y prima por tamaño— no solo lleva a aprobar malas inversiones: también lleva a **sobrevaluar la propia empresa** y a negociar mal una venta o un aporte de socios.`,
    ],
  },
  {
    heading: 'Errores frecuentes del CEO',
    paragraphs: [
      `**Creer que el capital propio es gratis.** El error conceptual más extendido. Como el equity no se factura, el dueño lo trata como costo cero y mide el éxito solo por la ganancia contable. Pero el capital propio tiene un costo de oportunidad real (cerca del 19% en Andina), y una empresa que no lo supera está empobreciendo a su dueño aunque muestre utilidad. Ignorar el Ke es ignorar la mitad del costo del capital.`,
      `**Subestimar el WACC usando una tasa "de EEUU" o "lo que cuesta el banco".** Si Andina midiera su costo de capital propio en 10% (ignorando riesgo país y prima por tamaño), creería que crea valor con un ROIC del 12%, cuando en realidad lo destruye, porque su WACC real es casi el doble. Subestimar el WACC es el error más caro y silencioso de la gestión financiera: te lleva a aprobar inversiones que te empobrecen, convencido de que te enriquecen.`,
      `**No ajustar el beta por el apalancamiento (saltearse Hamada).** Usar un beta sectorial publicado sin desapalancarlo y reapalancarlo con la propia estructura lleva a un Ke equivocado. Una empresa muy endeudada que usa un beta de empresas poco endeudadas subestima su riesgo de equity y, otra vez, su WACC. El beta no es un dato fijo del sector: depende de cuánta deuda tenés vos.`,
      `**Pensar que más deuda siempre baja el WACC.** La deuda es barata y trae escudo fiscal, pero pasado el punto óptimo dispara el beta apalancado, el costo del equity y el riesgo de quiebra. Andina, que financia capital de trabajo estructural con descubierto al 85%, es el ejemplo de manual: su exceso de deuda cara no le baja el WACC, le incendia el resultado con 560 de intereses. La estructura de capital tiene un óptimo, no una regla de "más es mejor".`,
    ],
  },
  {
    heading: 'Qué decisiones habilita',
    paragraphs: [
      `Conocer el WACC habilita, antes que nada, **el filtro de toda inversión**: un umbral concreto contra el cual medir cada proyecto, cada compra de maquinaria, cada expansión. La pregunta deja de ser "¿esto da ganancia?" y pasa a ser "¿el retorno supera el 21-22% que me cuesta el capital?". Andina necesita un ROIC por encima de su WACC solo para empatar; con esa vara, descarta proyectos que parecían buenos pero destruyen valor, y prioriza los que de verdad enriquecen al dueño.`,
      `Habilita **gestionar la estructura de capital con criterio**. Sabiendo cómo la deuda baja el WACC por ser barata pero lo sube por riesgo (vía Hamada), el CEO puede buscar la mezcla que minimiza su costo de capital: reemplazar el descubierto al 85% por deuda de largo plazo más barata, dosificar el apalancamiento, y dejar de confundir "deuda barata" con "más deuda siempre conviene". Bajar el WACC un solo punto vale, en valuación, muchísimo más que un año de margen.`,
      `Permite **valuar la empresa con rigor** y, por lo tanto, negociar bien. Con el WACC correcto, el dueño puede descontar sus flujos futuros y poner un número defendible a su empresa frente a un socio, un banco o un comprador, sin sobrevaluarla por usar una tasa irrealmente baja ni subvaluarla por excederse en el riesgo. El WACC convierte la valuación de una opinión en un cálculo.`,
      `Por último, habilita **alinear toda la gestión detrás de la creación de valor**: empujar el ROIC hacia arriba (mejor rotación, mejor margen, menos capital ocioso) y el WACC hacia abajo (mejor estructura de financiamiento, menos riesgo evitable). Esa es la síntesis de las finanzas corporativas y el cierre natural del programa: un CEO que conoce su verdadero costo del capital deja de gestionar por la ganancia contable y empieza a gestionar por el valor que su empresa **crea o destruye** cada año.`,
    ],
  },
]
