// ============================================================================
// DEEP DIVE — SEMANA 3
// "De la utilidad al valor operativo: NOPAT, Capital Invertido y ROIC"
// Contenido ampliado y detallado para el documento Word de la Semana 3.
// Caso transversal: Andina Manufacturas S.A. (cifras en USD miles, 2024).
// ============================================================================

export const deepDive03: { heading: string; paragraphs: string[] }[] = [
  {
    heading: "El margen es solo un tercio de la historia",
    paragraphs: [
      "Muchísimas direcciones de PyME viven mirando una sola cifra: el **margen** del Estado de Resultados. Gané 8% sobre ventas, estoy bien. Es la cifra más cómoda porque está arriba, en el estado más lindo, y porque es fácil de calcular: dividís un resultado por las ventas y listo. Pero el margen, solo, **no te dice si tu negocio es bueno**. Te dice cuánto ganás por cada venta, que es importante, pero es apenas una de las tres fuerzas que determinan la rentabilidad real de tu capital.",
      "Pensalo con dos negocios opuestos. Un supermercado tiene márgenes minúsculos, del 2 o 3%, y suele ser un gran negocio. Una joyería de lujo tiene márgenes enormes, del 40%, y puede ser un mal negocio. ¿Cómo es posible? Porque el supermercado **hace girar su capital muchísimas veces al año** —compra y vende el stock en días— mientras la joyería tiene una vitrina cara parada meses esperando un comprador. Lo que importa no es solo cuánto ganás por venta, sino **cuántas veces hacés girar tu capital** y **cuánto capital tuviste que poner** para lograrlo.",
      "Andina es la víctima perfecta de la obsesión por el margen. Su dueño mira el resultado, ve ventas que crecen de 7.400 a 8.200 y un margen operativo decente, y concluye que el negocio anda. Pero su capital está atrapado: cuentas por cobrar de 1.850 que se cobran lento, inventarios de 2.400 que crecen más rápido que las ventas. Su capital gira poco, y un capital que gira poco arruina la rentabilidad aunque el margen por venta sea bueno. El margen lo tranquiliza mientras la rotación lo funde.",
      "Esta semana rompemos la obsesión por el margen y la reemplazamos por una pregunta mucho más potente y mucho más difícil de responder con autocomplacencia: **¿cuánto rinde cada peso que invertí en este negocio?** Esa pregunta se responde con el **ROIC**, el retorno sobre el capital invertido. Y para construirlo necesitamos dos piezas nuevas: una medida limpia de lo que el negocio genera (el NOPAT) y una medida honesta de lo que el negocio consume (el capital invertido).",
    ],
  },
  {
    heading: "DuPont: descomponer la rentabilidad en tres palancas",
    paragraphs: [
      "La herramienta clásica para entender de qué está hecha la rentabilidad se llama **descomposición DuPont**, por la empresa que la popularizó hace un siglo. Su idea es elegante: la rentabilidad sobre el patrimonio (**ROE**) no es un número monolítico, sino el **producto de tres palancas independientes** que se pueden mejorar por separado. La fórmula es ROE = Margen neto × Rotación del activo × Multiplicador financiero, o en sus componentes: (Resultado/Ventas) × (Ventas/Activo) × (Activo/Patrimonio Neto).",
      "La **primera palanca, el margen** (Resultado/Ventas), mide cuánto ganás por cada peso de venta. Es la única que muchas administraciones miran, y se mejora subiendo precios o bajando costos. La **segunda palanca, la rotación** (Ventas/Activo), mide cuántas veces girás tu activo en ventas durante el año: es la eficiencia con que usás lo que tenés. Se mejora vendiendo más con el mismo activo, o vendiendo lo mismo con menos activo —cobrando más rápido, reduciendo stock—. La **tercera palanca, el multiplicador financiero** (Activo/Patrimonio Neto), mide cuánto apalancás con deuda: amplifica la rentabilidad sobre el capital propio, pero también el riesgo.",
      "Lo revelador de DuPont es que **dos empresas con el mismo ROE pueden tener motores completamente distintos**. Una lo logra con margen alto y rotación baja (la joyería); otra con margen bajo y rotación altísima (el supermercado). Saber cuál es tu mezcla cambia por completo el plan de acción. Si tu rentabilidad es baja, DuPont te dice **dónde está el problema**: en el margen, en la rotación o en el apalancamiento. Sin DuPont, andás a ciegas tocando precios cuando quizás el problema es que tu stock no rota.",
      "Aplicado a Andina, el diagnóstico es nítido. Su margen no es el problema: el negocio operativo genera buen resultado bruto. Su **rotación es la palanca floja**: con un activo de más de 7.000 y ventas de 8.200, su activo apenas gira algo más de una vez al año, lastrado por las cuentas por cobrar lentas y el inventario inflado. Y su **multiplicador está jugando en contra**: el apalancamiento, que debería amplificar la rentabilidad, la destruye porque la deuda es carísima (descubierto al 85%). DuPont muestra que el dueño de Andina está mirando la única palanca que funciona —el margen— y es ciego a las dos que lo están hundiendo.",
    ],
  },
  {
    heading: "Por qué el margen solo no alcanza: la trampa de la rotación",
    paragraphs: [
      "Profundicemos en la palanca que el margen oculta, porque es donde mueren los negocios rentables: la **rotación**. La rotación mide la velocidad a la que tu capital se convierte en ventas y vuelve a vos como caja. Un capital que rota rápido trabaja muchas veces al año; uno que rota lento trabaja poco, y cada vuelta que no da es rentabilidad que no generás. Por eso un margen excelente sobre un capital que casi no se mueve da un negocio mediocre.",
      "La matemática lo hace evidente. Imaginá dos empresas con el mismo capital invertido. La primera tiene 5% de margen pero rota su capital 4 veces al año: su retorno sobre el capital es del orden de 20%. La segunda tiene 15% de margen —el triple— pero rota su capital solo una vez al año: su retorno es 15%, menor que la primera pese a triplicar el margen. La velocidad le ganó a la rentabilidad por venta. Esta es, exactamente, la razón por la que el supermercado le gana a la joyería.",
      "En Andina la trampa de la rotación está en el **capital de trabajo**. Las cuentas por cobrar de 1.850 y los inventarios de 2.400 representan plata inmovilizada que no está girando: clientes que tardan en pagar y stock que tarda en venderse. Mientras esa plata está quieta, no genera ventas nuevas ni rentabilidad. El crecimiento de ventas que enorgullece al dueño se está financiando, en realidad, inmovilizando cada vez más capital de trabajo, lo que hunde la rotación y, con ella, el retorno sobre el capital. Crece la venta y empeora el negocio.",
      "La conclusión de gestión es contundente y conecta directamente con las semanas anteriores: el **capital de trabajo mal gestionado mata negocios rentables**. La Semana 1 mostró cómo el aumento de cuentas por cobrar (330) e inventarios (550) drenaba la caja operativa; la Semana 2 mostró que 290 de esa cartera y 420 de ese stock ni siquiera valen lo que figuran. Ahora la Semana 3 cierra el argumento: ese capital de trabajo inflado es lo que destruye la rotación y, por lo tanto, el ROIC. Es el mismo problema visto desde tres ángulos: caja, valor y rentabilidad.",
    ],
  },
  {
    heading: "NOPAT: la utilidad operativa, limpia de ruido financiero",
    paragraphs: [
      "Para medir bien un negocio necesitamos aislarlo de **cómo está financiado**. La utilidad neta mezcla dos cosas que conviene separar: cómo opera la empresa y cuánta deuda cara arrastra. Dos empresas con exactamente el mismo negocio pero distinta estructura de deuda muestran utilidades netas muy diferentes, y eso no significa que una sea mejor negocio que la otra. Significa que una se financió distinto. Para juzgar el negocio en sí, las finanzas usan el **NOPAT**: Net Operating Profit After Taxes, la utilidad operativa después de impuestos.",
      "El NOPAT se calcula como **EBIT × (1 − t)**: tomás el resultado operativo y le restás los impuestos que pagaría ese resultado **como si la empresa no tuviera deuda**. Fijate la sutileza: no restás los intereses reales, porque los intereses son consecuencia de la decisión de financiamiento, no del negocio. El NOPAT pregunta: si esta empresa no debiera un centavo, ¿cuánta utilidad operativa neta de impuestos generaría? Esa cifra mide la **capacidad de generación operativa pura**, antes de cualquier decisión sobre deuda.",
      "Calculémoslo para Andina con sus números reales de 2024. El **EBIT es 830** (el resultado operativo, antes de intereses e impuestos). La **tasa impositiva t es 35%**. Entonces el **NOPAT = 830 × (1 − 0,35) = 830 × 0,65 = 539,5 ≈ 540**. Andina genera unos 540 de utilidad operativa neta de impuestos. Esa es la potencia real de su negocio, despojada de su estructura de financiamiento.",
      "Comparemos ahora el NOPAT de 540 con el **resultado neto contable de 175**, y aparece la lección central de las finanzas corporativas. La diferencia son, esencialmente, los **560 de intereses** (ajustados por su efecto impositivo) que se lleva el financiamiento caro. El negocio operativo de Andina genera 540; la estructura financiera se devora la mayor parte y deja solo 175 en la última línea. El NOPAT le devuelve al dueño la cifra que el ruido financiero le escondía: su negocio es tres veces mejor de lo que la utilidad neta sugiere, pero su financiamiento es tres veces peor de lo que tolera.",
    ],
  },
  {
    heading: "Capital Invertido: cuánta plata pusiste realmente a trabajar",
    paragraphs: [
      "El NOPAT nos dice cuánto genera el negocio; ahora necesitamos saber **cuánto capital tuvimos que poner** para generarlo. Sin esa segunda pieza, el NOPAT es un número suelto: 540 es excelente si invertiste 2.000 y mediocre si invertiste 6.000. Esa medida del capital realmente puesto a trabajar es el **Capital Invertido**, y de forma operativa se calcula como **Capital de Trabajo + Activo Fijo**.",
      "El **capital de trabajo** es lo que queda inmovilizado en el ciclo operativo: **cuentas por cobrar + inventarios − proveedores**. Es lo que vos financiás a tus clientes (al venderles a plazo) y a tu stock (al comprarlo antes de venderlo), menos lo que tus proveedores te financian a vos. En Andina: cuentas por cobrar 1.850 + inventarios 2.400 − proveedores 1.280 = **2.970 de capital de trabajo**. Casi tres millones inmovilizados solo en el ciclo operativo, una cifra enorme para una empresa que vende 8.200.",
      "El **activo fijo** es la infraestructura productiva: terreno, edificio, maquinaria, rodados. En Andina, a valor contable: terreno 350 + edificio 620 + maquinaria 1.450 + rodados 140 = **2.560 de activo fijo**. Sumando ambos componentes, el **Capital Invertido de Andina ronda los 5.530** (2.970 de capital de trabajo + 2.560 de activo fijo). Es un capital invertido pesado, y un capital invertido grande es estructuralmente difícil de hacer rendir: cada peso adicional inmovilizado es un peso más que el NOPAT tiene que justificar.",
      "Acá conviene una observación de gestión que conecta con la Semana 2. Buena parte del capital de trabajo de Andina está **inflado e improductivo**: de los 1.850 de cuentas por cobrar, 290 son mora dura; de los 2.400 de inventario, 420 son obsoletos. Es decir, unos 710 del capital invertido están atrapados en activos que ni rotan ni se cobran. No solo es mucho capital: es mucho capital **muerto**. Esa es la pista que después convierte el diagnóstico en plan de acción, porque liberar ese capital muerto sube el ROIC sin tocar el margen.",
    ],
  },
  {
    heading: "ROIC: el verdadero termómetro del negocio",
    paragraphs: [
      "Con las dos piezas listas, llegamos a la pregunta de oro de cualquier dueño: **¿cuánto rinde, de verdad, el capital que tengo metido en este negocio?** La respuesta es el **ROIC** (Return on Invested Capital), y su fórmula es la más importante del programa hasta acá: **ROIC = NOPAT / Capital Invertido**. Mide cuánto rinde, después de impuestos, cada peso de capital puesto a trabajar, aislado por completo de cómo se financió ese capital.",
      "Para Andina, el cálculo cierra el caso: **ROIC = 540 / 5.530 ≈ 9,8%**, redondeando un **10%**. Es decir, cada peso invertido en el negocio de Andina rinde apenas un 10% anual después de impuestos. Y notá algo: si en lugar del capital de presentación usáramos el capital de gestión —sincerando los 710 de incobrables y obsoletos que no deberían contar como capital productivo—, el capital invertido bajaría a alrededor de 4.820 y el ROIC subiría a cerca del 11%. El propio acto de limpiar el balance mejora la lectura del retorno, y señala el camino: liberar capital muerto es la palanca más directa para subir el ROIC.",
      "El contraste con la lectura contable es demoledor. Contablemente, Andina **gana**: muestra 175 de resultado neto y ventas en crecimiento, y el dueño está conforme mirando el margen. Pero el ROIC dice otra cosa: el negocio entero, con todo su capital de 5.530, rinde solo un 10% después de impuestos. El margen miraba una venta; el ROIC mira el negocio completo. Y el negocio completo, medido honestamente, rinde flojo.",
      "¿Es bueno o malo ese 10%? La respuesta no está en el número aislado, sino en compararlo con **cuánto cuesta el capital** que financia el negocio. Si el capital de Andina cuesta más del 10% —y con descubierto al 85% y deuda en USD al 18%, seguramente cuesta bastante más—, entonces Andina **destruye valor**: rinde menos de lo que paga por financiarse. Esa comparación, ROIC contra costo de capital, es la frontera entre crear y destruir valor, y es justo donde arranca la Semana 4. El ROIC de hoy es la mitad de esa ecuación; la otra mitad le va a poner número exacto al drama de Andina.",
    ],
  },
  {
    heading: "Interrelación: cómo se enlazan margen, rotación, apalancamiento, NOPAT y ROIC",
    paragraphs: [
      "Conviene ver el cuadro completo, porque todas las piezas de la semana son la misma historia contada con distinto vocabulario. **DuPont y ROIC apuntan a lo mismo desde ángulos distintos**: DuPont descompone la rentabilidad del patrimonio en margen, rotación y apalancamiento; el ROIC mide la rentabilidad del capital operativo aislando el apalancamiento. Donde DuPont mezcla el efecto del financiamiento en el multiplicador, el ROIC lo saca afuera para juzgar el negocio puro. Son lentes complementarias: DuPont diagnostica el porqué; el ROIC sentencia el cuánto.",
      "El puente entre ambas es la **rotación**, que aparece en las dos. En DuPont la rotación es Ventas/Activo; en el ROIC está implícita en el Capital Invertido del denominador. Cuando el capital de trabajo de Andina se infla (cuentas por cobrar lentas, inventario obsoleto), pasan dos cosas a la vez: la rotación de DuPont cae y el capital invertido del ROIC sube. Es el mismo fenómeno —capital inmovilizado— deprimiendo ambos indicadores. Por eso atacar el capital de trabajo mejora simultáneamente la rotación, el ROIC y, como vimos en la Semana 1, la caja. Una sola acción, tres beneficios.",
      "El otro enlace es entre **NOPAT y margen**. El NOPAT no es más que el resultado operativo después de impuestos, así que un buen margen operativo alimenta un buen NOPAT. Pero el NOPAT, dividido por el capital invertido, vuelve a someter ese margen al juicio de la rotación: un NOPAT decente sobre un capital enorme da un ROIC pobre. Por eso decimos que el margen es un tercio de la historia: alimenta el numerador del ROIC, pero el denominador —el capital, gobernado por la rotación— tiene la última palabra.",
      "Y todo se conecta con las semanas previas, formando un sistema. La Semana 1 nos dio los estados y mostró que el resultado no es la caja. La Semana 2 nos enseñó a sincerar el balance a valor real, dándonos un capital invertido creíble. La Semana 3 toma ese capital sincerado, lo cruza con el NOPAT y produce el ROIC, el primer veredicto sobre si Andina crea o destruye valor. Cada semana no agregó un tema suelto: agregó una capa que apoya sobre la anterior y prepara la siguiente. Ese es el método: de leer, a traducir, a valuar.",
    ],
  },
  {
    heading: "Errores frecuentes del CEO con la rentabilidad",
    paragraphs: [
      "**Confundir margen con rentabilidad del negocio.** El error fundacional de la semana. El dueño de Andina cree que un margen decente significa un buen negocio, e ignora que su ROIC ronda apenas el 10%. El margen mide una venta; la rentabilidad del negocio mide todo el capital. Una empresa con buen margen y ROIC bajo está atrapando capital que rendiría más en cualquier otro lado, incluso en un plazo fijo. El margen tranquiliza; el ROIC desnuda.",
      "**Juzgar el negocio por la utilidad neta.** Andina muestra 175 de resultado neto, pero su NOPAT es 540. Quien juzga el negocio por los 175 está culpando a la operación de un problema que es de financiamiento. La utilidad neta mezcla el negocio con la deuda; separar ambos con el NOPAT evita el diagnóstico equivocado de tocar precios o costos cuando lo que hay que arreglar es la estructura financiera.",
      "**Ignorar el capital de trabajo como fuente de capital invertido.** Muchos dueños asocian capital invertido solo con maquinaria y edificios, y se olvidan de que el capital de trabajo de Andina (2.970) es mayor que su activo fijo (2.560). El capital más pesado de Andina no está en sus máquinas: está atrapado en cuentas por cobrar e inventarios. No verlo lleva a buscar eficiencias en la planta mientras la sangría real está en la cobranza y el stock.",
      "**Festejar el crecimiento de ventas sin mirar el capital que consume.** Andina crece de 7.400 a 8.200 y el dueño lo celebra. Pero ese crecimiento vino inmovilizando más capital de trabajo (330 más de cuentas por cobrar, 550 más de inventario), lo que hundió la rotación y el ROIC. Crecer sin controlar el capital que el crecimiento consume es crecer hacia la destrucción de valor. La pregunta correcta no es solo cuánto crecés, sino cuánto capital te cuesta cada peso de crecimiento.",
    ],
  },
  {
    heading: "Qué decisiones habilita pasar de la utilidad al valor",
    paragraphs: [
      "La primera decisión que habilita el ROIC es **liberar capital muerto para subir la rentabilidad sin tocar el margen**. En Andina, sincerar y liquidar los 420 de inventario obsoleto y cobrar o castigar los 290 de mora dura reduce el capital invertido en unos 710, lo que por sí solo levanta el ROIC del 10% hacia el 11%. Es la palanca más rápida y más al alcance de la mano: no requiere vender más ni subir precios, solo dejar de inmovilizar capital en activos que no trabajan.",
      "La segunda decisión es **atacar la palanca correcta según lo que diga DuPont**. Como el diagnóstico de Andina señala a la rotación y al apalancamiento, no al margen, el plan de acción se reordena: acelerar la cobranza (acortar plazos, premiar pronto pago, frenar el crédito a morosos), reducir el inventario a niveles que roten, y refinanciar la deuda cara. Tocar precios sería curar la enfermedad equivocada. DuPont evita ese desperdicio de energía dirigiendo el esfuerzo a donde de verdad duele.",
      "La tercera decisión es **separar el problema operativo del financiero**, ahora con números. El NOPAT de 540 frente al resultado neto de 175 prueba que Andina tiene un buen negocio (540) mal financiado (los intereses se comen el resto). Eso autoriza una conversación distinta con el banco y con uno mismo: el problema no es producir ni vender, es la estructura de deuda. Refinanciar el descubierto al 85% —quizás usando el terreno oculto de 900 como garantía, según vimos en la Semana 2— atacaría la raíz sin tocar la operación.",
      "Finalmente, esta semana habilita la pregunta que define el destino de Andina y que respondemos la próxima: **¿el ROIC supera al costo del capital?** Hoy sabemos que Andina rinde un 10%. La Semana 4 va a calcular cuánto le cuesta su capital, y si ese costo supera el 10% —como todo indica—, el veredicto será que Andina, pese a su ganancia contable y su crecimiento de ventas, **destruye valor en cada vuelta**. Pasar de la utilidad al valor no es un ejercicio académico: es la diferencia entre un dueño que cree que va bien y uno que sabe la verdad y puede cambiarla.",
    ],
  },
];
