// Contenido ampliado y detallado para el Word de la Semana 12.
// Valuación integral por DCF y plan de creación de valor.
// Markdown-lite: **negrita** y líneas que arrancan con "- " para listas.

export const deepDive12: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'El valor de una empresa no es lo que acumuló, es la caja que va a generar',
    paragraphs: [
      'Durante once semanas el programa entrenó una sola habilidad de fondo: leer la verdadera información que se esconde detrás de la contabilidad de presentación. Aprendimos a distinguir lo económico de lo financiero, a medir si el negocio rinde más que su costo de capital con la comparación entre ROIC y WACC, a entender cómo el capital de trabajo y el apalancamiento drenan o crean caja, y a desarmar las tasas hasta el hueso. Todo eso confluye ahora en la pregunta más importante que un dueño puede hacerse, la que da sentido a todas las anteriores: cuánto vale mi empresa y qué la hace valer más.',
      'La respuesta exige desterrar una creencia muy arraigada. El valor de una empresa no es su patrimonio contable, ni la suma de sus activos, ni el último resultado neto. El valor de una empresa es **la caja futura que va a generar, traída a hoy**. Una empresa vale por lo que va a producir mañana, no por lo que acumuló ayer. El pasado, los activos históricos y las utilidades contables son a lo sumo pistas sobre esa capacidad futura, pero no son el valor en sí. Esta inversión de perspectiva, del pasado acumulado al futuro descontado, es el corazón de toda valuación seria.',
      'La herramienta que materializa esta idea es el **flujo de fondos descontado**, o DCF por sus siglas en inglés. El DCF proyecta la caja libre que el negocio va a generar en los próximos años, le suma una estimación del valor de todo lo que viene después, y trae ese conjunto al presente con una tasa que captura el riesgo y el costo de oportunidad. No es una fórmula mágica ni un oráculo: es un razonamiento explícito y discutible sobre el futuro, cuya principal virtud es obligarte a hacer visibles todos los supuestos que sostienen el número.',
      'Andina es el caso integrador perfecto porque su valuación por DCF revela la distancia exacta entre lo que el dueño cree y lo que la realidad muestra. El dueño cree que su empresa vale lo que dice su patrimonio contable, alrededor de 2770, porque vende cada vez más y da ganancia. La valuación va a mostrar que su negocio operativo tiene buen pulso pero que su deuda neta se queda con buena parte del valor, y que mientras su ROIC siga por debajo del WACC está destruyendo valor cada año que opera, aunque la contabilidad muestre utilidad. Esa brecha es la lección final del programa.',
    ],
  },
  {
    heading: 'El FCFF: el combustible de la valuación',
    paragraphs: [
      'El **Free Cash Flow to the Firm (FCFF)** es la caja que el negocio genera para repartir entre todos sus financiadores, bancos y dueños por igual, después de pagar todo lo que el negocio necesita para seguir funcionando y creciendo. Es el combustible de la valuación porque es lo único realmente disponible para quienes pusieron capital. La construcción parte del resultado operativo y lo va depurando hasta dejar caja pura: **FCFF = EBIT·(1 − t) + Amortizaciones − CAPEX − Variación de capital de trabajo**.',
      'Cada término encierra una idea del programa. El **EBIT·(1 − t)** es el NOPAT, el resultado operativo después de impuestos calculado como si la empresa no tuviera deuda, para no contaminar la caja operativa con la estructura de financiamiento, que se incorpora más tarde vía el WACC. Las **amortizaciones se suman de nuevo** porque son un cargo contable que no implica salida de caja. El **CAPEX se resta** porque la inversión en activo fijo es caja real que el negocio necesita para sostenerse. Y la **variación del capital de trabajo se resta o se suma** según consuma o libere caja: más cuentas por cobrar e inventarios consumen, más proveedores liberan.',
      'Por qué el FCFF y no el resultado contable o el EBITDA. El resultado neto contable contiene partidas que no son caja y está contaminado por la estructura de deuda; el EBITDA ignora por completo la inversión en CAPEX y en capital de trabajo que el negocio necesita para seguir vivo. El FCFF es la única medida que refleja la caja libre, limpia y repartible, después de pagar todo lo imprescindible. Todo lo que el programa enseñó sobre capital de trabajo y sobre CAPEX vive precisamente en esta construcción: no son temas separados, son los componentes que determinan cuánta caja libre queda.',
      'Hagamos el número con Andina para verlo concreto. Su EBIT es 830 y la tasa de impuesto es 35%, así que el NOPAT es 830·(1 − 0,35) = **539,5**. Le sumamos las amortizaciones de 290, le restamos el CAPEX de 440, y le restamos la variación de capital de trabajo del año, que fue muy negativa: las cuentas por cobrar aumentaron 330 y los inventarios 550 mientras los proveedores aportaron 160, de modo que el capital de trabajo consumió alrededor de 720 netos de caja. El FCFF resultante es aproximadamente 539,5 + 290 − 440 − 720 ≈ **−330**: negativo. El negocio operativo, tal como está gestionado hoy, no genera caja libre, la consume, y casi todo el problema está en el capital de trabajo que devora más que lo que el negocio produce.',
    ],
  },
  {
    heading: 'Descontar al WACC: por qué la tasa lo cambia todo',
    paragraphs: [
      'Un peso dentro de cinco años no vale un peso hoy: vale menos, por dos razones que conviven. Primero, porque el peso de hoy lo podrías invertir y tenerlo trabajando durante esos cinco años. Segundo, porque sobre el peso futuro pesa el riesgo de que no llegue, de que el negocio no genere lo proyectado. La tasa que captura simultáneamente el costo de oportunidad y el riesgo es el **WACC**, el costo promedio ponderado del capital: el rendimiento mínimo que la empresa debe generar para satisfacer tanto a los bancos, vía el costo de la deuda, como a los dueños, vía el costo del capital propio, ponderado por cuánto pesa cada fuente.',
      'En LatAm el WACC es estructuralmente alto, y entender por qué importa para no subestimar la vara. El costo del capital propio carga el riesgo país medido por el EMBI, una prima por tamaño que castiga a las PyMEs por su menor liquidez y mayor fragilidad, y se construye sobre una tasa libre de riesgo y una prima de mercado base. El costo de la deuda, como vimos en la semana anterior, también es elevado. Con los supuestos del programa para Andina, el WACC ronda el **18 a 20%**. Esa tasa es la vara que decide todo: si el negocio rinde un ROIC por encima de ella, crea valor; si rinde por debajo, destruye valor cada año que opera, por más que la contabilidad muestre ganancia.',
      'Descontar al WACC significa, mecánicamente, dividir cada flujo futuro por (1 + WACC) elevado al número de años que falta para recibirlo. Un flujo de 100 dentro de un año, descontado a un WACC del 19%, vale hoy 100/1,19 ≈ 84; ese mismo flujo dentro de cinco años vale apenas 100/1,19^5 ≈ 42, la mitad. Cuanto más lejano el flujo y más alta la tasa, menos pesa hoy. Esta es la razón por la cual en LatAm el valor se concentra en los primeros años de la proyección: el WACC alto castiga durísimo lo lejano, y los flujos de la década entrante valen mucho más que los de la siguiente.',
      'Hay una consecuencia estratégica que el dueño no siempre ve. Como el WACC alto comprime el valor de los flujos lejanos, en LatAm la creación de valor de corto y mediano plazo pesa muchísimo. Mejorar la caja de los próximos tres años mueve la aguja del valor mucho más que prometer un futuro brillante a diez años vista, que el descuento prácticamente borra. Para Andina, esto significa que arreglar su capital de trabajo y su deuda ahora, liberando caja en el horizonte cercano, tiene un impacto desproporcionado sobre su valor frente a cualquier plan de expansión lejana.',
    ],
  },
  {
    heading: 'El valor terminal de Gordon: la mayor parte del valor está en el horizonte',
    paragraphs: [
      'No se puede proyectar flujos para siempre, así que la práctica es proyectar un horizonte explícito, típicamente de cinco a diez años, y resolver todo lo que viene después con el **valor terminal**, calculado con la fórmula de Gordon. La idea es suponer que, a partir del último año proyectado, los flujos crecen a una tasa constante y modesta llamada **g**, en perpetuidad. La fórmula es **VT = FCFF·(1 + g)/(WACC − g)**: se toma el flujo del último año, se lo hace crecer una vez por g, y se lo divide por la diferencia entre el WACC y g.',
      'Lo que sorprende a casi todos los dueños la primera vez es que el valor terminal suele representar la mayor parte del Enterprise Value, a veces el 60 o el 70% del total. Esto tiene sentido: el horizonte explícito captura solo los primeros años, mientras que el valor terminal captura toda la vida restante de la empresa, que es muchísimo más larga. Pero tiene una implicación incómoda: el supuesto de g, que parece un detalle técnico, termina determinando la mayor porción del valor. Por eso la elección de g es delicadísima y debe hacerse con prudencia casi obsesiva.',
      'La regla de prudencia es clara: **g nunca debería superar el crecimiento de largo plazo de la economía en la que operás**, porque ninguna empresa puede crecer para siempre más rápido que el país que la contiene; si lo hiciera, en el infinito sería más grande que toda la economía, lo cual es absurdo. Para una PyME LatAm, una g del 2 al 3% en dólares es razonable. Una g inflada, del 6 o 7%, no refleja una empresa pujante: refleja una valuación tramposa que se cae al primer escrutinio serio.',
      'Hay además una trampa matemática en el denominador (WACC − g) que conviene conocer. Cuanto más cerca está g del WACC, más chico es el denominador y más explota el valor terminal hacia el infinito. Esto significa que pequeños cambios en g pueden cambiar enormemente la valuación, lo cual no es un defecto de la fórmula sino una verdad sobre la incertidumbre: el valor de una empresa es genuinamente sensible a los supuestos sobre su futuro lejano. La conclusión madura es que una valuación no es un número mágico sino un rango razonado, y que defender una valuación es defender sus supuestos, no recitar una cifra.',
    ],
  },
  {
    heading: 'De Enterprise Value a Equity Value: lo que realmente vale tu parte',
    paragraphs: [
      'El **Enterprise Value (EV)** es el valor de la empresa como negocio operativo: lo que valen los activos productivos que generan el FCFF, con independencia de cómo estén financiados. Se obtiene sumando los FCFF proyectados descontados año a año más el valor terminal descontado: **EV = Σ FCFF_t/(1 + WACC)^t + VT/(1 + WACC)^n**. El EV responde una pregunta concreta: cuánto vale la máquina de generar caja, mirada en su totalidad, sea quien sea su dueño y sin importar cuánta deuda cargue.',
      'Pero el dueño no se queda con todo el Enterprise Value, porque una parte de la empresa, en los hechos, le pertenece a los bancos. Para saber cuánto vale su parte hay que restar la deuda neta: **Equity Value = Enterprise Value − Deuda neta**, donde **Deuda neta = deuda financiera total − caja y equivalentes**. La lógica es transparente: el valor del negocio se reparte primero entre los acreedores, que tienen prioridad, y lo que sobra después de cancelar la deuda es lo que vale el capital de los dueños. La caja se resta de la deuda porque podría usarse para cancelarla.',
      'Esta resta es el momento de la verdad para muchos dueños endeudados, y para Andina en particular. Su deuda financiera incluye el descubierto bancario de 540, los préstamos bancarios de corto plazo de 620, los préstamos de largo plazo de 980 y los cheques diferidos de 430, lo que suma 2570 de deuda financiera. Contra eso tiene caja por 180 y inversiones transitorias por 60, es decir 240 de liquidez. La deuda neta resulta entonces 2570 − 240 = **2330**. Es una mochila enorme: cualquiera sea el Enterprise Value que arroje la proyección, hay que restarle 2330 antes de saber qué le queda al dueño.',
      'De acá sale una de las ideas más potentes del programa para un dueño endeudado: **desapalancar y abaratar la deuda no es solo aliviar la caja, es transferir valor desde los bancos hacia los dueños**. Cada peso de deuda neta que Andina cancela es, mecánicamente, un peso de Equity Value que vuelve a su dueño, además del efecto indirecto de bajar los intereses, subir el NOPAT y reducir el riesgo que descuenta el mercado. Una empresa puede tener un Enterprise Value respetable y un Equity Value flaco porque la deuda se comió la diferencia; reducir esa deuda es la vía más directa para que el valor vuelva a las manos de quien arriesgó su capital.',
    ],
  },
  {
    heading: 'Interrelaciones: la valuación como síntesis de todo el programa',
    paragraphs: [
      'La valuación por DCF no es un tema nuevo que se agrega al final: es el lugar donde todo lo aprendido se encuentra y se mide en una sola unidad común, el valor. La conexión con **ROIC vs WACC** es la columna vertebral: el ROIC determina si los flujos que proyectamos crecen creando valor o destruyéndolo, y el WACC es la tasa exacta a la que los descontamos. Una empresa con ROIC por encima del WACC genera flujos que valen más que el capital que consumen y vale más que sus activos; una con ROIC por debajo, como Andina hoy, destruye valor en cada vuelta y por eso su Equity Value real queda por debajo de su patrimonio contable.',
      'La conexión con el **capital de trabajo** es la que más mueve la aguja en el corto plazo. Como vimos en el cálculo del FCFF, las cuentas por cobrar y los inventarios crecientes de Andina consumieron alrededor de 720 de caja en el año y llevaron su flujo libre a terreno negativo. Liberar ese capital atrapado, cobrando más rápido y depurando el inventario obsoleto de 420, no requiere vender una unidad más y sin embargo mejora directamente el FCFF, que es el numerador de toda la valuación. Es la palanca de creación de valor más rápida y más barata que tiene la empresa.',
      'La conexión con el **apalancamiento y las tasas** opera por dos vías simultáneas. Por un lado, la deuda neta se resta del Enterprise Value para llegar al Equity Value, así que menos deuda es más valor para el dueño de forma directa. Por otro lado, abaratar la deuda y reducir el riesgo financiero baja el WACC al que se descuentan todos los flujos futuros, y un WACC menor eleva tanto el Enterprise Value como el valor terminal. Las semanas 10 y 11 no fueron desvíos: fueron la preparación de dos de los insumos centrales de la valuación, la deuda neta y el WACC.',
      'Por último, la conexión con los **activos ocultos y sobrevaluados** que el programa enseñó a detectar completa la foto. Andina tiene un terreno que figura en libros a 350 y vale en el mercado alrededor de 900, una marca y una cartera de clientes que valen unos 650 y no aparecen en la contabilidad, y a la vez maquinaria parcialmente obsoleta e inventario de lenta rotación que valen menos de lo que dicen los libros. La valuación por caja captura el potencial de monetizar lo oculto y de no seguir invirtiendo en lo improductivo. Así, la semana final integra ROIC, WACC, capital de trabajo, apalancamiento, tasas y calidad de activos en una única respuesta sobre cuánto vale la empresa y por qué.',
    ],
  },
  {
    heading: 'Andina vista entera: una empresa sana por dentro y enferma por fuera',
    paragraphs: [
      'Pongamos toda la película junta. Lo que el dueño de Andina creía: vendo cada vez más, 8200 este año contra 7400 el anterior, gano plata, 175 de resultado neto, tengo activos y un terreno; mi empresa debe valer lo que dice mi patrimonio, unos 2770. Es una lectura honesta pero superficial, anclada en el pasado contable y en la línea del margen, que es exactamente la trampa que el programa enseñó a evitar.',
      'Lo que el análisis revela es otra historia. Sus cuentas por cobrar e inventarios atrapan caja, porque las ventas crecen pero no se cobran ni se rotan, llevando el FCFF a terreno negativo. Su descubierto al 85% y sus préstamos caros generan 560 de intereses sobre un EBIT de 830, es decir el 67% de lo operativo se evapora en deuda. Su ROIC está por debajo del WACC de 18 a 20%, de modo que destruye valor cada año aunque dé ganancia contable. Y al descontar su flujo libre y restar la deuda neta de 2330, su Equity Value real es bastante menor que el patrimonio contable que el dueño imaginaba. La distancia entre las dos lecturas es la distancia entre un dueño que mira el margen y un CEO que entiende el valor.',
      'Pero hay un lado luminoso que el mismo análisis pone a la vista. Andina tiene un terreno que vale 900 y figura a 350, más de 550 de valor oculto; una marca y una cartera de clientes que valen alrededor de 650 y no están en libros; y proveedores por 1280 que podría aprovechar mucho mejor para desplazar deuda cara. El negocio operativo, en su núcleo, tiene buen pulso: vende, tiene clientes, tiene activos valiosos subreconocidos. No es una empresa muerta ni un mal negocio.',
      'La síntesis es contundente: Andina es una empresa **sana por dentro y enferma por fuera**. El negocio operativo está bien; lo que la enferma es cómo está financiada y cómo administra su capital de trabajo. Y esa es la mejor noticia posible, porque a diferencia del mercado, del producto o de la competencia, que el dueño no controla, la estructura financiera y la gestión del capital de trabajo están enteramente bajo su mando. La enfermedad de Andina es curable, y la cura no depende de la suerte sino de la decisión.',
    ],
  },
  {
    heading: 'El plan de creación de valor: de destruir valor a empresa perdurable',
    paragraphs: [
      'El plan de creación de valor de Andina se ordena en cinco palancas, todas bajo control del dueño, y todas conectadas con una semana del programa. La primera es el **capital de trabajo**: reducir los días de cobro, depurar y vender el inventario obsoleto de 420, y estirar el plazo de los proveedores. El efecto es directo y rápido: libera caja, mejora el FCFF y sube el Enterprise Value. Es la palanca que más mueve la aguja en el corto plazo y la que no cuesta un peso de inversión, solo disciplina de gestión.',
      'La segunda palanca es el **costo de la deuda**: sustituir el descubierto al 85% por financiamiento de proveedores y por deuda más barata y más larga. El efecto es doble: baja los intereses, lo que sube el NOPAT, y reduce la deuda neta, lo que sube el Equity Value. La tercera palanca es el **apalancamiento** propiamente dicho: usar la caja liberada por las dos primeras palancas para desapalancar, y si hace falta vender activos ociosos, bajando la proporción de deuda hasta una cobertura sana. El efecto es reducir el riesgo financiero, lo que puede bajar el WACC y, por esa vía, subir el valor de todos los flujos futuros.',
      'La cuarta palanca son los **activos ociosos y ocultos**: monetizar el terreno revaluado, reconocer y poner a trabajar el valor de la marca, vender la maquinaria obsoleta y, sobre todo, no comprar CAPEX innecesario que solo inmoviliza caja. El efecto es generar fondos para desapalancar y mejorar el Equity Value real. La quinta palanca es la síntesis de todas, la relación **ROIC vs WACC**: combinando más margen operativo con menos capital invertido, el ROIC sube hasta superar al WACC, y en ese momento, el más importante de todos, la empresa deja de destruir valor y empieza a crearlo en cada vuelta.',
      'El mensaje de cierre del programa se cristaliza acá. Andina puede pasar de destruir valor a crearlo sin vender una sola unidad más, solo cobrando mejor, financiándose más barato, desapalancando y poniendo a trabajar sus activos ociosos. La creación de valor casi nunca viene de afuera, de más ventas o de un mejor mercado; viene de adentro, de decisiones que el dueño controla por completo. Esa es, en una frase, la diferencia entre un dueño que mira el margen y un CEO que entiende el valor, y es el aprendizaje que sintetiza las doce semanas.',
    ],
  },
  {
    heading: 'Errores frecuentes del CEO en la valuación',
    paragraphs: [
      'El primer error es **confundir el patrimonio contable con el valor de la empresa**. El patrimonio mira el pasado acumulado al costo histórico; el valor mira la caja futura descontada. Andina lo muestra con crudeza: su dueño cree que la empresa vale 2770 porque eso dice el patrimonio, cuando la valuación por caja, restada la deuda neta, arroja bastante menos. El patrimonio contable puede sobrevaluar o subvaluar enormemente según los activos ocultos y la deuda; nunca es el valor.',
      'El segundo error es **inflar la tasa g del valor terminal**. Como el valor terminal suele ser el 60 o 70% del total y el denominador es (WACC − g), una g optimista de más infla artificialmente toda la valuación. Es el truco más común para vender un número alto, y el primero que un comprador serio detecta. La g prudente, nunca superior al crecimiento de largo plazo de la economía, es la marca de una valuación honesta frente a una valuación de fantasía.',
      'El tercer error es **defender un número en lugar de los supuestos**. Una valuación no es una cifra sagrada sino un rango razonado: cambia con el WACC, con la g, con las proyecciones de caja. El CEO maduro nunca dice mi empresa vale exactamente X; dice mi empresa vale en este rango bajo estos supuestos, y acá están. Y a la inversa, si alguien le presenta una valuación sin mostrarle el FCFF proyectado, el WACC y la g, sabe que no le están valuando la empresa, le están vendiendo un número.',
      'El cuarto error es **valuar con EBITDA o resultado contable en lugar de caja libre**. El EBITDA ignora el CAPEX y el capital de trabajo que el negocio necesita para vivir, y el resultado contable está lleno de partidas que no son caja. Valuar Andina por su EBITDA de 1120 daría una foto engañosamente saludable, porque oculta que su capital de trabajo se devora la caja y que su FCFF es negativo. Solo la caja libre, depurada de todo lo que no es caja, cuenta la verdad sobre el valor.',
    ],
  },
  {
    heading: 'Qué decisiones habilita dominar la valuación',
    paragraphs: [
      'Un CEO que domina la valuación gana, antes que nada, la capacidad de **saber cuánto vale su empresa hoy y por qué**, no como una sensación sino como un número defendible con supuestos explícitos. Esto cambia toda conversación de venta, de incorporación de un socio, de sucesión familiar o de toma de deuda con garantía, porque deja de negociar desde la intuición y empieza a negociar desde un modelo que puede sostener frente a cualquier contraparte.',
      'La segunda decisión que habilita es **priorizar las palancas de valor por su impacto real**. Con el modelo en la mano, el dueño puede simular cuánto sube su Equity Value si libera capital de trabajo, cuánto si abarata la deuda, cuánto si desapalanca, y ordenar sus esfuerzos por retorno. Deja de dispersarse en mil mejoras y concentra su energía donde el modelo le muestra que la aguja se mueve más, que en LatAm casi siempre es la caja de los próximos años.',
      'La tercera decisión es **distinguir las mejoras que crean valor de las que solo lo aparentan**. Crecer en ventas inmovilizando más capital de trabajo y financiándolo con descubierto caro puede subir el resultado contable y destruir valor a la vez, como le pasa a Andina. Con la valuación como brújula, el dueño evalúa cada decisión por su efecto sobre el FCFF y sobre la relación entre ROIC y WACC, no por su efecto sobre el margen del trimestre. Esa brújula lo protege del crecimiento que enferma.',
      'La decisión final, y la que corona el programa, es **gobernar la empresa para crear valor de forma sostenida**. El dueño que entiende la valuación ya no administra para mostrar utilidad contable ni para que la caja apenas alcance: administra para que el ROIC supere de manera estable al WACC, para que la caja libre crezca, para que la deuda neta baje y el valor vuelva a sus manos. Convierte cada semana del programa en un instrumento de una sola partitura, la creación de valor, y deja atrás para siempre la mirada del dueño que confunde vender más con valer más. Ese salto, del margen al valor, es el objetivo último de Finanzas Corporativas para un CEO.',
    ],
  },
]
